"""Adapter protocols used by completion processing."""

from pathlib import Path
from typing import Protocol, runtime_checkable

from ..ports.pull_request_tracker import PRInfo
from ..ports.working_copy import (
    BranchPathsResult,
    DiffResult,
    PushResult,
    RebaseResult,
)


@runtime_checkable
class LabelAdapter(Protocol):
    """Protocol for label operations."""

    def add_label(self, issue_number: int, label: str) -> None: ...
    def remove_label(self, issue_number: int, label: str) -> None: ...


@runtime_checkable
class PRAdapter(Protocol):
    """Protocol for PR operations."""

    def create_pr(
        self, title: str, body: str, head: str, base: str = "main", draft: bool | None = None
    ) -> PRInfo: ...
    def add_comment(self, issue_or_pr_number: int, body: str) -> str: ...
    def get_prs_for_issue(self, issue_number: int, state: str = "open") -> list[PRInfo]: ...
    def get_prs_for_branch(self, branch: str, state: str = "open") -> list[PRInfo]: ...
    def set_pr_base(self, pr_number: int, base: str) -> None: ...


@runtime_checkable
class GitAdapter(Protocol):
    """Protocol for git operations."""

    def push(
        self,
        worktree: Path,
        remote: str = "origin",
        set_upstream: bool = True,
        skip_hooks: bool = False,
    ) -> PushResult: ...

    def rebase_on_branch(self, worktree: Path, target: str = "origin/main") -> RebaseResult: ...
    def create_branch_from_current(self, worktree: Path, branch: str) -> None: ...
    def list_branch_names(self, worktree: Path) -> list[str]: ...
    def get_current_branch(self, worktree: Path) -> str | None: ...
    def get_head_sha(self, worktree: Path) -> str | None: ...
    def has_uncommitted_changes(self, worktree: Path) -> bool: ...
    def has_tracked_changes(self, worktree: Path, include_staged: bool = True) -> bool: ...
    def list_dirty_files(self, worktree: Path, mode: str) -> list[str] | None: ...
    def diff_against_base(self, worktree: Path, base_ref: str) -> DiffResult: ...
    def branch_post_image_paths_against_base(
        self, worktree: Path, base_ref: str
    ) -> BranchPathsResult: ...
    def default_branch(self, repo_root: Path, remote: str = "origin") -> str: ...
