"""Project the charter into the tech lead's launch inputs (#7330).

The tech-lead prompt tells the agent to read ``tech-lead-charter.md`` from its
``tech-lead-data`` directory (``TECH_LEAD_CHARTER_SECTION``). This module writes
that file at launch, GENERATED from the same
:class:`~.tech_lead_charter_policy.TechLeadCharterPolicy` the orchestrator
enforces at completion, so what the agent is told it may do alone, must
propose, or may only advise is one computation with what is actually allowed.
Orchestrator-originated kinds (finding promotion) are not the agent's to
propose, so they are left out.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from ..domain.tech_lead_charter import (
    ORCHESTRATOR_CHARTER_ACTION_KINDS,
    CharterOutcome,
    CharterRole,
)
from ..domain.tech_lead_run_artifacts import TECH_LEAD_DATA_DIRNAME
from .tech_lead_charter_policy import TechLeadCharterPolicy

if TYPE_CHECKING:
    from ..infra.config import Config
    from .worktree_context import WorktreeContext

TECH_LEAD_CHARTER_FILENAME = "tech-lead-charter.md"

#: The per-outcome line labels, in rendering order. The contract test parses
#: the rendered file by these labels.
CHARTER_OUTCOME_LABELS: dict[CharterOutcome, str] = {
    CharterOutcome.EXECUTED: "Acts on its own",
    CharterOutcome.PROPOSED: "Proposes for operator approval",
    CharterOutcome.REFUSED_DESTRUCTIVE: "Always needs approval (destructive)",
    CharterOutcome.ADVICE_ONLY: "Advice only (recorded, not acted on)",
}

_PREAMBLE = """# Your charter

Generated by the orchestrator from `tech_lead.charter` and the per-action
`tech_lead.authority.*` modes. The orchestrator decides every action you propose
against exactly this charter when your run completes.

- Your decision file states INTENT only. You cannot choose a role or a depth:
  the orchestrator derives both from each action's `action_type`, so writing a
  role into your decision changes nothing.
- Noticing and advising are never restricted. Report every finding you have;
  a proposal the charter does not let you act on is recorded for the operator
  as advice, never dropped.
- Destructive actions never run unattended, whatever the dials say.
"""


def _dials(policy: TechLeadCharterPolicy, role: CharterRole) -> str:
    charter = policy.charter.for_role(role)
    if not charter.enabled:
        return "disabled"
    return f"depth: {charter.depth.value}, authority: {charter.authority.value}"


def render_tech_lead_charter_prompt(policy: TechLeadCharterPolicy) -> str:
    """The charter as the agent reads it: per role, what happens to each action."""
    grouped = policy.outcomes_by_role()
    lines = [_PREAMBLE]
    for role in CharterRole:
        lines.append(f"## {role.value} ({_dials(policy, role)})")
        lines.append("")
        by_outcome = grouped[role]
        rendered_any = False
        for outcome, label in CHARTER_OUTCOME_LABELS.items():
            kinds = [
                verdict.kind
                for verdict in by_outcome.get(outcome, ())
                if verdict.kind not in ORCHESTRATOR_CHARTER_ACTION_KINDS
            ]
            if kinds:
                rendered_any = True
                lines.append(f"- {label}: " + ", ".join(f"`{kind}`" for kind in kinds))
        if not rendered_any:
            lines.append("- No action type you can propose maps to this role yet.")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_tech_lead_charter_prompt(
    policy: TechLeadCharterPolicy, run_dir: Path
) -> Path:
    """Write the charter into the run's ``tech-lead-data`` (a required launch input)."""
    path = run_dir / TECH_LEAD_DATA_DIRNAME / TECH_LEAD_CHARTER_FILENAME
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_tech_lead_charter_prompt(policy), encoding="utf-8")
    return path


def stage_tech_lead_charter(
    config: "Config", run_dir: Path, ctx: "WorktreeContext"
) -> Path:
    """Launch step: write the charter from the LIVE config and list it in the
    run manifest, next to the assignment it accompanies."""
    path = write_tech_lead_charter_prompt(TechLeadCharterPolicy.from_config(config), run_dir)
    ctx.update_manifest({"tech_lead_charter": str(path)})
    return path
