"""E2E issue tracker adapter - Creates GitHub issues from E2E test failures.

This adapter implements the E2EIssueTracker protocol and uses the existing
GitHub HTTP client to create parent issues for E2E runs and sub-issues for
individual test failures.
"""

import logging
from typing import TYPE_CHECKING

from ..infra.e2e_db import E2ERun, E2ETestResult
from ..ports.e2e_issue_tracker import (
    E2EParentIssueInfo,
    E2ESubIssueInfo,
)

if TYPE_CHECKING:
    from ..adapters.github.http_client import GitHubHttpClient

logger = logging.getLogger(__name__)


class GitHubE2EIssueTracker:
    """Creates and manages E2E test failure issues on GitHub.

    Implements the E2EIssueTracker protocol using the GitHub HTTP client.
    Creates parent issues for E2E runs and links individual test failures
    as sub-issues.
    """

    def __init__(self, client: "GitHubHttpClient"):
        """Initialize with a GitHub HTTP client.

        Args:
            client: Configured GitHubHttpClient instance
        """
        self._client = client

    def create_run_issue(
        self,
        run: E2ERun,
        failed_count: int,
        labels: list[str] | None = None,
    ) -> E2EParentIssueInfo | None:
        """Create a parent issue for an E2E run with failures."""
        title = f"E2E Run #{run.id}: {failed_count} test failure{'s' if failed_count != 1 else ''}"

        # Build body with run details
        body_parts = [
            "## E2E Test Run Summary",
            "",
            f"**Run ID**: {run.id}",
            f"**Status**: {run.status}",
        ]

        if run.commit_sha:
            body_parts.append(f"**Commit**: `{run.commit_sha[:12]}`")
        if run.branch:
            body_parts.append(f"**Branch**: `{run.branch}`")
        if run.started_at:
            body_parts.append(f"**Started**: {run.started_at}")
        if run.duration_seconds:
            body_parts.append(f"**Duration**: {run.duration_seconds:.1f}s")

        body_parts.extend([
            "",
            f"**Failed Tests**: {failed_count}",
            "",
            "---",
            "",
            "Sub-issues will be created for each failing test.",
            "",
            "_This issue was auto-generated by the orchestrator._",
        ])

        body = "\n".join(body_parts)

        result = self._client.create_issue(
            title=title,
            body=body,
            labels=labels,
        )

        if result is None:
            logger.error("[e2e-tracker] Failed to create parent issue for run #%d", run.id)
            return None

        issue_number = result.get("number")
        if issue_number is None:
            logger.error("[e2e-tracker] Created issue but no number returned")
            return None

        html_url = result.get("html_url", "")

        # Get the node ID for sub-issue linking
        node_id = self._client.get_issue_node_id(issue_number)
        if not node_id:
            logger.warning(
                "[e2e-tracker] Created issue #%d but could not get node ID",
                issue_number,
            )
            # Return without node_id - sub-issue linking won't work but issue exists
            node_id = ""

        logger.info(
            "[e2e-tracker] Created parent issue #%d for E2E run #%d",
            issue_number,
            run.id,
        )

        return E2EParentIssueInfo(
            issue_number=issue_number,
            html_url=html_url,
            node_id=node_id,
        )

    def create_test_failure_issue(
        self,
        parent_issue: E2EParentIssueInfo,
        test_result: E2ETestResult,
        first_failing_sha: str,
        last_passing_sha: str | None,
        labels: list[str] | None = None,
    ) -> E2ESubIssueInfo | None:
        """Create a sub-issue for an individual test failure."""
        # Extract short test name from nodeid
        short_name = test_result.nodeid.split("::")[-1] if "::" in test_result.nodeid else test_result.nodeid

        title = f"E2E: {short_name}"

        # Build body with test details
        body_parts = [
            "## Test Failure Details",
            "",
            f"**Test**: `{test_result.nodeid}`",
            f"**Parent Issue**: #{parent_issue.issue_number}",
        ]

        if first_failing_sha:
            body_parts.append(f"**First Failing Commit**: `{first_failing_sha[:12]}`")
        if last_passing_sha:
            body_parts.append(f"**Last Passing Commit**: `{last_passing_sha[:12]}`")

        if test_result.duration_seconds:
            body_parts.append(f"**Duration**: {test_result.duration_seconds:.2f}s")

        if test_result.longrepr:
            body_parts.extend([
                "",
                "### Stack Trace",
                "",
                "```",
                test_result.longrepr[:2000],  # Truncate long traces
            ])
            if len(test_result.longrepr) > 2000:
                body_parts.append("... (truncated)")
            body_parts.append("```")

        body_parts.extend([
            "",
            "---",
            "",
            "### Instructions for Agent",
            "",
            "1. Analyze whether this is a test bug or a code bug",
            "2. Fix the underlying issue",
            "3. Run the test locally to verify the fix",
            "4. Use `agent-done completed` when finished",
            "",
            "_This issue was auto-generated from E2E test failure._",
        ])

        body = "\n".join(body_parts)

        result = self._client.create_issue(
            title=title,
            body=body,
            labels=labels,
        )

        if result is None:
            logger.error(
                "[e2e-tracker] Failed to create sub-issue for test %s",
                test_result.nodeid,
            )
            return None

        issue_number = result.get("number")
        if issue_number is None:
            logger.error("[e2e-tracker] Created issue but no number returned")
            return None

        html_url = result.get("html_url", "")

        # Link as sub-issue if parent has node_id
        if parent_issue.node_id:
            linked = self._client.add_sub_issue(parent_issue.node_id, issue_number)
            if linked:
                logger.info(
                    "[e2e-tracker] Linked issue #%d as sub-issue of #%d",
                    issue_number,
                    parent_issue.issue_number,
                )
            else:
                logger.warning(
                    "[e2e-tracker] Could not link #%d as sub-issue (will be standalone)",
                    issue_number,
                )
        else:
            logger.warning(
                "[e2e-tracker] No parent node_id - issue #%d not linked as sub-issue",
                issue_number,
            )

        logger.info(
            "[e2e-tracker] Created issue #%d for failing test: %s",
            issue_number,
            test_result.nodeid,
        )

        return E2ESubIssueInfo(
            issue_number=issue_number,
            html_url=html_url,
            parent_issue_number=parent_issue.issue_number,
            nodeid=test_result.nodeid,
        )

    def close_issue_with_comment(
        self,
        issue_number: int,
        comment: str,
    ) -> bool:
        """Close an issue with a comment explaining the resolution."""
        try:
            # Add comment
            self._client.add_comment(issue_number, comment)

            # Close the issue using update_issue_state
            self._client.update_issue_state(issue_number, "closed")

            logger.info("[e2e-tracker] Closed issue #%d", issue_number)
            return True
        except Exception as e:
            logger.error(
                "[e2e-tracker] Failed to close issue #%d: %s",
                issue_number,
                e,
            )
            return False

    def add_sub_issue(
        self,
        parent_node_id: str,
        child_issue_number: int,
    ) -> bool:
        """Link an issue as a sub-issue of a parent."""
        return self._client.add_sub_issue(parent_node_id, child_issue_number)

    def get_issue_node_id(self, issue_number: int) -> str | None:
        """Get the GraphQL node ID for an issue."""
        return self._client.get_issue_node_id(issue_number)
