"""Unified diagnostics for issue-orchestrator.

This module provides a single doctor function that both CLI and web can call.
"""

import os
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from ..ports.command_runner import CommandRunner
from .config import Config


@dataclass
class Check:
    """A single diagnostic check result."""
    name: str
    status: str  # "ok", "warning", "error", "info"
    detail: str


@dataclass
class DoctorResult:
    """Result of running diagnostics."""
    checks: list[Check] = field(default_factory=list)

    @property
    def overall(self) -> str:
        """Overall status based on all checks."""
        if any(c.status == "error" for c in self.checks):
            return "error"
        if any(c.status == "warning" for c in self.checks):
            return "warning"
        return "ok"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return {
            "overall": self.overall,
            "checks": [
                {"name": c.name, "status": c.status, "detail": c.detail}
                for c in self.checks
            ],
        }


def _check_guardrails_in_worktree(
    repo_root: Path,
    runner: CommandRunner,
    worktree_base: str = "../",
) -> list[Check]:
    """Create a test worktree and verify guardrails work.

    This tests the actual agent environment by:
    1. Creating a worktree using normal setup
    2. Running guardrail checks with the PATH as agents see it
    3. Cleaning up the worktree

    Args:
        repo_root: Path to the repository root
        runner: CommandRunner for executing test commands
        worktree_base: Base directory for worktrees

    Returns list of Check results for each guardrail tested.
    """
    from ..adapters.worktree._worktree import create_worktree, remove_worktree

    checks: list[Check] = []
    worktree_path: Optional[Path] = None

    try:
        # Create test worktree
        worktree_path, _, _, _, _, _, _ = create_worktree(
            repo_root=repo_root,
            issue_number=0,
            issue_title="doctor-guardrail-test",
            worktree_base=Path(worktree_base),
        )

        checks.append(Check(
            name="Test Worktree",
            status="ok",
            detail=f"Created at {worktree_path}",
        ))

        # Build the PATH as agents see it (wrapper dir prepended)
        wrapper_dir = Path(__file__).parent.parent / "scripts"
        env = os.environ.copy()
        env["PATH"] = f"{wrapper_dir}:{env.get('PATH', '')}"
        env.pop("ORCHESTRATOR_GH_AUTH", None)  # Ensure no auth token

        # Helper to run a guardrail test
        def test_blocked(cmd: list[str], name: str, detail_ok: str, detail_fail: str) -> Check:
            result = runner.run(
                cmd,
                cwd=worktree_path,
                env=env,
                timeout_seconds=5,
            )
            # Check for "BLOCKED" in stderr - this is the definitive signal
            # that the wrapper script blocked the command.
            # Note: We don't rely on returncode because SIGCHLD handlers
            # (used to auto-reap zombie processes) can interfere with
            # subprocess.run() exit code collection on some systems.
            if result.timed_out:
                return Check(name=name, status="warning", detail="Check timed out")
            if "BLOCKED" in result.stderr:
                return Check(name=name, status="ok", detail=detail_ok)
            else:
                debug_info = f"rc={result.returncode}, stderr={result.stderr[:200] if result.stderr else 'empty'}"
                return Check(name=name, status="error", detail=f"{detail_fail} [{debug_info}]")

        # Check: git push is blocked (uses wrapper script via PATH, not GitCLI)
        checks.append(test_blocked(
            ["git", "push"],
            "Git Push Guard",
            "git push correctly blocked",
            "git push was NOT blocked - guardrail failed",
        ))

        # Check 1: gh pr create is blocked
        # Use traceable strings so if guardrail fails, we know the source
        checks.append(test_blocked(
            ["gh", "pr", "create", "--title", "[DOCTOR-CHECK] DO NOT MERGE", "--body", "Auto-generated by doctor guardrail check - if you see this PR, the guardrail failed"],
            "GH PR Create Guard",
            "gh pr create correctly blocked",
            "gh pr create was NOT blocked - guardrail failed",
        ))

        # Check 2: gh pr review is blocked (whitelist enforcement)
        checks.append(test_blocked(
            ["gh", "pr", "review", "1", "--approve"],
            "GH PR Review Guard",
            "gh pr review correctly blocked",
            "gh pr review was NOT blocked - guardrail failed",
        ))

        # Check 3: gh api is blocked (whitelist enforcement)
        checks.append(test_blocked(
            ["gh", "api", "/user"],
            "GH API Guard",
            "gh api correctly blocked",
            "gh api was NOT blocked - guardrail failed",
        ))

        # Check 4: gh issue create is blocked (whitelist enforcement)
        checks.append(test_blocked(
            ["gh", "issue", "create", "--title", "[DOCTOR-CHECK] DO NOT CREATE", "--body", "Auto-generated by doctor guardrail check - if you see this issue, the guardrail failed"],
            "GH Issue Create Guard",
            "gh issue create correctly blocked",
            "gh issue create was NOT blocked - guardrail failed",
        ))


        # Check 6: agent-done is available
        result = runner.run(
            ["agent-done", "--help"],
            cwd=worktree_path,
            env=env,
            timeout_seconds=5,
        )
        if result.returncode == 0:
            checks.append(Check(
                name="agent-done Available",
                status="ok",
                detail="agent-done command found",
            ))
        elif "not found" in result.stderr.lower() or "no such file" in result.stderr.lower():
            checks.append(Check(
                name="agent-done Available",
                status="error",
                detail="agent-done command not found in PATH",
            ))
        else:
            checks.append(Check(
                name="agent-done Available",
                status="error",
                detail=f"agent-done command not working: {result.stderr[:100]}",
            ))

        # Check 7: Verify credential stripping by ACTUALLY trying to bypass
        # This simulates an agent trying to use the real binaries directly
        from ..control.isolation import build_isolation_prefix

        # Build isolation prefix (same as agent sessions get)
        isolation_script = build_isolation_prefix(
            worktree=worktree_path,
            isolation_mode="standard",
            scrub_env=True,
            isolate_home=False,
        )

        # 7a: Try gh auth with real binary
        try:
            real_gh = None
            for gh_path in ["/opt/homebrew/bin/gh", "/usr/local/bin/gh", "/usr/bin/gh"]:
                if os.path.isfile(gh_path) and os.access(gh_path, os.X_OK):
                    real_gh = gh_path
                    break

            if real_gh is None:
                checks.append(Check(
                    name="GH Auth Bypass Test",
                    status="warning",
                    detail="Could not find real gh binary to test",
                ))
            else:
                bypass_script = f'{isolation_script} && {real_gh} auth status 2>&1'
                result = runner.run(
                    f"bash -c '{bypass_script}'",
                    cwd=worktree_path,
                    env=os.environ.copy(),
                    timeout_seconds=10,
                    shell=True,
                )
                output = result.stdout + result.stderr
                if "Logged in" in output or "Active account" in output:
                    checks.append(Check(
                        name="GH Auth Bypass Test",
                        status="error",
                        detail=f"BYPASS: {real_gh} auth succeeded!",
                    ))
                else:
                    checks.append(Check(
                        name="GH Auth Bypass Test",
                        status="ok",
                        detail="Real gh cannot authenticate after scrubbing",
                    ))
        except Exception as e:
            checks.append(Check(
                name="GH Auth Bypass Test",
                status="warning",
                detail=f"Error: {e}",
            ))

        # 7b: Try git push with real binary (should fail without credentials)
        try:
            real_git = None
            for git_path in ["/opt/homebrew/bin/git", "/usr/local/bin/git", "/usr/bin/git"]:
                if os.path.isfile(git_path) and os.access(git_path, os.X_OK):
                    real_git = git_path
                    break

            if real_git is None:
                checks.append(Check(
                    name="Git Push Bypass Test",
                    status="warning",
                    detail="Could not find real git binary to test",
                ))
            else:
                # Try to push - should fail due to GIT_ASKPASS=/usr/bin/false
                bypass_script = f'{isolation_script} && {real_git} push --dry-run 2>&1 || true'
                result = runner.run(
                    f"bash -c '{bypass_script}'",
                    cwd=worktree_path,
                    env=os.environ.copy(),
                    timeout_seconds=10,
                    shell=True,
                )
                output = result.stdout + result.stderr
                # Success indicators (push worked - bad!)
                if "Everything up-to-date" in output or "->" in output.lower():
                    checks.append(Check(
                        name="Git Push Bypass Test",
                        status="error",
                        detail=f"BYPASS: {real_git} push succeeded!",
                    ))
                # Failure indicators (good - credentials blocked)
                elif any(x in output.lower() for x in ["authentication", "permission denied", "fatal:", "could not read"]):
                    checks.append(Check(
                        name="Git Push Bypass Test",
                        status="ok",
                        detail="Real git push blocked (no credentials)",
                    ))
                else:
                    # No upstream might be ok too
                    checks.append(Check(
                        name="Git Push Bypass Test",
                        status="ok",
                        detail="Real git push failed (expected)",
                    ))
        except Exception as e:
            checks.append(Check(
                name="Git Push Bypass Test",
                status="warning",
                detail=f"Error: {e}",
            ))

    except Exception as e:
        checks.append(Check(
            name="Test Worktree",
            status="error",
            detail=f"Failed to create: {e}",
        ))
    finally:
        # Cleanup
        if worktree_path and worktree_path.exists():
            try:
                remove_worktree(worktree_path)
            except Exception:
                pass  # Best effort cleanup

    return checks


def run_doctor(
    config: Optional[Config] = None,
    config_path: Optional[Path] = None,
    runner: Optional[CommandRunner] = None,
) -> DoctorResult:
    """Run all diagnostic checks.

    Args:
        config: Optional pre-loaded config (used by web when orchestrator is running)
        config_path: Optional path to config file (used by CLI)
        runner: Optional CommandRunner for executing test commands (guardrails check)

    Returns:
        DoctorResult with all check results
    """
    from ..adapters.github.http_client import (
        _read_keyring_token,
        validate_github_token,
        KEYRING_SERVICE,
        KEYRING_USERNAME,
    )

    result = DoctorResult()

    # === GitHub Authentication ===
    env_vars = ["ISSUE_ORCH_GITHUB_TOKEN", "GITHUB_TOKEN", "GH_TOKEN"]
    token_sources = []
    for var in env_vars:
        value = os.environ.get(var)
        if value:
            masked = value[:4] + "..." + value[-4:] if len(value) > 12 else "***"
            token_sources.append(f"{var}: {masked}")

    keyring_token = _read_keyring_token()
    if keyring_token:
        masked = keyring_token[:4] + "..." + keyring_token[-4:] if len(keyring_token) > 12 else "***"
        token_sources.append(f"Keyring ({KEYRING_SERVICE}/{KEYRING_USERNAME}): {masked}")

    if token_sources:
        result.checks.append(Check(
            name="Token Sources",
            status="ok",
            detail=", ".join(token_sources),
        ))
    else:
        result.checks.append(Check(
            name="Token Sources",
            status="error",
            detail="No GitHub token found",
        ))

    # Validate token with GitHub
    token_result = validate_github_token()
    if token_result.valid:
        result.checks.append(Check(
            name="GitHub Auth",
            status="ok",
            detail=f"Authenticated as: {token_result.username}",
        ))
    else:
        result.checks.append(Check(
            name="GitHub Auth",
            status="error",
            detail=token_result.error or "Unknown error",
        ))

    # === AI Provider Keys ===
    from .ai_keys import list_ai_keys, AI_PROVIDERS

    ai_keys = list_ai_keys()
    configured = [(k, s) for k, (_, s) in ai_keys.items() if s != "not set"]

    if configured:
        detail_parts = []
        for key_name, source in configured:
            provider_name = AI_PROVIDERS.get(key_name, {}).get("name", key_name)
            detail_parts.append(f"{provider_name} ({source})")
        result.checks.append(Check(
            name="AI Provider Keys",
            status="ok",
            detail=", ".join(detail_parts),
        ))
    else:
        result.checks.append(Check(
            name="AI Provider Keys",
            status="warning",
            detail="No AI keys configured. Run: issue-orchestrator keys set <provider>",
        ))

    # === Configuration ===
    if config is None and config_path:
        if config_path.exists():
            try:
                config = Config.load(config_path)
                result.checks.append(Check(
                    name="Config File",
                    status="ok",
                    detail=str(config_path),
                ))
            except Exception as e:
                result.checks.append(Check(
                    name="Config File",
                    status="error",
                    detail=f"Failed to load: {e}",
                ))
                return result
        else:
            result.checks.append(Check(
                name="Config File",
                status="warning",
                detail="Not found",
            ))
            return result

    if config is None:
        # Try to find config in new location
        from .config import list_configs, get_config_path

        cwd = Path.cwd()
        available = list_configs(cwd)
        if available:
            config_file = get_config_path(cwd, available[0])
            try:
                config = Config.load(config_file)
                result.checks.append(Check(
                    name="Config File",
                    status="ok",
                    detail=str(config_file.relative_to(cwd)),
                ))
            except Exception as e:
                result.checks.append(Check(
                    name="Config File",
                    status="error",
                    detail=f"Failed to load {config_file}: {e}",
                ))
                return result
        else:
            result.checks.append(Check(
                name="Config File",
                status="warning",
                detail="Not found in current directory",
            ))
            return result

    # Validate config
    validation_errors = config.validate()
    if validation_errors:
        result.checks.append(Check(
            name="Config Validation",
            status="error",
            detail="; ".join(validation_errors[:3]) + ("..." if len(validation_errors) > 3 else ""),
        ))
    else:
        result.checks.append(Check(
            name="Config Validation",
            status="ok",
            detail="All checks passed",
        ))

    # Check for unknown fields in config schema
    unknown_fields = config.validate_unknown_fields()
    if unknown_fields:
        field_names = [f[0] for f in unknown_fields]
        detail = ", ".join(field_names[:5]) + ("..." if len(field_names) > 5 else "")
        result.checks.append(Check(
            name="Config Schema",
            status="error" if config.config_strict else "warning",
            detail=f"Unknown fields: {detail}",
        ))
    else:
        result.checks.append(Check(
            name="Config Schema",
            status="ok",
            detail="No unknown fields",
        ))

    # Check for invalid template variables
    invalid_templates = config.validate_template_variables()
    if invalid_templates:
        details = []
        for agent_label, field_name, bad_vars in invalid_templates[:3]:
            details.append(f"{agent_label}.{field_name}: {{{', '.join(sorted(bad_vars))}}}")
        detail = "; ".join(details) + ("..." if len(invalid_templates) > 3 else "")
        result.checks.append(Check(
            name="Template Variables",
            status="error",
            detail=f"Invalid: {detail}",
        ))
    else:
        result.checks.append(Check(
            name="Template Variables",
            status="ok",
            detail="All template variables valid",
        ))

    # Repository
    if config.repo:
        result.checks.append(Check(
            name="Repository",
            status="ok",
            detail=config.repo,
        ))
    else:
        result.checks.append(Check(
            name="Repository",
            status="warning",
            detail="Not configured",
        ))

    # === Working Directory ===
    # Check for uncommitted changes that might confuse users
    # (agent worktrees will branch from main, not inherit these changes)
    if runner:
        repo_root = Path.cwd()
        try:
            from ..adapters.git.git_cli import GitCLI
            git = GitCLI(runner=runner)
            status_result = git.run(repo_root, ["status", "--porcelain"], timeout_s=10, check=False)
            if status_result.returncode == 0:
                has_uncommitted = bool(status_result.stdout.strip())
                if has_uncommitted:
                    result.checks.append(Check(
                        name="Working Directory",
                        status="warning",
                        detail="Uncommitted changes (won't affect agent worktrees - they branch from main)",
                    ))
                else:
                    result.checks.append(Check(
                        name="Working Directory",
                        status="ok",
                        detail="Clean",
                    ))
            else:
                result.checks.append(Check(
                    name="Working Directory",
                    status="info",
                    detail="Could not check git status",
                ))
        except Exception:
            result.checks.append(Check(
                name="Working Directory",
                status="info",
                detail="Could not check git status",
            ))

    # Agents
    agent_count = len(config.agents)
    if agent_count > 0:
        result.checks.append(Check(
            name="Agents",
            status="ok",
            detail=f"{agent_count} configured",
        ))

        # Check agent scripts
        missing_scripts = []
        for name, agent_cfg in config.agents.items():
            cmd_parts = agent_cfg.command.split()
            # Skip env var assignments (VAR=value or VAR={template}) to find actual command
            script = None
            for part in cmd_parts:
                if "=" not in part or part.startswith("{"):
                    script = part
                    break
            if script and not shutil.which(script) and not Path(script).exists():
                missing_scripts.append(f"{name}: {script}")

        if missing_scripts:
            result.checks.append(Check(
                name="Agent Scripts",
                status="error",
                detail=f"Missing: {', '.join(missing_scripts[:3])}" + ("..." if len(missing_scripts) > 3 else ""),
            ))
        else:
            result.checks.append(Check(
                name="Agent Scripts",
                status="ok",
                detail="All found",
            ))
    else:
        result.checks.append(Check(
            name="Agents",
            status="warning",
            detail="None configured",
        ))

    # === Code Review ===
    if config.review_enabled:
        if config.code_review_agent:
            if config.code_review_agent in config.agents:
                # Check for per-agent reviewers
                per_agent = [
                    (name, a.reviewer)
                    for name, a in config.agents.items()
                    if a.reviewer
                ]
                if per_agent:
                    invalid = [f"{n}→{r}" for n, r in per_agent if r not in config.agents]
                    if invalid:
                        result.checks.append(Check(
                            name="Code Review",
                            status="error",
                            detail=f"Invalid per-agent reviewers: {', '.join(invalid)}",
                        ))
                    else:
                        result.checks.append(Check(
                            name="Code Review",
                            status="ok",
                            detail=f"Enabled, default: {config.code_review_agent}, {len(per_agent)} per-agent",
                        ))
                else:
                    result.checks.append(Check(
                        name="Code Review",
                        status="ok",
                        detail=f"Enabled, default: {config.code_review_agent}",
                    ))
            else:
                result.checks.append(Check(
                    name="Code Review",
                    status="error",
                    detail=f"Default reviewer '{config.code_review_agent}' not in agents",
                ))
        else:
            result.checks.append(Check(
                name="Code Review",
                status="error",
                detail="Enabled but no default reviewer set",
            ))
    else:
        result.checks.append(Check(
            name="Code Review",
            status="info",
            detail="Disabled",
        ))

    # === E2E Test Runner ===
    if config.e2e.enabled:
        repo_root = Path.cwd()
        e2e_checks = []

        # Check pytest_args point to valid test directory
        if config.e2e.pytest_args:
            test_path = config.e2e.pytest_args[0]  # First arg is typically the path
            test_dir = repo_root / test_path
            if test_dir.exists():
                e2e_checks.append(f"tests: {test_path}")
            else:
                result.checks.append(Check(
                    name="E2E Runner",
                    status="warning",
                    detail=f"Test path '{test_path}' not found",
                ))

        # Check quarantine file
        quarantine_path = repo_root / config.e2e.quarantine_file
        if quarantine_path.exists():
            try:
                lines = [l.strip() for l in quarantine_path.read_text().splitlines()
                        if l.strip() and not l.strip().startswith("#")]
                e2e_checks.append(f"quarantine: {len(lines)} tests")
            except Exception:
                e2e_checks.append("quarantine: unreadable")
        else:
            e2e_checks.append("quarantine: none")

        # Check DB directory is writable
        db_dir = repo_root / ".issue-orchestrator"
        if db_dir.exists() and os.access(db_dir, os.W_OK):
            e2e_checks.append("db: writable")
        elif not db_dir.exists():
            e2e_checks.append("db: will create")
        else:
            result.checks.append(Check(
                name="E2E Runner",
                status="error",
                detail=".issue-orchestrator not writable",
            ))

        # Add summary if no errors
        if not any(c.name == "E2E Runner" for c in result.checks):
            auto = f"auto={config.e2e.auto_run_interval_minutes}m" if config.e2e.auto_run_interval_minutes > 0 else "manual"
            retry = "retry=on" if config.e2e.allow_retry_once else "retry=off"
            result.checks.append(Check(
                name="E2E Runner",
                status="ok",
                detail=f"Enabled ({auto}, {retry}, {', '.join(e2e_checks)})",
            ))
    else:
        result.checks.append(Check(
            name="E2E Runner",
            status="info",
            detail="Disabled",
        ))

    # === Guardrails (via test worktree) ===
    # Only run if we have a valid config with a repo AND a runner
    if config and config.repo and runner:
        repo_root = Path.cwd()
        # Get worktree_base from config (now top-level)
        worktree_base = str(config.worktree_base) if config.worktree_base else "../"

        guardrail_checks = _check_guardrails_in_worktree(repo_root, runner, worktree_base)
        result.checks.extend(guardrail_checks)
    elif config and config.repo and not runner:
        result.checks.append(Check(
            name="Guardrails",
            status="info",
            detail="Skipped (no CommandRunner provided)",
        ))

    return result
