"""Data models for issue-orchestrator."""

import os
import shlex
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Optional, TYPE_CHECKING

from .issue_key import IssueKey, GitHubIssueKey, parse_external_id
from .session_key import SessionKey, TaskKind  # pyright: ignore[reportUnusedImport] (re-exported)

if TYPE_CHECKING:
    from ..ports.issue import Issue as IssueProtocol

# Marker used in PR bodies to identify orchestrator-generated PRs
ORCHESTRATOR_PR_MARKER = "Generated by issue-orchestrator"


# ---------------------------------------------------------------------------
# Pure label helpers (no config / service dependency) — prefix-aware
# ---------------------------------------------------------------------------

def _base_of(label: str) -> str:
    """Strip an optional single colon-delimited prefix, returning the base name."""
    # "bot:in-progress" → "in-progress", "in-progress" → "in-progress"
    # "blocked:claim-lost" has *semantic* colons so we only strip if the
    # first segment looks like a prefix (no dash).
    first, sep, rest = label.partition(":")
    if sep and "-" not in first and rest:
        return rest
    return label


def _is_blocking_label(label: str) -> bool:
    """Pure string check for blocking labels — handles both prefixed and unprefixed."""
    base = _base_of(label)
    if base == "blocked" or base.startswith("blocked-") or base.startswith("blocked:"):
        return True
    return base in ("needs-human", "failed")

# Path for completion records relative to worktree root
# Each session writes to a distinct file based on agent name to avoid
# race conditions when multiple sessions reuse the same worktree
COMPLETION_RECORD_PATH = ".issue-orchestrator/completion.json"  # Legacy fallback
COMPLETION_DIR = ".issue-orchestrator"


def get_completion_path(
    agent_name: str | None = None,
    session_name: str | None = None,
    run_dir: str | None = None,
) -> str:
    """Get the completion file path for an agent.

    Args:
        agent_name: The agent label (e.g., "agent:e2e-test"). If None, uses legacy path.
        session_name: Session name for per-session output directories.

    Returns:
        Path like ".issue-orchestrator/completion-agent_e2e-test.json"
    """
    if run_dir:
        completion_dir = f"{COMPLETION_DIR}/sessions/{run_dir}"
        if not agent_name:
            return f"{completion_dir}/completion.json"
        safe_name = sanitize_agent_label(agent_name)
        return f"{completion_dir}/completion-{safe_name}.json"
    if session_name:
        completion_dir = f"{COMPLETION_DIR}/sessions/{session_name}"
        if not agent_name:
            return f"{completion_dir}/completion.json"
        # Sanitize agent name for filename (replace : and other special chars)
        safe_name = sanitize_agent_label(agent_name)
        return f"{completion_dir}/completion-{safe_name}.json"
    if not agent_name:
        return COMPLETION_RECORD_PATH
    # Sanitize agent name for filename (replace : and other special chars)
    safe_name = sanitize_agent_label(agent_name)
    return f"{COMPLETION_DIR}/completion-{safe_name}.json"


def sanitize_agent_label(agent_name: str) -> str:
    return agent_name.replace(":", "_").replace("/", "_").replace(" ", "_")


class CompletionOutcome(Enum):
    """Outcome of agent work - what happened, not what to do."""
    COMPLETED = "completed"  # Work done, ready for PR
    BLOCKED = "blocked"  # Cannot proceed, external blocker
    NEEDS_HUMAN = "needs_human"  # Need clarification from human
    REVIEW_APPROVED = "review_approved"  # Reviewer: code looks good
    REVIEW_CHANGES_REQUESTED = "review_changes_requested"  # Reviewer: needs changes


class RequestedAction(Enum):
    """Actions the agent requests the orchestrator to take."""
    CREATE_PR = "create_pr"
    ADD_BLOCKED_LABEL = "add_blocked_label"
    ADD_NEEDS_HUMAN_LABEL = "add_needs_human_label"
    ADD_CODE_REVIEWED_LABEL = "add_code_reviewed_label"
    ADD_NEEDS_REWORK_LABEL = "add_needs_rework_label"
    REMOVE_CODE_REVIEW_LABEL = "remove_code_review_label"
    REMOVE_NEEDS_REWORK_LABEL = "remove_needs_rework_label"
    POST_COMMENT = "post_comment"
    PUSH_BRANCH = "push_branch"


# ===========================================================================
# Identity and Location Abstractions
# ===========================================================================


@dataclass(frozen=True)
class SessionIdentity:
    """Identifies a session within the orchestrator.

    Immutable snapshot of session identity used across:
    - ObservedCompletion (observed facts)
    - PublishJob (background work)
    - Event payloads
    """
    issue_number: int
    issue_title: str
    session_key: str  # e.g., "code:123" or "review:456"
    terminal_id: str


@dataclass(frozen=True)
class WorktreeLocation:
    """Location info for a worktree.

    Immutable snapshot of where work is happening. Distinct from WorktreeInfo
    (in ports/) which captures creation-time metadata like reuse status.
    """
    path: str  # String for immutability (not Path)
    branch_name: str
    completion_path: str  # Relative path to completion.json


@dataclass
class CompletionRecord:
    """Structured completion record written by agent-done.

    This is the ONLY output from agent-done - a JSON file that the orchestrator
    reads, validates (as untrusted input), and acts upon via adapters.

    The agent does NOT:
    - Push code
    - Create PRs
    - Post comments
    - Mutate labels

    The orchestrator verifies worktree state and executes all side effects.
    """
    # Core identification
    session_id: str  # Orchestrator's session identifier (e.g., "session-42")
    timestamp: str  # ISO format timestamp when agent-done was called

    # Outcome - what happened (not what to do)
    outcome: CompletionOutcome

    # Human-readable summary for logging/debugging
    summary: str

    # Requested actions - what the agent wants the orchestrator to do
    # Orchestrator validates and may reject/modify based on policy
    requested_actions: list[RequestedAction] = field(default_factory=list)

    # Status-specific data (all optional, validated based on outcome)
    # For COMPLETED
    implementation: Optional[str] = None  # What was implemented
    problems: Optional[str] = None  # Problems encountered

    # For BLOCKED
    blocked_reason: Optional[str] = None
    blocked_by: Optional[list[int]] = None  # Issue numbers
    attempted: Optional[str] = None
    when_unblocked: Optional[str] = None  # Hint for future agent

    # For NEEDS_HUMAN
    question: Optional[str] = None
    context: Optional[str] = None
    options: Optional[list[str]] = None
    default_action: Optional[str] = None

    # For REVIEW_* outcomes
    review_summary: Optional[str] = None  # For approved
    review_issues: Optional[str] = None  # For changes_requested
    risk_level: Optional[str] = None  # "low", "medium", "high"
    checks_passed: Optional[list[str]] = None
    checks_needed: Optional[list[str]] = None

    # Comment body to post (if POST_COMMENT in requested_actions)
    comment_body: Optional[str] = None

    # Extra labels to add to the PR (if CREATE_PR in requested_actions)
    pr_labels: Optional[list[str]] = None

    # Validation reference (if agent_gate was run)
    validation_record_path: Optional[str] = None  # Path to validation record JSON

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "session_id": self.session_id,
            "timestamp": self.timestamp,
            "outcome": self.outcome.value,
            "summary": self.summary,
            "requested_actions": [a.value for a in self.requested_actions],
            "implementation": self.implementation,
            "problems": self.problems,
            "blocked_reason": self.blocked_reason,
            "blocked_by": self.blocked_by,
            "attempted": self.attempted,
            "when_unblocked": self.when_unblocked,
            "question": self.question,
            "context": self.context,
            "options": self.options,
            "default_action": self.default_action,
            "review_summary": self.review_summary,
            "review_issues": self.review_issues,
            "risk_level": self.risk_level,
            "checks_passed": self.checks_passed,
            "checks_needed": self.checks_needed,
            "comment_body": self.comment_body,
            "pr_labels": self.pr_labels,
            "validation_record_path": self.validation_record_path,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CompletionRecord":
        """Create from dictionary (JSON deserialization).

        Validates strictly - missing required fields or invalid values raise ValueError.
        This is UNTRUSTED input from the agent.
        """
        # Required fields
        required = ["session_id", "timestamp", "outcome", "summary"]
        for field_name in required:
            if field_name not in data:
                raise ValueError(f"Missing required field: {field_name}")

        try:
            outcome = CompletionOutcome(data["outcome"])
        except ValueError:
            raise ValueError(f"Invalid outcome: {data['outcome']}")

        requested_actions = []
        for action in data.get("requested_actions", []):
            try:
                requested_actions.append(RequestedAction(action))
            except ValueError:
                raise ValueError(f"Invalid requested action: {action}")

        return cls(
            session_id=data["session_id"],
            timestamp=data["timestamp"],
            outcome=outcome,
            summary=data["summary"],
            requested_actions=requested_actions,
            implementation=data.get("implementation"),
            problems=data.get("problems"),
            blocked_reason=data.get("blocked_reason"),
            blocked_by=data.get("blocked_by"),
            attempted=data.get("attempted"),
            when_unblocked=data.get("when_unblocked"),
            question=data.get("question"),
            context=data.get("context"),
            options=data.get("options"),
            default_action=data.get("default_action"),
            review_summary=data.get("review_summary"),
            review_issues=data.get("review_issues"),
            risk_level=data.get("risk_level"),
            checks_passed=data.get("checks_passed"),
            checks_needed=data.get("checks_needed"),
            comment_body=data.get("comment_body"),
            pr_labels=data.get("pr_labels"),
            validation_record_path=data.get("validation_record_path"),
        )


class SessionStatus(Enum):
    """Status of a Claude session."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    BLOCKED = "blocked"
    NEEDS_HUMAN = "needs_human"
    FAILED = "failed"
    TIMED_OUT = "timed_out"
    VALIDATION_FAILED = "validation_failed"  # Agent completed but validation gate failed
    NEEDS_VALIDATION_RETRY = "needs_validation_retry"  # Validation failed but retries remaining


class IssueStatus(Enum):
    """Status of an issue in the queue."""
    AVAILABLE = "available"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    NEEDS_HUMAN = "needs_human"
    COMPLETED = "completed"


@dataclass
class Issue:
    """A GitHub issue.

    Note: This class is being deprecated in favor of the Issue Protocol
    and GitHubIssue implementation. New code should use ports.issue.Issue
    and adapters.github.GitHubIssue.
    """
    number: int
    title: str
    labels: list[str]
    state: str = "open"  # "open" or "closed"
    repo: str = ""  # Repository in owner/repo format
    milestone: Optional[str] = None
    body: Optional[str] = None
    milestone_number: Optional[int] = None
    milestone_due_on: Optional[str] = None  # ISO date string

    @property
    def key(self) -> IssueKey:
        """Stable identity for this issue.

        Uses external ID from title prefix (e.g., [M1-011]) if present,
        otherwise falls back to the issue number as a string.
        """
        parsed = parse_external_id(self.title)
        external_id = parsed.external_id or str(self.number)
        return GitHubIssueKey(repo=self.repo, external_id=external_id)

    @property
    def agent_type(self) -> Optional[str]:
        """Extract agent type from labels (e.g., 'agent:web')."""
        for label in self.labels:
            if label.startswith("agent:"):
                return label
        return None

    @property
    def priority(self) -> int:
        """Extract priority (lower = higher priority)."""
        if "priority:high" in self.labels:
            return 1
        elif "priority:medium" in self.labels:
            return 2
        elif "priority:low" in self.labels:
            return 3
        return 4

    @property
    def is_blocked(self) -> bool:
        """Check if issue has any blocking label.

        Blocking labels: blocked, blocked-*, needs-human, failed (legacy).

        Blocked is a MODIFIER label that coexists with in-progress.
        An issue can be both in-progress AND blocked - this means:
        - We maintain ownership/claim on the issue
        - Work is paused waiting for intervention
        - When blocking label is removed, work resumes immediately
        """
        return any(_is_blocking_label(l) for l in self.labels)

    @property
    def is_in_progress(self) -> bool:
        """Check if issue has the 'in-progress' label."""
        return any(_base_of(l) == "in-progress" for l in self.labels)

    @property
    def needs_human(self) -> bool:
        """Check if issue specifically needs human intervention.

        Subset of blocked - checks for: needs-human, blocked-needs-human.
        """
        return any(_base_of(l) in ("blocked-needs-human", "needs-human") for l in self.labels)


@dataclass
class AgentConfig:
    """Configuration for an agent type."""
    prompt_path: Path
    # Original relative path from config - used in commands so agents read from worktree
    prompt_relative: str = ""
    # Provider name (e.g., "claude-code", "codex") - validated against agent_runner registry
    # If not set, uses default_agent.provider. If that's also not set, config validation fails.
    provider: Optional[str] = None
    model: str = "sonnet"
    timeout_minutes: int = 45
    # Provider-specific arguments (e.g., permission_mode for claude-code, approval_mode for codex)
    provider_args: dict[str, Any] = field(default_factory=dict)
    # Permission mode for Claude CLI: default, acceptEdits, bypassPermissions, plan, dontAsk
    # Deprecated: use provider_args instead. Kept for backwards compatibility.
    permission_mode: str = "default"
    # Skip code review for this agent (e.g., domain-expert agents that don't produce code)
    skip_review: bool = False
    # Per-agent reviewer override (uses review.default if not set)
    reviewer: Optional[str] = None
    # Command template - escape hatch to override provider-generated command
    # If set, this is used instead of provider.build_command()
    # For non-interactive mode, add -p flag (Claude), use 'exec' (Codex), or -p (Gemini)
    # Note: {system_prompt} includes agent-done instructions + "Read {prompt} for task instructions"
    command: str = "claude {claude_args} --permission-mode {permission_mode} --model {model} --append-system-prompt '{system_prompt}' '{initial_prompt}'"
    # Optional override for hook verification AI agent (e.g., "claude-code")
    meta_agent: Optional[str] = None
    initial_prompt: str = "Work on issue #{issue_number}: {issue_title}. Follow the instructions in {prompt}. When done, exit with /exit."
    # AI system type for log retrieval (e.g., "claude-code", "codex", "gemini", "aider")
    # If not set, auto-detected from command. Must match an entry in ai-systems.yaml.
    ai_system: Optional[str] = None
    # Path to retry prompt template (relative to repo root). Used when validation fails.
    # If not set, uses validation.retry_prompt_template or built-in default.
    # Template variables: {original_task}, {validation_cmd}, {error_file}, {error_summary},
    #                     {retry_count}, {max_retries}
    retry_prompt_template: Optional[str] = None

    def get_command(
        self,
        issue_number: int,
        issue_title: str,
        worktree: Path,
        pr_number: Optional[int] = None,
        existing_work: Optional[str] = None,
    ) -> str:
        """Render the command template with actual values, including initial prompt.

        If a provider is configured, uses the provider's build_command() method.
        Otherwise, falls back to the legacy command template.

        Args:
            issue_number: The GitHub issue number
            issue_title: The issue title
            worktree: Path to the worktree
            pr_number: Optional PR number (for review agents). If a prompt template
                       uses {pr_number} but this is not provided, a KeyError is raised.
            existing_work: Optional context about existing commits in the worktree.
                          If provided, prepended to prompt so agent knows to complete vs restart.
        """
        # Build format kwargs - pr_number only included if provided (fail-fast if used but missing)
        # Use relative prompt path so agents read from worktree (not main repo)
        prompt_for_command = self.prompt_relative if self.prompt_relative else str(self.prompt_path)
        format_kwargs = {
            "issue_number": issue_number,
            "issue_title": issue_title,
            "prompt": prompt_for_command,
            "worktree": worktree,
            "model": self.model,
            "permission_mode": self.permission_mode,
            "claude_args": os.environ.get("ORCHESTRATOR_CLAUDE_ARGS", "").strip(),
        }
        if pr_number is not None:
            format_kwargs["pr_number"] = pr_number

        # First render the initial prompt
        rendered_prompt = self.initial_prompt.format(**format_kwargs)

        # Prepend existing work context if provided
        if existing_work:
            rendered_prompt = f"IMPORTANT: {existing_work}\n\n{rendered_prompt}"

        # If provider is set, use provider-based command building
        if self.provider:
            return self._build_provider_command(rendered_prompt, prompt_for_command)

        # Legacy template-based command building
        from issue_orchestrator.resources import get_agent_done_instructions

        # Escape single quotes in the prompt for shell safety
        escaped_prompt = rendered_prompt.replace("'", "'\\''")

        # Build the full system prompt with agent-done instructions
        agent_done_docs = get_agent_done_instructions()
        system_prompt = (
            f"{agent_done_docs}\n\n"
            f"---\n\n"
            f"Read {prompt_for_command} for your task-specific instructions."
        )
        # Escape single quotes for shell embedding
        escaped_system_prompt = system_prompt.replace("'", "'\\''")

        # Then render the full command with the prompt included
        format_kwargs["initial_prompt"] = escaped_prompt
        format_kwargs["system_prompt"] = escaped_system_prompt

        prompt_mode = os.environ.get("ORCHESTRATOR_CLAUDE_PROMPT_MODE", "arg").strip().lower()
        if prompt_mode == "stdin":
            template = (
                "printf '%s' '{initial_prompt}' | "
                "claude {claude_args} --input-format text "
                "--permission-mode {permission_mode} --model {model} "
                "--append-system-prompt '{system_prompt}'"
            )
            return template.format(**format_kwargs)

        return self.command.format(**format_kwargs)

    def _build_provider_command(self, prompt: str, prompt_file: str) -> str:
        """Build command using the configured provider.

        Args:
            prompt: The fully rendered prompt to send to the agent
            prompt_file: Path to the prompt/instructions file (for system prompt)

        Returns:
            Shell-safe command string
        """
        from issue_orchestrator.agent_runner import get_provider
        from issue_orchestrator.resources import get_agent_done_instructions

        # self.provider is guaranteed non-None here (caller checks)
        assert self.provider is not None
        provider = get_provider(self.provider)

        # Build provider-specific kwargs from provider_args
        kwargs = dict(self.provider_args)

        # STRICT ENFORCEMENT: Agent-done is ALWAYS injected for ALL providers.
        # - For Claude: inject via system_prompt (--append-system-prompt)
        # - For other providers: prepend to the prompt itself
        agent_done_docs = get_agent_done_instructions()
        agent_done_with_prompt_ref = (
            f"{agent_done_docs}\n\n"
            f"---\n\n"
            f"Read {prompt_file} for your task-specific instructions."
        )

        if self.provider == "claude-code":
            # Claude Code uses --append-system-prompt for agent-done
            system_prompt = agent_done_with_prompt_ref
            # Append any user-provided system_prompt (agent-done always comes first)
            user_system_prompt = kwargs.pop("system_prompt", None)
            if user_system_prompt:
                system_prompt = f"{system_prompt}\n\n---\n\n{user_system_prompt}"
            kwargs["system_prompt"] = system_prompt
            # Use permission_mode from provider_args or fall back to legacy field
            kwargs.setdefault("permission_mode", self.permission_mode)
        else:
            # Other providers (Codex, etc.): prepend agent-done to the prompt itself
            prompt = f"{agent_done_with_prompt_ref}\n\n---\n\n{prompt}"

        # Build the command (returns list[str])
        cmd_list = provider.build_command(prompt=prompt, model=self.model, **kwargs)

        # Convert to shell-safe string
        return shlex.join(cmd_list)


@dataclass
class Session:
    """A running Claude session working on an issue.

    The `key` field is the domain identity (SessionKey) used for:
    - Duplicate prevention at launch
    - Lookup in active sessions
    - Removal when done
    - State machine lookup

    The `terminal_id` is an opaque handle that only the terminal adapter interprets.
    """
    key: SessionKey  # Domain identity - (IssueKey, TaskKind)
    issue: "IssueProtocol"
    agent_config: AgentConfig
    terminal_id: str  # Opaque handle - only terminal adapter interprets this
    worktree_path: Path
    branch_name: str
    completion_path: str = COMPLETION_RECORD_PATH  # Agent-specific path to completion.json
    agent_label: Optional[str] = None  # Agent type label (e.g., "agent:backend") for per-agent reviewer
    pr_number: int | None = None  # PR number for review/rework sessions
    rework_cycle: int | None = None  # Which rework iteration (1, 2, ...) — None for initial coding
    started_at: datetime = field(default_factory=datetime.now)
    status: SessionStatus = SessionStatus.RUNNING
    exit_sent: bool = False  # Track if we've already sent /exit
    validation_retry_count: int = 0  # Number of validation retries attempted
    original_prompt: str | None = None  # Original prompt for retry context
    last_validation_error: str | None = None  # Last validation error for retry prompt
    last_validation_error_file: str | None = None  # Path to validation error file
    last_output_monotonic: float | None = None
    last_output_at: float | None = None
    last_log_mtime: float | None = None
    last_log_size: int | None = None
    last_output_tail: str | None = None
    last_no_output_monotonic: float | None = None
    # Claim/lease fields for multi-orchestrator coordination
    lease_id: str | None = None  # Unique identifier for the claim
    lease_acquired_at: datetime | None = None  # When the claim was acquired
    lease_expires_at: datetime | None = None  # When the claim expires if not renewed
    last_claim_verified_at: datetime | None = None  # Last time we verified we're still the winner

    @property
    def runtime_minutes(self) -> int:
        """How long this session has been running."""
        delta = datetime.now() - self.started_at
        return int(delta.total_seconds() / 60)

    @property
    def is_timed_out(self) -> bool:
        """Check if session exceeded timeout."""
        return self.runtime_minutes > self.agent_config.timeout_minutes


@dataclass
class SessionHistoryEntry:
    """Record of a completed session."""
    issue_number: int
    title: str
    agent_type: str
    status: str  # "completed", "failed", "blocked", "needs_human", "timed_out"
    runtime_minutes: int
    pr_url: Optional[str] = None  # Set if PR was created
    status_reason: Optional[str] = None  # Human-readable explanation of status
    worktree_path: Optional[Path] = None
    completed_at: Optional[datetime] = None  # When the session completed (for sequence visibility)


@dataclass
class PendingCleanup:
    """A session awaiting cleanup after review completes.

    Tracks sessions that completed successfully but need to wait for
    code review or triage review before closing tabs/removing worktrees.
    """
    issue: "IssueProtocol"  # The issue this cleanup is for
    pr_number: int
    pr_url: str
    branch_name: str
    terminal_id: str
    worktree_path: Path

    @property
    def issue_number(self) -> int:
        """Backwards-compatible access to issue number."""
        return self.issue.number


@dataclass
class PendingReview:
    """A PR queued for code review.

    Store-agnostic: uses IssueKey for identity, not GitHub-specific fields.
    """
    issue_key: "IssueKey"     # Store-agnostic identity
    pr_number: int
    pr_url: str
    branch_name: str
    _issue_number: int  # The actual GitHub issue number (stable_id may not be numeric)
    agent_label: Optional[str] = None  # Agent that created the PR (for per-agent reviewer)

    @property
    def issue_number(self) -> int:
        """Access to issue number (stored explicitly, not derived from stable_id)."""
        return self._issue_number


@dataclass(frozen=True)
class DiscoveredReview:
    """A PR discovered from session completion, pending Planner decision.

    This is a "fact" - the Planner will decide whether to queue it.
    Immutable to be safely included in OrchestratorSnapshot.
    """
    issue_number: int
    pr_number: int
    pr_url: str
    branch_name: str
    agent_label: Optional[str] = None  # Agent that created the PR (for per-agent reviewer)


@dataclass(frozen=True)
class TriageFacts:
    """Facts about triage review trigger conditions.

    Immutable snapshot of conditions for Planner to decide on triage.
    """
    pr_count: int = 0  # PRs with watch label
    threshold: int = 0  # Configured threshold
    existing_triage_issue: Optional[int] = None  # Existing open triage issue number
    watch_label: str = ""  # Label being watched
    prs: tuple[Any, ...] = field(default_factory=tuple)  # PR info for body generation
    # Labels from source issues/PRs (for label inheritance)
    source_labels: frozenset[str] = field(default_factory=frozenset)
    # Milestones from source issues: tuple of (number, title) for milestone inheritance
    source_milestones: tuple[tuple[int, str], ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class DiscoveredRework:
    """A PR discovered needing rework, pending Planner decision.

    This is a "fact" - the Planner will decide whether to queue it.
    Immutable to be safely included in OrchestratorSnapshot.
    """
    issue_number: int
    pr_number: int
    branch_name: str
    agent_type: str
    rework_cycle: int = 1


@dataclass(frozen=True)
class DiscoveredEscalation:
    """An escalation discovered during rework scan, pending Planner decision.

    This is a "fact" - the Planner will decide whether to escalate.
    Immutable to be safely included in OrchestratorSnapshot.
    """
    issue_number: int
    pr_number: int
    rework_cycle: int


@dataclass(frozen=True)
class DiscoveredFailure:
    """A session failure discovered, pending Planner decision on triage.

    This is a "fact" - the Planner will decide whether to queue a triage review.
    Immutable to be safely included in OrchestratorSnapshot.
    """
    issue_number: int
    issue_title: str
    failure_reason: str  # "failed" or "timed_out"


@dataclass(frozen=True)
class ImmediateCleanup:
    """A session that needs immediate cleanup (no deferred review).

    Created when a session completes/times out and cleanup should happen
    immediately (not deferred until triage review).
    """
    issue_number: int
    terminal_id: str  # e.g., "issue-123", "review-456"
    worktree_path: str
    reason: str  # e.g., "completed", "timed_out"


@dataclass(frozen=True)
class CleanupFacts:
    """Facts about pending cleanups and their review status.

    Immutable snapshot of conditions for Planner to decide on cleanups.
    """
    pending_cleanups: tuple[Any, ...]  # tuple of PendingCleanup-like info
    reviewed_pr_numbers: frozenset[int]  # PRs that have the cleanup label
    close_tabs: bool = False  # Config: whether to close terminal tabs
    remove_worktrees: bool = False  # Config: whether to remove worktrees
    # Immediate cleanups (no deferred review) - sessions that completed/timed out
    immediate_cleanups: tuple["ImmediateCleanup", ...] = field(default_factory=tuple)


@dataclass
class PendingRework:
    """A work item that needs rework after review requested changes.

    Store-agnostic: uses IssueKey for identity, not GitHub-specific fields.
    Adapters resolve the key to backing-store details (PR number, branch, URL).
    """
    issue_key: "IssueKey"     # Store-agnostic identity
    agent_type: str           # Cached to avoid lookup at launch time
    rework_cycle: int = 1     # Which rework iteration this is (1, 2, etc.)
    issue_number: int | None = None  # Backing store handle for GitHub rework flows

    def resolve_issue_number(self) -> int | None:
        """Resolve issue number for GitHub workflows, if available."""
        if self.issue_number is not None:
            return self.issue_number
        try:
            return int(self.issue_key.stable_id())
        except (TypeError, ValueError):
            return None


@dataclass
class PendingTriageReview:
    """A triage batch review issue queued for processing.

    Triage reviews are treated as reviews (not work items) so they get
    processed with priority, alongside pending_reviews and pending_reworks.
    """
    issue_number: int  # The triage review GitHub issue number
    title: str  # Issue title (for display)


@dataclass
class PendingValidationRetry:
    """A session that needs to be re-launched with validation retry prompt.

    When validation fails but retries are remaining, the orchestrator queues
    a retry. The next tick will re-launch the session with error context.
    """
    issue_number: int
    issue_title: str
    agent_label: str
    worktree_path: str
    branch_name: str
    original_prompt: str | None
    validation_error: str
    validation_error_file: str | None
    retry_count: int  # Current retry count (will be incremented on re-launch)
    validation_cmd: str | None = None  # For building retry prompt


# Backwards compatibility alias
PendingCTOReview = PendingTriageReview


# =============================================================================
# Publish Job Models (Async Completion Processing)
# =============================================================================


class PublishJobStatus(Enum):
    """Status of a publish job in the background queue."""
    QUEUED = "queued"      # Job created, waiting for worker
    RUNNING = "running"    # Worker is executing
    SUCCEEDED = "succeeded"  # Job completed successfully
    FAILED = "failed"      # Job failed (may be retryable)


@dataclass(frozen=True)
class ObservedCompletion:
    """Facts observed from a completed session.

    This is produced by the observation phase (fast) and consumed by:
    1. The planner (to project labels immediately)
    2. The job queue (to enqueue background publish work)

    Immutable to ensure it's a pure fact, not mutated during processing.

    Uses composition for cleaner structure:
    - identity: Who/what session this is
    - worktree: Where the work happened
    - record: What the agent reported (the completion record)
    """
    # Composed abstractions
    identity: SessionIdentity
    worktree: WorktreeLocation
    record: CompletionRecord

    # Session-specific fields (not from the completion record)
    pr_number: int | None = None  # For review sessions
    agent_label: str | None = None  # For per-agent reviewer

    # Validation state (for sessions with validation configured)
    validation_retry_count: int = 0
    original_prompt: str | None = None

    # Convenience accessors for commonly-used fields
    @property
    def issue_number(self) -> int:
        return self.identity.issue_number

    @property
    def issue_title(self) -> str:
        return self.identity.issue_title

    @property
    def session_key(self) -> str:
        return self.identity.session_key

    @property
    def terminal_id(self) -> str:
        return self.identity.terminal_id

    @property
    def worktree_path(self) -> str:
        return self.worktree.path

    @property
    def branch_name(self) -> str:
        return self.worktree.branch_name

    @property
    def completion_path(self) -> str:
        return self.worktree.completion_path

    @property
    def outcome(self) -> CompletionOutcome:
        return self.record.outcome

    @property
    def requested_actions(self) -> list[RequestedAction]:
        return self.record.requested_actions

    @property
    def summary(self) -> str:
        return self.record.summary

    @property
    def needs_publish(self) -> bool:
        """Check if this completion requires publishing (git push + PR)."""
        return RequestedAction.PUSH_BRANCH in self.record.requested_actions

    @property
    def is_code_session(self) -> bool:
        """Check if this is a code (issue) session vs review session."""
        return self.pr_number is None

    # Convenience accessors for CompletionRecord fields
    @property
    def implementation(self) -> Optional[str]:
        return self.record.implementation

    @property
    def problems(self) -> Optional[str]:
        return self.record.problems

    @property
    def blocked_reason(self) -> Optional[str]:
        return self.record.blocked_reason

    @property
    def review_summary(self) -> Optional[str]:
        return self.record.review_summary

    @property
    def review_issues(self) -> Optional[str]:
        return self.record.review_issues

    @property
    def comment_body(self) -> Optional[str]:
        return self.record.comment_body

    @property
    def pr_labels(self) -> Optional[list[str]]:
        return self.record.pr_labels


@dataclass
class PublishJob:
    """A background job to publish completion work (git push, PR, validation).

    Created from an ObservedCompletion when the planner decides to queue it.
    Executed by the PublishJobExecutor in a background thread.
    """
    # Job identity (unique constraint: issue_number + session_key)
    job_id: str  # UUID
    issue_number: int
    session_key: str

    # Job state
    status: PublishJobStatus = PublishJobStatus.QUEUED
    created_at: float = 0.0  # time.monotonic() when created
    started_at: float | None = None  # time.monotonic() when worker started
    finished_at: float | None = None  # time.monotonic() when completed

    # Work data (from ObservedCompletion)
    worktree_path: str = ""
    branch_name: str = ""
    completion_path: str = ""
    issue_title: str = ""
    pr_number: int | None = None  # For review sessions
    agent_label: str | None = None

    # Completion record data (needed for PR body, labels, etc.)
    outcome: str = ""
    requested_actions: tuple[str, ...] = field(default_factory=tuple)
    implementation: str | None = None
    problems: str | None = None
    comment_body: str | None = None
    pr_labels: tuple[str, ...] | None = None

    # Validation config (passed through for post-publish validation)
    run_validation: bool = False
    validation_retry_count: int = 0
    original_prompt: str | None = None

    # Result (populated by worker)
    result_success: bool | None = None
    result_pr_url: str | None = None
    result_pr_number: int | None = None
    result_message: str | None = None
    result_errors: tuple[str, ...] | None = None
    result_diagnostic_path: str | None = None

    # Retry tracking
    attempt_count: int = 0
    last_error: str | None = None

    @classmethod
    def from_observed_completion(
        cls,
        observed: ObservedCompletion,
        job_id: str,
        run_validation: bool = False,
    ) -> "PublishJob":
        """Create a publish job from an observed completion."""
        import time
        return cls(
            job_id=job_id,
            issue_number=observed.issue_number,
            session_key=observed.session_key,
            created_at=time.monotonic(),
            worktree_path=observed.worktree_path,
            branch_name=observed.branch_name,
            completion_path=observed.completion_path,
            issue_title=observed.issue_title,
            pr_number=observed.pr_number,
            agent_label=observed.agent_label,
            # Convert enums to strings for storage
            outcome=observed.outcome.value,
            requested_actions=tuple(a.value for a in observed.requested_actions),
            implementation=observed.implementation,
            problems=observed.problems,
            comment_body=observed.comment_body,
            pr_labels=tuple(observed.pr_labels) if observed.pr_labels else None,
            run_validation=run_validation,
            validation_retry_count=observed.validation_retry_count,
            original_prompt=observed.original_prompt,
        )

    def mark_started(self) -> None:
        """Mark job as started by worker."""
        import time
        self.status = PublishJobStatus.RUNNING
        self.started_at = time.monotonic()
        self.attempt_count += 1

    def mark_succeeded(
        self,
        pr_url: str | None = None,
        pr_number: int | None = None,
        message: str = "",
    ) -> None:
        """Mark job as successfully completed."""
        import time
        self.status = PublishJobStatus.SUCCEEDED
        self.finished_at = time.monotonic()
        self.result_success = True
        self.result_pr_url = pr_url
        self.result_pr_number = pr_number
        self.result_message = message

    def mark_failed(
        self,
        error: str,
        errors: list[str] | None = None,
        diagnostic_path: str | None = None,
    ) -> None:
        """Mark job as failed."""
        import time
        self.status = PublishJobStatus.FAILED
        self.finished_at = time.monotonic()
        self.result_success = False
        self.result_message = error
        self.last_error = error
        if errors:
            self.result_errors = tuple(errors)
        self.result_diagnostic_path = diagnostic_path

    @property
    def duration_seconds(self) -> float | None:
        """Duration of job execution in seconds."""
        if self.started_at is None or self.finished_at is None:
            return None
        return self.finished_at - self.started_at

    @property
    def is_terminal(self) -> bool:
        """Check if job is in a terminal state."""
        return self.status in (PublishJobStatus.SUCCEEDED, PublishJobStatus.FAILED)


@dataclass(frozen=True)
class PublishJobResult:
    """Result of a completed publish job, for consumption by orchestrator.

    Immutable snapshot returned by job executor when polled.
    """
    job_id: str
    issue_number: int
    session_key: str
    success: bool
    pr_url: str | None = None
    pr_number: int | None = None
    message: str = ""
    errors: tuple[str, ...] | None = None
    diagnostic_path: str | None = None
    duration_seconds: float | None = None
    review_exchange_completed: bool = False

    # Validation results (if validation was run)
    validation_passed: bool | None = None
    validation_error: str | None = None
    validation_error_file: str | None = None
    needs_validation_retry: bool = False


@dataclass
class DependencyProblem:
    """A dependency problem for an issue (for web UI display)."""
    issue_number: int
    issue_title: str
    blocked_by: list[tuple[int, str, str]]  # [(dep_number, dep_title, state)]
    summary: str  # Human-readable summary


@dataclass
class OrchestratorState:
    """Persisted state of the orchestrator."""
    active_sessions: list[Session] = field(default_factory=list)
    completed_today: list[int] = field(default_factory=list)  # issue numbers (to migrate: set[IssueKey])
    failed_this_cycle: set[int] = field(default_factory=set)  # issues that failed since last refresh (prevent immediate retry)
    paused: bool = False
    priority_queue: list[int] = field(default_factory=list)  # manual priority overrides (to migrate: list[IssueKey])
    session_history: list[SessionHistoryEntry] = field(default_factory=list)  # This session's history
    issues_started_count: int = 0  # Total issues started this session (for max_issues_to_start)
    pending_reviews: list[PendingReview] = field(default_factory=list)  # PRs waiting for code review
    pending_reworks: list[PendingRework] = field(default_factory=list)  # PRs needing rework after review
    pending_triage_reviews: list["PendingTriageReview"] = field(default_factory=list)  # Triage batch reviews waiting
    pending_cleanups: list[PendingCleanup] = field(default_factory=list)  # Sessions awaiting cleanup after review
    pending_validation_retries: list["PendingValidationRetry"] = field(default_factory=list)  # Sessions needing validation retry
    startup_status: str = "pending"  # "pending", "running", "complete"
    startup_message: str = ""  # Current startup task description
    cached_queue_issues: list["IssueProtocol"] = field(default_factory=list)  # Cached queue for instant pagination
    queue_last_refresh_at: float = 0.0  # Unix timestamp of last queue refresh
    queue_last_network_sync_at: float = 0.0  # Unix timestamp of last network sync attempt
    queue_last_full_scan_at: float = 0.0  # Unix timestamp of last full GitHub scan
    queue_refresh_count: int = 0  # Number of queue refresh cycles completed
    queue_last_refresh_mode: str = "none"  # none|full|incremental
    queue_delta_watermark: str | None = None  # Last committed watermark for incremental delta sync
    issue_refresh_timestamps: dict[int, float] = field(default_factory=dict)  # issue_number -> unix timestamp of last confirmed refresh
    ui_visible_issue_numbers: list[int] = field(default_factory=list)  # Issue numbers currently visible in Flow UI
    ui_visible_updated_at: float = 0.0  # Unix timestamp when UI visibility hint was last updated
    dependency_problems: dict[int, "DependencyProblem"] = field(default_factory=dict)  # Issues blocked by dependencies (to migrate: dict[IssueKey, ...])
    # Discovered facts pending Planner decision
    discovered_reviews: list[DiscoveredReview] = field(default_factory=list)  # Reviews from completions/scans
    discovered_reworks: list[DiscoveredRework] = field(default_factory=list)  # Reworks from scans
    discovered_escalations: list[DiscoveredEscalation] = field(default_factory=list)  # Escalations from scans
    discovered_failures: list["DiscoveredFailure"] = field(default_factory=list)  # Failures for triage
    # Immediate cleanups - sessions that need cleanup now (not deferred until review)
    immediate_cleanups: list["ImmediateCleanup"] = field(default_factory=list)
    # Stale in-progress tracking: issue_number -> consecutive ticks with stale in-progress
    stale_issue_ticks: dict[int, int] = field(default_factory=dict)
    # Async completion processing (publish jobs)
    observed_completions: list["ObservedCompletion"] = field(default_factory=list)  # Completions detected this tick
    pending_publish_jobs: dict[str, "PublishJob"] = field(default_factory=dict)  # job_id -> job (queued)
    running_publish_jobs: dict[str, "PublishJob"] = field(default_factory=dict)  # job_id -> job (in progress)
    # Queue refresh/freshness tracking for dashboard UX and lazy refresh behavior
    queue_last_refresh_at: float = 0.0  # Epoch seconds of last queue refresh completion
    queue_refresh_in_progress: bool = False  # True while refresh is actively fetching from GitHub
    queue_refresh_requested: bool = False  # True when a manual refresh has been requested
    issue_last_refreshed_at: dict[int, float] = field(default_factory=dict)  # issue_number -> epoch seconds


@dataclass
class CommentHeadings:
    """Configurable headings for worker comments on issues.

    These headings structure the comments workers post, allowing
    correlation with triage investigation comments and other tooling.
    """
    implementation: str = "## Implementation"
    problems: str = "## Problems Encountered"
    pr_link: str = "## Pull Request"
    blocked: str = "## Blocked"
    needs_human: str = "## Needs Human Input"

    def format_completion_comment(
        self,
        implementation: str,
        problems: str | None,
        pr_url: str,
    ) -> str:
        """Format a completion comment with all sections."""
        lines = [
            self.implementation,
            implementation,
            "",
            self.problems,
            problems or "None",
            "",
            self.pr_link,
            pr_url,
        ]
        return "\n".join(lines)

    def format_blocked_comment(self, reason: str) -> str:
        """Format a blocked comment."""
        return f"{self.blocked}\n{reason}"

    def format_needs_human_comment(self, question: str) -> str:
        """Format a needs-human comment."""
        return f"{self.needs_human}\n{question}"
