"""Data models for issue-orchestrator."""

import os
import re
import shlex
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Literal, Optional, TYPE_CHECKING, TypeAlias
from unittest.mock import Mock

from .dependency_gates import DependencyGateSnapshot
from .issue_key import IssueKey, GitHubIssueKey, parse_external_id
from .session_key import SessionKey, TaskKind  # re-exported for callers
from .sandbox_scope import (
    SandboxScope,
    SandboxScopeContext,
    SandboxUnsupportedError,
    compute_session_scope,
)
from .session_run import SessionRunAssets
from .tech_lead_session import (
    ApprovedTechLeadOp,
    TechLeadCaseFileSummary,
    TechLeadLaunchScope,
    TechLeadSessionFlavor,
)

if TYPE_CHECKING:
    from ..ports.issue import Issue as IssueProtocol

# Marker used in PR bodies to identify orchestrator-generated PRs
ORCHESTRATOR_PR_MARKER = "Generated by issue-orchestrator"
RETROSPECTIVE_REVIEW_TERMINAL_PREFIX = f"{TaskKind.RETROSPECTIVE_REVIEW.value}-"


# ---------------------------------------------------------------------------
# Pure label helpers (no config / service dependency) — prefix-aware
# ---------------------------------------------------------------------------

def _base_of(label: str) -> str:
    """Strip an optional single colon-delimited prefix, returning the base name."""
    # "bot:in-progress" → "in-progress", "in-progress" → "in-progress"
    # "blocked:claim-lost" has *semantic* colons so we only strip if the
    # first segment looks like a prefix (no dash).
    first, sep, rest = label.partition(":")
    if sep and "-" not in first and rest:
        return rest
    return label


def _is_blocking_label(label: str) -> bool:
    """Pure string check for blocking labels — handles both prefixed and unprefixed."""
    base = _base_of(label)
    if (
        # _base_of("blocked:claim-lost") returns "claim-lost", so keep the
        # unprefixed semantic-colon form before checking prefix-stripped bases.
        label.startswith("blocked:")
        or base == "blocked"
        or base.startswith("blocked-")
        or base.startswith("blocked:")
    ):
        return True
    return base in ("needs-human", "failed", "publish-failed")

# Path for completion records relative to worktree root
# Each session writes to a distinct file based on agent name to avoid
# race conditions when multiple sessions reuse the same worktree
COMPLETION_RECORD_PATH = ".issue-orchestrator/completion.json"  # Legacy fallback
COMPLETION_DIR = ".issue-orchestrator"


def get_completion_path(
    agent_name: str | None = None,
    session_name: str | None = None,
    run_dir: str | None = None,
) -> str:
    """Get the completion file path for an agent.

    Args:
        agent_name: The agent label (e.g., "agent:e2e-test"). If None, uses legacy path.
        session_name: Session name for per-session output directories.

    Returns:
        Path like ".issue-orchestrator/completion-agent_e2e-test.json"
    """
    if run_dir:
        completion_dir = f"{COMPLETION_DIR}/sessions/{run_dir}"
        if not agent_name:
            return f"{completion_dir}/completion.json"
        safe_name = sanitize_agent_label(agent_name)
        return f"{completion_dir}/completion-{safe_name}.json"
    if session_name:
        completion_dir = f"{COMPLETION_DIR}/sessions/{session_name}"
        if not agent_name:
            return f"{completion_dir}/completion.json"
        # Sanitize agent name for filename (replace : and other special chars)
        safe_name = sanitize_agent_label(agent_name)
        return f"{completion_dir}/completion-{safe_name}.json"
    if not agent_name:
        return COMPLETION_RECORD_PATH
    # Sanitize agent name for filename (replace : and other special chars)
    safe_name = sanitize_agent_label(agent_name)
    return f"{COMPLETION_DIR}/completion-{safe_name}.json"


def sanitize_agent_label(agent_name: str) -> str:
    return agent_name.replace(":", "_").replace("/", "_").replace(" ", "_")


class CompletionOutcome(Enum):
    """Outcome of agent work - what happened, not what to do."""
    COMPLETED = "completed"  # Work done, ready for PR
    BLOCKED = "blocked"  # Cannot proceed, external blocker
    NEEDS_HUMAN = "needs_human"  # Need clarification from human
    REVIEW_APPROVED = "review_approved"  # Reviewer: code looks good
    REVIEW_CHANGES_REQUESTED = "review_changes_requested"  # Reviewer: needs changes


class RequestedAction(Enum):
    """Actions the agent requests the orchestrator to take."""
    CREATE_PR = "create_pr"
    ADD_BLOCKED_LABEL = "add_blocked_label"
    ADD_NEEDS_HUMAN_LABEL = "add_needs_human_label"
    ADD_CODE_REVIEWED_LABEL = "add_code_reviewed_label"
    ADD_NEEDS_REWORK_LABEL = "add_needs_rework_label"
    REMOVE_NEEDS_REWORK_LABEL = "remove_needs_rework_label"
    REMOVE_CODE_REVIEW_LABEL = "remove_code_review_label"
    POST_COMMENT = "post_comment"
    PUSH_BRANCH = "push_branch"


# ---------------------------------------------------------------------------
# CompletionRecord untrusted-input bounds
#
# Completion records are written by agents in isolated worktrees and read by
# the orchestrator as untrusted input. Bounds here cap DoS / injection surface
# (see security issue #5987, findings F1, F2, F7). Downstream consumers are
# still responsible for any context-specific checks (e.g. path containment
# relative to the actual worktree path).
# ---------------------------------------------------------------------------

# Default cap for any agent-supplied free-form string. Matches GitHub's max
# comment length so we do not reject a legitimate comment body.
_COMPLETION_STRING_MAX_BYTES = 64 * 1024

# Tighter caps for specific fields.
_COMPLETION_RISK_LEVEL_MAX = 32
_COMPLETION_TIMESTAMP_MAX = 64
_COMPLETION_OPTION_MAX_BYTES = 1 * 1024
_COMPLETION_LIST_OF_STRINGS_MAX_ITEMS = 100
_COMPLETION_BLOCKED_BY_MAX_ITEMS = 50
# RequestedAction is a closed enum with ~10 members, so legitimate
# completions never carry more than a handful. Cap generously to reject
# clearly abusive input without hard-coding the exact enum size.
_COMPLETION_REQUESTED_ACTIONS_MAX = 50

_PR_LABEL_MAX_LENGTH = 50  # GitHub's own limit
_PR_LABEL_MAX_COUNT = 20
# GitHub allows unicode in labels; we intentionally restrict to a conservative
# ASCII allowlist because agent-supplied labels are untrusted and appear in
# GH API URLs, logs, and UI. Start with an alphanum; allow space/dash/dot/
# underscore/slash/colon thereafter.
_PR_LABEL_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 ._/:\-]{0,49}$")

# Completion records may legitimately propose several follow-up issues after
# audit-style tasks. Keep a generous parser bound for direct in-memory callers;
# any tighter side-effect throttle belongs in the issue publishing policy.
_FOLLOW_UP_ISSUES_MAX = 50
_FOLLOW_UP_TITLE_MAX_BYTES = 255
_FOLLOW_UP_REASON_MAX_BYTES = 4 * 1024
_FOLLOW_UP_EVIDENCE_MAX_BYTES = 4 * 1024
_FOLLOW_UP_SUGGESTED_LABELS_MAX = 10


def _check_optional_string(
    name: str,
    value: Any,
    *,
    max_bytes: int = _COMPLETION_STRING_MAX_BYTES,
    allow_empty: bool = True,
) -> str | None:
    """Validate an optional agent-supplied string field.

    Returns the string unchanged if valid; raises ValueError on violation.
    """
    if value is None:
        return None
    if not isinstance(value, str):
        raise ValueError(f"{name} must be a string")
    if "\x00" in value:
        raise ValueError(f"{name} must not contain null bytes")
    if not allow_empty and not value.strip():
        raise ValueError(f"{name} must be a non-empty string")
    encoded_len = len(value.encode("utf-8"))
    if encoded_len > max_bytes:
        raise ValueError(
            f"{name} exceeds maximum length "
            f"({encoded_len} bytes > {max_bytes} bytes)"
        )
    return value


def _check_required_string(name: str, value: Any, *, max_bytes: int) -> str:
    """Validate a required agent-supplied string field."""
    if not isinstance(value, str):
        raise ValueError(f"{name} must be a string")
    if "\x00" in value:
        raise ValueError(f"{name} must not contain null bytes")
    encoded_len = len(value.encode("utf-8"))
    if encoded_len > max_bytes:
        raise ValueError(
            f"{name} exceeds maximum length "
            f"({encoded_len} bytes > {max_bytes} bytes)"
        )
    return value


def _check_validation_record_path(value: Any) -> str | None:
    """Static validation for ``validation_record_path``.

    The value is produced by agent-side validation machinery (see
    ``AgentGate.run`` in ``control/validation.py``, which currently
    records ``str(self.store.get_record_path(head_sha))`` — an
    absolute path rooted at the worktree). We can't meaningfully
    enforce relative-only here without breaking the orchestrator's
    own producer, so the static checks are limited to:

    - non-empty string, no null bytes, bounded size
    - no ``..`` segments (cheap traversal guard)

    Runtime containment — "the resolved path must live inside the
    worktree's ``.issue-orchestrator`` directory" — belongs in the
    consumer (``completion_processor._attach_validation_artifacts``),
    which has both the worktree path and the ability to resolve
    symlinks and re-check containment against the real filesystem.
    """
    if value is None:
        return None
    if not isinstance(value, str):
        raise ValueError("validation_record_path must be a string")
    if not value.strip():
        raise ValueError("validation_record_path must be a non-empty string")
    if "\x00" in value:
        raise ValueError("validation_record_path must not contain null bytes")
    if len(value.encode("utf-8")) > _COMPLETION_STRING_MAX_BYTES:
        raise ValueError("validation_record_path is too long")
    normalized = PurePosixPath(value.replace("\\", "/"))
    if any(part == ".." for part in normalized.parts):
        raise ValueError(
            "validation_record_path must not contain '..' path segments"
        )
    return value


def _check_pr_labels(value: Any) -> list[str] | None:
    if value is None:
        return None
    if not isinstance(value, list):
        raise ValueError("pr_labels must be a list of strings")
    if len(value) > _PR_LABEL_MAX_COUNT:
        raise ValueError(
            f"pr_labels exceeds maximum count "
            f"({len(value)} > {_PR_LABEL_MAX_COUNT})"
        )
    checked: list[str] = []
    for idx, item in enumerate(value):
        if not isinstance(item, str):
            raise ValueError(f"pr_labels[{idx}] must be a string")
        if not _PR_LABEL_PATTERN.match(item):
            raise ValueError(
                f"pr_labels[{idx}] is not a valid label "
                f"(must match {_PR_LABEL_PATTERN.pattern})"
            )
        checked.append(item)
    return checked


def _check_list_of_strings(
    name: str,
    value: Any,
    *,
    max_items: int = _COMPLETION_LIST_OF_STRINGS_MAX_ITEMS,
    max_bytes_per_item: int = _COMPLETION_STRING_MAX_BYTES,
) -> list[str] | None:
    if value is None:
        return None
    if not isinstance(value, list):
        raise ValueError(f"{name} must be a list of strings")
    if len(value) > max_items:
        raise ValueError(
            f"{name} exceeds maximum count ({len(value)} > {max_items})"
        )
    for idx, item in enumerate(value):
        _check_required_string(
            f"{name}[{idx}]", item, max_bytes=max_bytes_per_item
        )
    return list(value)


def _check_blocked_by(value: Any) -> list[int] | None:
    if value is None:
        return None
    if not isinstance(value, list):
        raise ValueError("blocked_by must be a list of integers")
    if len(value) > _COMPLETION_BLOCKED_BY_MAX_ITEMS:
        raise ValueError(
            f"blocked_by exceeds maximum count "
            f"({len(value)} > {_COMPLETION_BLOCKED_BY_MAX_ITEMS})"
        )
    for idx, item in enumerate(value):
        # Reject bools explicitly; bool is a subclass of int in Python.
        if isinstance(item, bool) or not isinstance(item, int):
            raise ValueError(f"blocked_by[{idx}] must be an integer")
    return list(value)


def _check_follow_up_issues_count(value: Any) -> None:
    if value is None:
        return
    if not isinstance(value, list):
        raise ValueError("follow_up_issues must be a list")
    if len(value) > _FOLLOW_UP_ISSUES_MAX:
        raise ValueError(
            f"follow_up_issues exceeds maximum count "
            f"({len(value)} > {_FOLLOW_UP_ISSUES_MAX})"
        )


def _validate_follow_up_required_string(
    value: Any, field_name: str, max_bytes: int
) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(
            f"follow_up_issues entries require non-empty {field_name}"
        )
    if "\x00" in value:
        raise ValueError(
            f"follow_up_issues {field_name} must not contain null bytes"
        )
    if len(value.encode("utf-8")) > max_bytes:
        raise ValueError(
            f"follow_up_issues {field_name} exceeds maximum length "
            f"({max_bytes} bytes)"
        )
    return value


def _validate_follow_up_suggested_labels(value: Any) -> list[str] | None:
    if value is None:
        return None
    if not isinstance(value, list) or not all(
        isinstance(item, str) and item.strip() for item in value
    ):
        raise ValueError(
            "follow_up_issues suggested_labels must be a list of non-empty strings"
        )
    if len(value) > _FOLLOW_UP_SUGGESTED_LABELS_MAX:
        raise ValueError(
            "follow_up_issues suggested_labels exceeds maximum count "
            f"({_FOLLOW_UP_SUGGESTED_LABELS_MAX})"
        )
    for idx, label in enumerate(value):
        if not _PR_LABEL_PATTERN.match(label):
            raise ValueError(
                f"follow_up_issues suggested_labels[{idx}] is not a valid label"
            )
    return list(value)


def _validate_follow_up_evidence(value: Any) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip():
        raise ValueError(
            "follow_up_issues evidence must be a non-empty string when provided"
        )
    if "\x00" in value:
        raise ValueError(
            "follow_up_issues evidence must not contain null bytes"
        )
    if len(value.encode("utf-8")) > _FOLLOW_UP_EVIDENCE_MAX_BYTES:
        raise ValueError(
            "follow_up_issues evidence exceeds maximum length "
            f"({_FOLLOW_UP_EVIDENCE_MAX_BYTES} bytes)"
        )
    return value


@dataclass
class CompletionRecord:
    """Structured completion record written by coding-done/reviewer-done.

    This is the ONLY output from the completion commands - a JSON file that the
    orchestrator reads, validates (as untrusted input), and acts upon via adapters.

    The agent does NOT:
    - Push code
    - Create PRs
    - Post comments
    - Mutate labels

    The orchestrator verifies worktree state and executes all side effects.
    """
    # Core identification
    session_id: str  # Orchestrator's session identifier (e.g., "session-42")
    timestamp: str  # ISO format timestamp when the completion command was called

    # Outcome - what happened (not what to do)
    outcome: CompletionOutcome

    # Human-readable summary for logging/debugging
    summary: str

    # Requested actions - what the agent wants the orchestrator to do
    # Orchestrator validates and may reject/modify based on policy
    requested_actions: list[RequestedAction] = field(default_factory=list)

    # Status-specific data (all optional, validated based on outcome)
    # For COMPLETED
    implementation: Optional[str] = None  # What was implemented
    problems: Optional[str] = None  # Problems encountered

    # For BLOCKED
    blocked_reason: Optional[str] = None
    blocked_by: Optional[list[int]] = None  # Issue numbers
    attempted: Optional[str] = None
    when_unblocked: Optional[str] = None  # Hint for future agent

    # For NEEDS_HUMAN
    question: Optional[str] = None
    context: Optional[str] = None
    options: Optional[list[str]] = None
    default_action: Optional[str] = None

    # For REVIEW_* outcomes
    review_summary: Optional[str] = None  # For approved
    review_issues: Optional[str] = None  # For changes_requested
    risk_level: Optional[str] = None  # "low", "medium", "high"
    checks_passed: Optional[list[str]] = None
    checks_needed: Optional[list[str]] = None

    # Comment body to post (if POST_COMMENT in requested_actions)
    comment_body: Optional[str] = None

    # Extra labels to add to the PR (if CREATE_PR in requested_actions)
    pr_labels: Optional[list[str]] = None

    # Validation reference (if agent_gate was run)
    validation_record_path: Optional[str] = None  # Path to validation record JSON
    follow_up_issues: Optional[list["ProposedFollowUpIssue"]] = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "session_id": self.session_id,
            "timestamp": self.timestamp,
            "outcome": self.outcome.value,
            "summary": self.summary,
            "requested_actions": [a.value for a in self.requested_actions],
            "implementation": self.implementation,
            "problems": self.problems,
            "blocked_reason": self.blocked_reason,
            "blocked_by": self.blocked_by,
            "attempted": self.attempted,
            "when_unblocked": self.when_unblocked,
            "question": self.question,
            "context": self.context,
            "options": self.options,
            "default_action": self.default_action,
            "review_summary": self.review_summary,
            "review_issues": self.review_issues,
            "risk_level": self.risk_level,
            "checks_passed": self.checks_passed,
            "checks_needed": self.checks_needed,
            "comment_body": self.comment_body,
            "pr_labels": self.pr_labels,
            "validation_record_path": self.validation_record_path,
            "follow_up_issues": [
                issue.to_dict() for issue in self.follow_up_issues
            ] if self.follow_up_issues else None,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CompletionRecord":
        """Create from dictionary (JSON deserialization).

        Validates strictly - missing required fields or invalid values raise ValueError.
        This is UNTRUSTED input from the agent.
        """
        # Required fields
        required = ["session_id", "timestamp", "outcome", "summary"]
        for field_name in required:
            if field_name not in data:
                raise ValueError(f"Missing required field: {field_name}")

        try:
            outcome = CompletionOutcome(data["outcome"])
        except ValueError:
            raise ValueError(f"Invalid outcome: {data['outcome']}")

        raw_actions = data.get("requested_actions", [])
        if not isinstance(raw_actions, list):
            raise ValueError("requested_actions must be a list")
        if len(raw_actions) > _COMPLETION_REQUESTED_ACTIONS_MAX:
            raise ValueError(
                f"requested_actions exceeds maximum count "
                f"({len(raw_actions)} > {_COMPLETION_REQUESTED_ACTIONS_MAX})"
            )
        requested_actions = []
        for action in raw_actions:
            try:
                requested_actions.append(RequestedAction(action))
            except ValueError:
                raise ValueError(f"Invalid requested action: {action}")

        session_id = _check_required_string(
            "session_id", data["session_id"], max_bytes=_COMPLETION_STRING_MAX_BYTES
        )
        timestamp = _check_required_string(
            "timestamp", data["timestamp"], max_bytes=_COMPLETION_TIMESTAMP_MAX
        )
        summary = _check_required_string(
            "summary", data["summary"], max_bytes=_COMPLETION_STRING_MAX_BYTES
        )

        follow_up_raw = data.get("follow_up_issues")
        _check_follow_up_issues_count(follow_up_raw)

        return cls(
            session_id=session_id,
            timestamp=timestamp,
            outcome=outcome,
            summary=summary,
            requested_actions=requested_actions,
            implementation=_check_optional_string(
                "implementation", data.get("implementation")
            ),
            problems=_check_optional_string("problems", data.get("problems")),
            blocked_reason=_check_optional_string(
                "blocked_reason", data.get("blocked_reason")
            ),
            blocked_by=_check_blocked_by(data.get("blocked_by")),
            attempted=_check_optional_string("attempted", data.get("attempted")),
            when_unblocked=_check_optional_string(
                "when_unblocked", data.get("when_unblocked")
            ),
            question=_check_optional_string("question", data.get("question")),
            context=_check_optional_string("context", data.get("context")),
            options=_check_list_of_strings(
                "options",
                data.get("options"),
                max_bytes_per_item=_COMPLETION_OPTION_MAX_BYTES,
            ),
            default_action=_check_optional_string(
                "default_action", data.get("default_action")
            ),
            review_summary=_check_optional_string(
                "review_summary", data.get("review_summary")
            ),
            review_issues=_check_optional_string(
                "review_issues", data.get("review_issues")
            ),
            risk_level=_check_optional_string(
                "risk_level",
                data.get("risk_level"),
                max_bytes=_COMPLETION_RISK_LEVEL_MAX,
            ),
            checks_passed=_check_list_of_strings(
                "checks_passed", data.get("checks_passed")
            ),
            checks_needed=_check_list_of_strings(
                "checks_needed", data.get("checks_needed")
            ),
            comment_body=_check_optional_string(
                "comment_body", data.get("comment_body")
            ),
            pr_labels=_check_pr_labels(data.get("pr_labels")),
            validation_record_path=_check_validation_record_path(
                data.get("validation_record_path")
            ),
            follow_up_issues=[
                ProposedFollowUpIssue.from_dict(item)
                for item in follow_up_raw
            ] if follow_up_raw is not None else None,
        )


@dataclass(frozen=True)
class ProposedFollowUpIssue:
    """Structured proposal for ancillary work discovered during coding."""

    title: str
    reason: str
    evidence: str | None = None
    suggested_labels: list[str] | None = None
    blocking: bool = False

    def to_dict(self) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "title": self.title,
            "reason": self.reason,
            "blocking": self.blocking,
        }
        if self.evidence is not None:
            payload["evidence"] = self.evidence
        if self.suggested_labels is not None:
            payload["suggested_labels"] = self.suggested_labels
        return payload

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ProposedFollowUpIssue":
        title = _validate_follow_up_required_string(
            data.get("title"), "title", _FOLLOW_UP_TITLE_MAX_BYTES
        )
        reason = _validate_follow_up_required_string(
            data.get("reason"), "reason", _FOLLOW_UP_REASON_MAX_BYTES
        )
        suggested_labels = _validate_follow_up_suggested_labels(
            data.get("suggested_labels")
        )
        blocking = data.get("blocking", False)
        if not isinstance(blocking, bool):
            raise ValueError("follow_up_issues blocking must be a boolean")
        evidence = _validate_follow_up_evidence(data.get("evidence"))
        return cls(
            title=title,
            reason=reason,
            evidence=evidence if isinstance(evidence, str) else None,
            suggested_labels=suggested_labels,
            blocking=blocking,
        )


class SessionStatus(Enum):
    """Status of a Claude session."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    BLOCKED = "blocked"
    NEEDS_HUMAN = "needs_human"
    FAILED = "failed"
    TIMED_OUT = "timed_out"
    VALIDATION_FAILED = "validation_failed"  # Agent completed but validation gate failed
    NEEDS_VALIDATION_RETRY = "needs_validation_retry"  # Validation failed but retries remaining


class IssueStatus(Enum):
    """Status of an issue in the queue."""
    AVAILABLE = "available"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    NEEDS_HUMAN = "needs_human"
    COMPLETED = "completed"


SessionHistoryStatus: TypeAlias = Literal[
    "completed",
    "merged",
    "closed",
    "failed",
    "validation_failed",
    "blocked",
    "needs_human",
    "timed_out",
]
AwaitingMergeTerminalStatus: TypeAlias = Literal["merged", "closed"]
AwaitingMergeReconciliationSource: TypeAlias = Literal["pull_request", "issue"]
RECONCILABLE_HISTORY_STATUSES: frozenset[SessionHistoryStatus] = frozenset({"completed"})
TERMINAL_AWAITING_MERGE_HISTORY_STATUSES: frozenset[AwaitingMergeTerminalStatus] = frozenset(
    {"merged", "closed"}
)
DONE_HISTORY_STATUSES: frozenset[SessionHistoryStatus] = frozenset(
    {"completed", "merged", "closed"}
)


@dataclass
class StatusRollupCapability:
    """Repo-wide, cross-tick backoff state for reading PR status rollups.

    Lives on :class:`OrchestratorState` because the awaiting-merge
    reconciler (and the gate it delegates rollup reads to) are rebuilt
    every tick — only ``OrchestratorState`` survives across ticks. A
    single repo-wide timestamp is the right granularity: permission to
    read the primary (GraphQL) ``statusCheckRollup`` is a property of the
    configured token, not of any one PR, so once it is denied every GraphQL
    probe fails identically until an operator fixes the token.
    ``permission_denied_since`` records when that denial was last observed;
    the gate suppresses further GraphQL probes (and the repeated permission
    warning) until a backoff window elapses, then re-probes once in case
    the token was fixed. The backoff is GraphQL-source-scoped only: the gate
    still reads the REST check-run / commit-status fallback each tick, so a
    fallback-readable failure is never masked by the backoff.
    """

    permission_denied_since: float | None = None
BLOCKED_HISTORY_STATUSES: frozenset[SessionHistoryStatus] = frozenset(
    {"blocked", "needs_human", "failed", "validation_failed", "timed_out"}
)


def session_history_status_from_session_status(status: SessionStatus) -> SessionHistoryStatus:
    """Convert a session status into a persisted history status."""
    history_statuses: dict[SessionStatus, SessionHistoryStatus] = {
        SessionStatus.COMPLETED: "completed",
        SessionStatus.BLOCKED: "blocked",
        SessionStatus.NEEDS_HUMAN: "needs_human",
        SessionStatus.FAILED: "failed",
        SessionStatus.VALIDATION_FAILED: "validation_failed",
        SessionStatus.TIMED_OUT: "timed_out",
    }
    if status not in history_statuses:
        raise ValueError(f"Session status {status.value!r} is not a history status")
    return history_statuses[status]


@dataclass
class Issue:
    """A GitHub issue.

    Note: This class is being deprecated in favor of the Issue Protocol
    and GitHubIssue implementation. New code should use ports.issue.Issue
    and adapters.github.GitHubIssue.
    """
    number: int
    title: str
    labels: list[str]
    state: str = "open"  # "open" or "closed"
    repo: str = ""  # Repository in owner/repo format
    milestone: Optional[str] = None
    body: Optional[str] = None
    milestone_number: Optional[int] = None
    milestone_due_on: Optional[str] = None  # ISO date string
    created_at: Optional[str] = None  # ISO timestamp string
    updated_at: Optional[str] = None  # ISO timestamp string
    comment_count: int = 0

    @property
    def key(self) -> IssueKey:
        """Stable identity for this issue.

        Uses external ID from title prefix (e.g., [M1-011]) if present,
        otherwise falls back to the issue number as a string.
        """
        parsed = parse_external_id(self.title)
        external_id = parsed.external_id or str(self.number)
        return GitHubIssueKey(repo=self.repo, external_id=external_id)

    @property
    def agent_type(self) -> Optional[str]:
        """Extract agent type from labels (e.g., 'agent:web')."""
        for label in self.labels:
            if label.startswith("agent:"):
                return label
        return None

    @property
    def priority(self) -> int:
        """Extract priority (lower = higher priority)."""
        if "priority:high" in self.labels:
            return 1
        elif "priority:medium" in self.labels:
            return 2
        elif "priority:low" in self.labels:
            return 3
        return 4

    @property
    def is_blocked(self) -> bool:
        """Check if issue has any blocking label.

        Blocking labels: blocked, blocked-*, needs-human, failed (legacy).

        Blocked is a MODIFIER label that coexists with in-progress.
        An issue can be both in-progress AND blocked - this means:
        - We maintain ownership/claim on the issue
        - Work is paused waiting for intervention
        - When blocking label is removed, work resumes immediately
        """
        return any(_is_blocking_label(l) for l in self.labels)

    @property
    def is_in_progress(self) -> bool:
        """Check if issue has the 'in-progress' label."""
        return any(_base_of(l) == "in-progress" for l in self.labels)

    @property
    def needs_human(self) -> bool:
        """Check if issue specifically needs human intervention.

        Subset of blocked - checks for: needs-human, blocked-needs-human.
        """
        return any(_base_of(l) in ("blocked-needs-human", "needs-human") for l in self.labels)


def resolve_retrospective_coder_agent(
    issue: "IssueProtocol",
    reviewer_agent_label: str | None,
) -> str | None:
    """Return the coder agent that should receive retrospective-review rework."""

    for label in issue.labels:
        if label.startswith("agent:") and label != reviewer_agent_label:
            return label
    agent_label = issue.agent_type
    if agent_label and agent_label != reviewer_agent_label:
        return agent_label
    return None


# Initial prompt used for review-kind launches when the agent config does not
# set an explicit ``initial_prompt``. The AgentConfig field default below is
# coding-flavored; inheriting it for a review launch would tell the reviewer
# to do coding work and call coding-done (prompt/protocol drift).
DEFAULT_REVIEW_INITIAL_PROMPT = (
    "Review PR #{pr_number} for issue #{issue_number}: {issue_title}. "
    "Follow the instructions in {prompt}. "
    "When done, use reviewer-done to report your verdict."
)

# Task kinds whose default initial prompt is the review prompt above.
_REVIEW_TASK_KINDS = frozenset(
    {TaskKind.REVIEW.value, TaskKind.RETROSPECTIVE_REVIEW.value}
)


@dataclass
class AgentConfig:
    """Configuration for an agent type."""
    prompt_path: Path
    # Original relative path from config - used in commands so agents read from worktree
    prompt_relative: str = ""
    # Provider name (e.g., "claude-code", "codex") - validated against agent_runner registry
    # If not set, uses default_agent.provider. If that's also not set, config validation fails.
    provider: Optional[str] = None
    model: str = "sonnet"
    timeout_minutes: int = 45
    # Provider-specific arguments (e.g., permission_mode for claude-code, approval_mode for codex)
    # Claude permission modes: default, acceptEdits, bypassPermissions, plan, dontAsk
    provider_args: dict[str, Any] = field(default_factory=dict)
    # Opt-in (default OFF) to the orchestrator-computed OS sandbox (ADR-0034),
    # under a TRUSTED-repository contract: the operator onboards the target repo,
    # so its Claude config + the operator's user/managed settings are trusted, and
    # the sandbox constrains the AGENT. When True, a claude-code launch replaces
    # yolo ``bypassPermissions`` with ``dontAsk`` + a bounded ``--settings``:
    # Bash and native file-tool WRITES are worktree-scoped, known secrets and
    # restricted egress are denied, and the agent cannot modify its own policy
    # files. Non-secret native READS outside the worktree remain possible by
    # design (this is not a read jail). Codex uses an invocation-scoped native
    # permission profile for equivalent write/secret/egress boundaries; its
    # additional read roots are also writable because Codex has no read-only
    # ``--add-dir``. Linked-worktree commits receive narrow access to the current
    # worktree's Git state/current ref and the shared loose-object store; other
    # shared Git metadata stays read-only. Provider-less/custom-command agents
    # are rejected.
    # Distinct from codex's ``provider_args.sandbox`` (a codex CLI policy string).
    sandbox: bool = False
    # Skip code review for this agent (e.g., domain-expert agents that don't produce code)
    skip_review: bool = False
    # Per-agent reviewer override (uses review.default if not set)
    reviewer: Optional[str] = None
    # Command template - escape hatch to override provider-generated command
    # If set, this is used instead of provider.build_command()
    # For one-shot mode, add -p flag (Claude), use 'exec' (Codex), or -p (Gemini)
    # Note: {system_prompt} includes completion instructions + "Read {prompt} for task instructions"
    command: str = "claude -p {claude_args} --permission-mode {permission_mode} --model {model} --append-system-prompt '{system_prompt}' '{initial_prompt}'"
    # Optional override for hook verification AI agent (e.g., "claude-code")
    meta_agent: Optional[str] = None
    initial_prompt: str = "Work on issue #{issue_number}: {issue_title}. Follow the instructions in {prompt}. When done, use coding-done to report completion."
    # AI system type for log retrieval (e.g., "claude-code", "codex", "gemini", "aider")
    # If not set, auto-detected from command. Must match an entry in ai-systems.yaml.
    ai_system: Optional[str] = None
    # Path to retry prompt template (relative to repo root). Used when validation fails.
    # If not set, uses validation.retry_prompt_template or built-in default.
    # Template variables: {original_task}, {validation_cmd}, {error_file}, {error_summary},
    #                     {retry_count}, {max_retries}
    retry_prompt_template: Optional[str] = None

    @property
    def effective_permission_mode(self) -> str:
        """Claude permission mode from ``provider_args`` (``"default"`` when unset).

        Single read shared by command rendering, session identity metadata,
        and failure diagnostics — there is exactly one place permission mode
        is spelled (``provider_args.permission_mode``) and one place it is
        resolved.
        """
        mode = self.provider_args.get("permission_mode")
        if isinstance(mode, str) and mode:
            return mode
        return "default"

    def _initial_prompt_template(self, task_kind: str) -> str:
        """Initial prompt template for ``task_kind``.

        An explicitly configured ``initial_prompt`` always wins. When the
        field still holds its coding-flavored dataclass default, review-kind
        launches get the review default instead — a reviewer must never be
        told to do coding work and call coding-done.
        """
        field_default = type(self).__dataclass_fields__["initial_prompt"].default
        if self.initial_prompt != field_default:
            return self.initial_prompt
        if task_kind in _REVIEW_TASK_KINDS:
            return DEFAULT_REVIEW_INITIAL_PROMPT
        return self.initial_prompt

    def render_initial_prompt(
        self,
        issue_number: int,
        issue_title: str,
        worktree: Path,
        pr_number: Optional[int] = None,
        existing_work: Optional[str] = None,
        task_kind: str = TaskKind.CODE.value,
    ) -> str:
        """Render the session prompt text before command wrapping."""
        prompt_for_command = self.prompt_relative if self.prompt_relative else str(self.prompt_path)
        format_kwargs = {
            "issue_number": issue_number,
            "issue_title": issue_title,
            "prompt": prompt_for_command,
            "worktree": worktree,
            "model": self.model,
            "permission_mode": self.effective_permission_mode,
            "claude_args": os.environ.get("ORCHESTRATOR_CLAUDE_ARGS", "").strip(),
        }
        if pr_number is not None:
            format_kwargs["pr_number"] = pr_number

        rendered_prompt = self._initial_prompt_template(task_kind).format(**format_kwargs)
        if existing_work:
            rendered_prompt = f"IMPORTANT: {existing_work}\n\n{rendered_prompt}"
        return rendered_prompt

    def resolve_launch_provider(self) -> Optional[str]:
        """Provider identity for building a LAUNCH command.

        ``provider`` wins. An explicitly configured ``command`` (anything
        other than the field default) is an intentional override and keeps
        template-based launching — exchange stub agents configure a custom
        ``command`` alongside a real ``ai_system``. Otherwise ``ai_system``
        resolves: it shares the provider-registry vocabulary
        (``claude-code``, ``codex``).

        Exists because session CLASSIFICATION (``provider or ai_system``,
        see ``persistent_session_exchange._agent_provider``) and command
        BUILDING (``provider`` only, else the legacy ``claude -p`` template)
        resolved differently: an ``ai_system="codex"`` reviewer with no
        ``provider`` was classified as codex but silently launched as
        print-mode claude, which renders nothing and hangs the round to its
        full timeout (caught by the real-codex exchange smoke test).
        """
        if self.provider:
            return self.provider
        if self.command != type(self).__dataclass_fields__["command"].default:
            return None
        return self.ai_system

    def get_command(
        self,
        issue_number: int,
        issue_title: str,
        worktree: Path,
        pr_number: Optional[int] = None,
        existing_work: Optional[str] = None,
        task_kind: str = "code",
        extra_provider_args: Optional[dict[str, Any]] = None,
    ) -> str:
        """Render the command template with actual values, including initial prompt.

        If a provider is configured, uses the provider's build_command() method.
        Otherwise, falls back to the custom command template.

        Args:
            issue_number: The GitHub issue number
            issue_title: The issue title
            worktree: Path to the worktree
            pr_number: Optional PR number (for review agents). If a prompt template
                       uses {pr_number} but this is not provided, a KeyError is raised.
            existing_work: Optional context about existing commits in the worktree.
                          If provided, prepended to prompt so agent knows to complete vs restart.
            task_kind: The task kind value (e.g., "code", "rework", "review", "tech_lead").
                      Determines which completion instructions are injected.
        """
        prompt_for_command = self.prompt_relative if self.prompt_relative else str(self.prompt_path)
        rendered_prompt = self.render_initial_prompt(
            issue_number=issue_number,
            issue_title=issue_title,
            worktree=worktree,
            pr_number=pr_number,
            existing_work=existing_work,
            task_kind=task_kind,
        )
        return self.get_command_for_prompt(
            rendered_prompt,
            issue_number=issue_number,
            issue_title=issue_title,
            worktree=worktree,
            pr_number=pr_number,
            prompt_file=prompt_for_command,
            task_kind=task_kind,
            extra_provider_args=extra_provider_args,
        )

    def get_command_for_prompt(
        self,
        rendered_prompt: str,
        *,
        worktree: Path,
        issue_number: int = 0,
        issue_title: str = "",
        pr_number: Optional[int] = None,
        prompt_file: str | None = None,
        task_kind: str = "code",
        evidence_read_roots: tuple[Path, ...] = (),
        extra_provider_args: Optional[dict[str, Any]] = None,
    ) -> str:
        """Build an agent command for an already-rendered prompt.

        ``evidence_read_roots`` is the read-only god-view grant for a tech-lead
        failure investigation (empty otherwise): the sandbox reads those roots
        while writes stay confined to ``worktree`` (#6824 R5).
        """
        prompt_for_command = prompt_file or (
            self.prompt_relative if self.prompt_relative else str(self.prompt_path)
        )
        # Resolve the per-session sandbox scope (ADR-0034) BEFORE choosing the
        # provider vs legacy-template path. Returns None unless this agent opted
        # in. ``sandbox: true`` is a security opt-in, so if a scope is requested
        # and there is no enforcing provider adapter (the provider-less/custom-
        # ``command`` launch mode), FAIL LOUD rather than silently render an
        # unsandboxed legacy-template command.
        sandbox_scope = compute_session_scope(
            self,
            SandboxScopeContext(
                task_kind=task_kind,
                worktree=worktree,
                evidence_read_roots=evidence_read_roots,
            ),
        )
        if sandbox_scope is not None and not self.provider:
            raise SandboxUnsupportedError(
                "sandbox: true is not supported for a provider-less / custom-command "
                "agent — the launcher cannot enforce the sandbox. Use a provider "
                "adapter (provider: claude-code), or set sandbox: false."
            )
        if self.provider:
            # The worktree anchors the sandbox's read/write roots; the task kind
            # selects the role. Each provider adapter must enforce or fail loud.
            return self._build_provider_command(
                rendered_prompt,
                prompt_for_command,
                task_kind,
                extra_provider_args,
                sandbox_scope=sandbox_scope,
            )

        # Legacy template-based command building (never sandboxed — guarded above)
        from issue_orchestrator.resources import get_completion_instructions

        # Escape single quotes in the prompt for shell safety
        escaped_prompt = rendered_prompt.replace("'", "'\\''")

        # Build the full system prompt with completion instructions
        completion_docs = get_completion_instructions(task_kind)
        system_prompt = (
            f"{completion_docs}\n\n"
            f"---\n\n"
            f"Read {prompt_for_command} for your task-specific instructions."
        )
        # Escape single quotes for shell embedding
        escaped_system_prompt = system_prompt.replace("'", "'\\''")

        # Then render the full command with the prompt included
        format_kwargs = {
            "issue_number": issue_number,
            "issue_title": issue_title,
            "prompt": prompt_for_command,
            "worktree": worktree,
            "model": self.model,
            "permission_mode": self.effective_permission_mode,
            "claude_args": os.environ.get("ORCHESTRATOR_CLAUDE_ARGS", "").strip(),
            "initial_prompt": escaped_prompt,
            "system_prompt": escaped_system_prompt,
        }
        if pr_number is not None:
            format_kwargs["pr_number"] = pr_number

        prompt_mode = os.environ.get("ORCHESTRATOR_CLAUDE_PROMPT_MODE", "arg").strip().lower()
        if prompt_mode == "stdin":
            template = (
                "printf '%s' '{initial_prompt}' | "
                "claude {claude_args} --input-format text "
                "--permission-mode {permission_mode} --model {model} "
                "--append-system-prompt '{system_prompt}'"
            )
            return template.format(**format_kwargs)

        return self.command.format(**format_kwargs)

    def _build_provider_command(
        self,
        prompt: str,
        prompt_file: str,
        task_kind: str,
        extra_provider_args: dict[str, Any] | None = None,
        *,
        sandbox_scope: SandboxScope | None = None,
    ) -> str:
        """Build command using the configured provider.

        Args:
            prompt: The fully rendered prompt to send to the agent
            prompt_file: Path to the prompt/instructions file (for system prompt)
            task_kind: The task kind value (e.g., "code", "rework", "review", "tech_lead").
            extra_provider_args: Per-issue overrides (e.g., from labels) merged on top
                of the agent's ``provider_args``.
            sandbox_scope: The per-session sandbox scope (ADR-0034), or ``None``
                when the agent has not opted in. ``None`` yields the exact
                unsandboxed command as before.

        Returns:
            Shell-safe command string
        """
        from issue_orchestrator.agent_runner import get_provider
        from issue_orchestrator.resources import get_completion_instructions

        # self.provider is guaranteed non-None here (caller checks)
        assert self.provider is not None
        provider = get_provider(self.provider)

        # Build provider-specific kwargs from provider_args, with per-issue overrides
        kwargs = dict(self.provider_args)
        if extra_provider_args:
            kwargs.update(extra_provider_args)

        # STRICT ENFORCEMENT: Completion instructions are ALWAYS injected for ALL providers.
        # - For Claude: inject via system_prompt (--append-system-prompt)
        # - For other providers: prepend to the prompt itself
        completion_docs = get_completion_instructions(task_kind)
        completion_with_prompt_ref = (
            f"{completion_docs}\n\n"
            f"---\n\n"
            f"Read {prompt_file} for your task-specific instructions."
        )

        if self.provider == "claude-code":
            # Claude Code uses --append-system-prompt for completion instructions
            system_prompt = completion_with_prompt_ref
            # Append any user-provided system_prompt (completion instructions always come first)
            user_system_prompt = kwargs.pop("system_prompt", None)
            if user_system_prompt:
                system_prompt = f"{system_prompt}\n\n---\n\n{user_system_prompt}"
            kwargs["system_prompt"] = system_prompt
            # setdefault keeps per-issue extra_provider_args overrides
            # authoritative over the agent's effective_permission_mode.
            kwargs.setdefault("permission_mode", self.effective_permission_mode)
        else:
            # Other providers (Codex, etc.): prepend completion instructions to prompt
            prompt = f"{completion_with_prompt_ref}\n\n---\n\n{prompt}"

        # Build the command (returns list[str])
        model: Optional[str] = self.model
        if (
            model == type(self).__dataclass_fields__["model"].default
            and self.provider != "claude-code"
        ):
            # The field default ("sonnet") is claude vocabulary. Forwarding
            # it to another provider sends e.g. ``codex --model sonnet``,
            # which the codex backend rejects (400) and the TUI then idles
            # for the whole round timeout — caught live by the real-codex
            # exchange smoke test. An untouched default is "no explicit
            # choice": let the provider use its own default model.
            model = None
        cmd_list = provider.build_command(
            prompt=prompt, model=model, sandbox_scope=sandbox_scope, **kwargs
        )

        # Convert to shell-safe string
        return shlex.join(cmd_list)


@dataclass
class Session:
    """A running Claude session working on an issue.

    The `key` field is the domain identity (SessionKey) used for:
    - Duplicate prevention at launch
    - Lookup in active sessions
    - Removal when done
    - State machine lookup

    The `terminal_id` is an opaque handle that only the terminal adapter interprets.
    """
    key: SessionKey  # Domain identity - (IssueKey, TaskKind)
    issue: "IssueProtocol"
    agent_config: AgentConfig
    terminal_id: str  # Opaque handle - only terminal adapter interprets this
    worktree_path: Path
    branch_name: str
    run_assets: SessionRunAssets  # Exact session artifacts allocated before launch.
    completion_path: str = COMPLETION_RECORD_PATH  # Agent-specific path to completion.json
    agent_label: Optional[str] = None  # Agent type label (e.g., "agent:backend") for per-agent reviewer
    pr_number: int | None = None  # PR number for review/rework sessions
    rework_cycle: int | None = None  # Which rework iteration (1, 2, ...) — None for initial coding
    started_at: datetime = field(default_factory=datetime.now)
    status: SessionStatus = SessionStatus.RUNNING
    exit_sent: bool = False  # Track if we've already sent /exit
    completion_detected_at: datetime | None = None  # First time observer saw a valid completion.json for this session
    validation_retry_count: int = 0  # Number of validation retries attempted
    original_prompt: str | None = None  # Original prompt for retry context
    last_validation_error: str | None = None  # Last validation error for retry prompt
    last_validation_error_file: str | None = None  # Path to validation error file
    last_output_monotonic: float | None = None
    last_output_at: float | None = None
    last_log_mtime: float | None = None
    last_log_size: int | None = None
    last_output_tail: str | None = None
    last_no_output_monotonic: float | None = None
    # Claim/lease fields for multi-orchestrator coordination
    lease_id: str | None = None  # Unique identifier for the claim
    lease_acquired_at: datetime | None = None  # When the claim was acquired
    lease_expires_at: datetime | None = None  # When the claim expires if not renewed
    last_claim_verified_at: datetime | None = None  # Last time we verified we're still the winner
    # True for a tech_lead failure investigation running in a disposable, run-scoped
    # scratch worktree (#6823). The worktree is a throwaway that reads its focus
    # issue as evidence, so completion must remove it regardless of the cleanup
    # config (a "keep worktrees for inspection" preference is for PR-producing
    # coding worktrees, not for scratch investigation workspaces).
    scratch_worktree: bool = False

    def __post_init__(self) -> None:
        _require_session_run_assets(self.run_assets)

    @property
    def run_dir(self) -> Path:
        """Exact session artifact directory allocated before launch."""
        return self.run_assets.run_dir

    @property
    def runtime_minutes(self) -> int:
        """How long this session has been running."""
        delta = datetime.now() - self.started_at
        return int(delta.total_seconds() / 60)

    @property
    def is_timed_out(self) -> bool:
        """Check if session exceeded timeout."""
        return self.runtime_minutes > self.agent_config.timeout_minutes


def _require_session_run_assets(value: object) -> None:
    if isinstance(value, Mock) or not isinstance(value, SessionRunAssets):
        raise TypeError("Session.run_assets must be a SessionRunAssets")


def is_retrospective_review_session(session: Session) -> bool:
    """Return true for current and restored retrospective review sessions."""

    return (
        session.key.task == TaskKind.RETROSPECTIVE_REVIEW
        or session.terminal_id.startswith(RETROSPECTIVE_REVIEW_TERMINAL_PREFIX)
    )


def active_retrospective_review_issue_numbers(sessions: Iterable[Session]) -> set[int]:
    """Return issue numbers with an active retrospective review session."""

    return {
        session.issue.number
        for session in sessions
        if is_retrospective_review_session(session)
    }


@dataclass
class SessionHistoryEntry:
    """Record of a completed session."""
    issue_number: int
    title: str
    agent_type: str
    status: SessionHistoryStatus
    runtime_minutes: int
    pr_url: Optional[str] = None  # Set if PR was created
    status_reason: Optional[str] = None  # Human-readable explanation of status
    worktree_path: Optional[Path] = None
    completed_at: Optional[datetime] = None  # When the session completed (for sequence visibility)
    issue_labels: tuple[str, ...] = ()  # Snapshot retained for area/seam facts


@dataclass
class PendingCleanup:
    """A session awaiting cleanup after review completes.

    Tracks sessions that completed successfully but need to wait for
    code review or tech_lead review before closing tabs/removing worktrees.
    """
    issue: "IssueProtocol"  # The issue this cleanup is for
    pr_number: int
    pr_url: str
    branch_name: str
    terminal_id: str
    worktree_path: Path

    @property
    def issue_number(self) -> int:
        """Backwards-compatible access to issue number."""
        return self.issue.number


@dataclass
class PendingReview:
    """A PR queued for code review.

    Store-agnostic: uses IssueKey for identity, not GitHub-specific fields.
    """
    issue_key: "IssueKey"     # Store-agnostic identity
    pr_number: int
    pr_url: str
    branch_name: str
    _issue_number: int  # The actual GitHub issue number (stable_id may not be numeric)
    agent_label: Optional[str] = None  # Agent that created the PR (for per-agent reviewer)
    issue_labels: tuple[str, ...] = field(default_factory=tuple, compare=False)

    @property
    def issue_number(self) -> int:
        """Access to issue number (stored explicitly, not derived from stable_id)."""
        return self._issue_number


@dataclass
class PendingRetrospectiveReview:
    """An issue queued for review of its existing implementation.

    This is review-first lifecycle work: a reviewer audits the implementation
    already present in the base branch or prior orchestrator PR. Approval
    records the review; changes requested hands the issue to a coder rework
    cycle that will create a normal PR.
    """

    issue_key: "IssueKey"
    issue_number: int
    issue_title: str
    agent_label: str
    trigger_label: str
    prior_pr_number: int | None = None
    prior_pr_url: str | None = None
    # The issue's real labels, captured at discovery. Carried through launch so
    # completion policy (e.g. clearing blocking labels) sees the true state —
    # the launched session otherwise only knows synthetic agent/trigger labels.
    issue_labels: tuple[str, ...] = ()


@dataclass(frozen=True)
class DiscoveredReview:
    """A PR discovered from session completion, pending Planner decision.

    This is a "fact" - the Planner will decide whether to queue it.
    Immutable to be safely included in OrchestratorSnapshot.
    """
    issue_number: int
    pr_number: int
    pr_url: str
    branch_name: str
    agent_label: Optional[str] = None  # Agent that created the PR (for per-agent reviewer)
    issue_key: str = ""  # stable_id; falls back to str(issue_number) when empty


@dataclass(frozen=True)
class DiscoveredRetrospectiveReview:
    """A trigger-labeled issue discovered for retrospective review."""

    issue_number: int
    issue_title: str
    agent_label: str
    trigger_label: str
    issue_key: str = ""
    prior_pr_number: int | None = None
    prior_pr_url: str | None = None
    issue_labels: tuple[str, ...] = ()


@dataclass(frozen=True)
class DiscoveredAwaitingMergeReconciliation:
    """A history-backed awaiting-merge transition discovered by repository scans.

    This is a fact. The Planner decides whether to emit a history reconciliation
    action, and the ActionApplier performs the actual history mutation.
    """

    issue_number: int
    pr_number: int
    pr_url: str
    status: AwaitingMergeTerminalStatus
    status_reason: str
    source: AwaitingMergeReconciliationSource
    issue_key: str = ""  # stable_id; falls back to str(issue_number) when empty


@dataclass(frozen=True)
class DiscoveredAwaitingMergeDrift:
    """An open issue still labeled awaiting-merge after its PR left that state.

    This is a fact. The Planner decides whether to move the issue into a
    blocked reconciliation state and which labels to mutate.
    """

    issue_number: int
    pr_number: int
    pr_url: str
    status_reason: str
    issue_key: str = ""  # stable_id; falls back to str(issue_number) when empty


@dataclass(frozen=True)
class TechLeadFacts:
    """Facts about tech_lead review trigger conditions.

    Immutable snapshot of conditions for Planner to decide on tech_lead.
    """
    pr_count: int = 0  # PRs with watch label
    threshold: int = 0  # Configured threshold (<= 0: batch trigger disabled)
    existing_tech_lead_issue: Optional[int] = None  # Existing open tech_lead issue number
    watch_label: str = ""  # Label being watched ("": batch trigger disabled)
    prs: tuple[Any, ...] = field(default_factory=tuple)  # PR info for body generation
    # Labels from source issues/PRs (for label inheritance)
    source_labels: frozenset[str] = field(default_factory=frozenset)
    # Milestones from source issues: tuple of (number, title) for milestone inheritance
    source_milestones: tuple[tuple[int, str], ...] = field(default_factory=tuple)
    # Periodic health review (ADR-0031 §4). Independent of the batch fields
    # above: tech_lead.health_review.interval_minutes gates these while
    # tech_lead_review_threshold gates only the batch fields.
    health_review_due: bool = False  # Interval elapsed since the last health review
    # The board fingerprint ``health_review_due`` was decided against. Travels
    # with the verdict so anchor creation records the board it fired on rather
    # than recomputing against a board that has since changed (#6793).
    health_review_fingerprint: str = ""
    existing_health_review_issue: Optional[int] = None  # Open marker-labeled anchor issue
    # Approved gated tech_lead proposals (#6778): open issues that carry a
    # StoredTechLeadOp but no longer carry the proposed-tech-lead gate label,
    # classified from the SAME anchor scan. The planner turns each into the
    # stored op's execution action.
    approved_tech_lead_ops: tuple["ApprovedTechLeadOp", ...] = field(default_factory=tuple)
    # Ledger rows whose proposal issue was ABSENT from the exhaustive scan
    # (#6779 R7). Absence is only a candidate for terminal cleanup — the scan
    # can be truncated — so the planner emits a
    # DiscardTerminalTechLeadProposalOpsAction and the applier confirms each with
    # a fresh targeted read before discarding. Surfacing these as a fact keeps
    # fact gathering read-only (#6779 R10).
    absent_proposal_op_candidates: tuple[int, ...] = field(default_factory=tuple)
    # Open pattern case files (#6781): observation-labeled issues classified
    # from the SAME anchor scan. Projected into the board snapshot so health
    # reviews mine accumulated evidence, and into the tech_lead board file.
    open_case_files: tuple["TechLeadCaseFileSummary", ...] = field(default_factory=tuple)
    # Whether THIS tick actually ran the exhaustive anchor scan that observes
    # open case files (#6781 R2). API-frugal ticks (health armed but not due,
    # no batch, empty op ledger) skip the scan and therefore carry
    # ``open_case_files=()`` meaning "not observed this tick" — NOT "observed
    # empty". Defaults to False so a facts snapshot that did not scan never
    # claims authority over the case-file projection: the board publisher
    # retains its last projection on such ticks and only replaces it when a
    # scan actually ran, so durable case-file evidence survives between scans
    # instead of being wiped by a frugal tick.
    case_files_scanned: bool = False


@dataclass(frozen=True)
class DiscoveredRework:
    """A PR discovered needing rework, pending Planner decision.

    This is a "fact" - the Planner will decide whether to queue it.
    Immutable to be safely included in OrchestratorSnapshot.
    """
    issue_number: int
    pr_number: int
    branch_name: str
    agent_type: str
    rework_cycle: int = 1
    source: str = "review_label"
    feedback: str | None = None
    # Set when post-publish validation recovers a PR that had already been
    # escalated to human review. The planner clears the stale human label while
    # routing it back to automated rework.
    clear_needs_human: bool = False
    # True when the discovery path already saw the feedback comment marker
    # on the PR, so the planner must not enqueue a duplicate comment. The
    # rework itself is still queued (idempotency is owned by labels/pending
    # state, not the comment).
    feedback_comment_already_posted: bool = False


@dataclass(frozen=True)
class DiscoveredEscalation:
    """An escalation discovered during rework scan, pending Planner decision.

    This is a "fact" - the Planner will decide whether to escalate.
    Immutable to be safely included in OrchestratorSnapshot.
    """
    issue_number: int
    pr_number: int
    rework_cycle: int


# Reasons a post-publish escalation can fire — distinct from rework-cycle
# exhaustion so the planner / applier can pick the right comment copy.
PostPublishEscalationKind = Literal[
    "checks_pending_timeout",   # required checks pending > timeout after approval
    "branch_protection_blocked",  # mergeable_state=blocked but rollup=SUCCESS
    "status_rollup_permission_denied",  # token cannot read check status to decide
    "merge_queue_failed",  # GitHub merge queue rejected the PR; failure_action=needs_human
]


@dataclass(frozen=True)
class DiscoveredAwaitingMergeEscalation:
    """A reviewer-approved PR is stuck in a state code rework can't fix.

    Emitted when:
      - WAIT_FOR_CHECKS has been observed for longer than the configured
        `post_publish_checks_pending_timeout_seconds`, OR
      - mergeable_state=blocked with status checks all SUCCESS (branch
        protection — approvals/CODEOWNERS/signatures, not a code issue).

    The planner converts this into an EscalateToHumanAction with a
    cause-specific comment so the reader knows why the orchestrator gave
    up the automated path.
    """
    issue_number: int
    pr_number: int
    pr_url: str
    issue_key: str
    rework_cycle: int  # carried for label/comment continuity
    kind: PostPublishEscalationKind
    reason: str  # short human-readable summary, used in the PR comment


@dataclass(frozen=True)
class DiscoveredMergeQueueEnqueue:
    """A reviewer-approved PR is eligible to enter the GitHub merge queue.

    Emitted only when merge queue mode is enabled and the merge queue
    coordinator decides the PR has cleared the gate, is not already queued,
    and is mergeable-or-behind (behind-base is enqueue-eligible, NOT rework).

    This is a "fact" — the Planner converts it into an
    ``EnqueueToMergeQueueAction`` and the ActionApplier performs the protected
    enqueue. Mutations never happen in the discovery path.
    """
    issue_number: int
    pr_number: int
    pr_url: str
    issue_key: str


@dataclass(frozen=True)
class DiscoveredFailure:
    """A session problem discovered, pending Planner decision on tech_lead.

    This is a "fact" - the Planner will decide whether to queue a tech_lead review.
    Immutable to be safely included in OrchestratorSnapshot.

    ``failure_reason`` covers terminal failures (``failed`` / ``timed_out``)
    plus explicit worker blocks (``blocked``). ``blocking_label`` preserves
    the completion policy's classification so the reaction model can treat a
    ``blocked-failed``-class outcome as unexplained while still recognizing a
    plain block that dependency policy can explain as healthy waiting.

    ``observed_at`` is epoch seconds at the discovery boundary. It lets the
    reaction owner group problems across adjacent ticks without relying on the
    planner tick rate. A zero value is accepted for restored/legacy test facts;
    a current-tick discovery treats it as current, while an already-pending
    legacy fact cannot count toward a time-bounded storm.

    ``issue_body`` and ``issue_milestone`` preserve dependency inputs from the
    completed session. The filtered issue queue may no longer contain that
    active issue after completion, but reaction classification must still be
    able to distinguish a tracked open dependency from an unexplained block.

    ``artifact_hints`` are absolute paths to on-disk artifacts a failure
    investigation should start from (failure diagnostic, session run
    manifest/analysis, attached agent log). Populated at the discovery seam
    (``handle_session_completion``) with only paths that EXIST at completion
    time — downstream consumers (plan -> queue -> board snapshot) project
    them verbatim and must never invent or discard them.
    """
    issue_number: int
    issue_title: str
    failure_reason: str  # "failed", "timed_out", or "blocked"
    artifact_hints: tuple[str, ...] = ()
    observed_at: float = 0.0
    blocking_label: str = ""
    issue_body: str = ""
    issue_milestone: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize for the durable storm-cohort ledger (#6780).

        A storm cohort outlives the process that discovered it: the anchor is
        created on tick N and the health review may launch after a restart, so
        the ledger must round-trip the WHOLE fact — ``artifact_hints`` above
        all, since the recovered board snapshot projects them verbatim.
        """
        return {
            "issue_number": self.issue_number,
            "issue_title": self.issue_title,
            "failure_reason": self.failure_reason,
            "artifact_hints": list(self.artifact_hints),
            "observed_at": self.observed_at,
            "blocking_label": self.blocking_label,
            "issue_body": self.issue_body,
            "issue_milestone": self.issue_milestone,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DiscoveredFailure":
        """Rehydrate a ledger row. Missing keys raise (fail-fast).

        The orchestrator writes every key in :meth:`to_dict`, so an absent one
        means a corrupt or hand-edited row — never a shape to paper over with
        defaults that would silently launch a health review with a truncated
        cohort.
        """
        return cls(
            issue_number=data["issue_number"],
            issue_title=data["issue_title"],
            failure_reason=data["failure_reason"],
            artifact_hints=tuple(data["artifact_hints"]),
            observed_at=data["observed_at"],
            blocking_label=data["blocking_label"],
            issue_body=data["issue_body"],
            issue_milestone=data["issue_milestone"],
        )


@dataclass(frozen=True)
class ImmediateCleanup:
    """A session that needs immediate cleanup (no deferred review).

    Created when a session completes/times out and cleanup should happen
    immediately (not deferred until tech_lead review).
    """
    issue_number: int
    terminal_id: str  # e.g., "issue-123", "review-456"
    worktree_path: str
    reason: str  # e.g., "completed", "timed_out"
    # True when ``worktree_path`` is a disposable tech-lead-investigation scratch
    # worktree (#6823): the Planner forces its removal even when the cleanup
    # config would otherwise keep worktrees, so scratch workspaces never
    # accumulate.
    scratch_worktree: bool = False


@dataclass(frozen=True)
class CleanupFacts:
    """Facts about pending cleanups and their review status.

    Immutable snapshot of conditions for Planner to decide on cleanups.
    """
    pending_cleanups: tuple[Any, ...]  # tuple of PendingCleanup-like info
    reviewed_pr_numbers: frozenset[int]  # PRs that have the cleanup label
    close_tabs: bool = False  # Config: whether to close terminal tabs
    remove_worktrees: bool = False  # Config: whether to remove worktrees
    # Immediate cleanups (no deferred review) - sessions that completed/timed out
    immediate_cleanups: tuple["ImmediateCleanup", ...] = field(default_factory=tuple)
    # Issues whose failed-session run assets a failure investigation still
    # references (discovered/queued/active) — the Planner must NOT clean these
    # up yet or the investigation launches into deleted artifact hints
    # (#6771 round 3). Computed by failure_investigation_hold_issue_numbers.
    held_issue_numbers: frozenset[int] = frozenset()


@dataclass
class PendingRework:
    """A work item that needs rework after review requested changes.

    Store-agnostic: uses IssueKey for identity, not GitHub-specific fields.
    Adapters resolve the key to backing-store details (PR number, branch, URL).
    """
    issue_key: "IssueKey"     # Store-agnostic identity
    agent_type: str           # Cached to avoid lookup at launch time
    rework_cycle: int = 1     # Which rework iteration this is (1, 2, etc.)
    issue_number: int | None = None  # Backing store handle for GitHub rework flows
    pr_number: int | None = None  # PR number that needs rework (from scanner)
    source: str = "review_label"
    feedback: str | None = None

    def resolve_issue_number(self) -> int | None:
        """Resolve issue number for GitHub workflows, if available."""
        if self.issue_number is not None:
            return self.issue_number
        try:
            return int(self.issue_key.stable_id())
        except (TypeError, ValueError):
            return None


@dataclass
class PendingTechLeadReview:
    """A tech_lead session queued for processing (ADR-0031).

    Tech Lead reviews are treated as reviews (not work items) so they get
    processed with priority, alongside pending_reviews and pending_reworks.

    The queue holds BOTH tech_lead variants: threshold-created batch tracking
    issues (audit the PR manifest) and failure investigations (diagnose one
    failed issue). ``flavor`` is required so every producer boundary declares
    which variant it is queueing; the launch path forwards it verbatim
    (#6768 B5 — collapsing both to one flavor made batch reviews skip
    manifest prep and audit nothing).

    ``failure`` preserves the typed triggering-failure context across the
    queue boundary: ``state.discovered_failures`` is a per-tick fact buffer
    cleared after planning, but the queued item is consumed on a LATER tick,
    so the launch-time board snapshot must read the failure from the queue
    item, not the buffer. It is required for FAILURE_INVESTIGATION (that
    variant exists only because a failure was discovered) and forbidden for
    BATCH_REVIEW and HEALTH_REVIEW. A storm-triggered HEALTH_REVIEW instead
    carries all triggering problems in ``problem_cohort``.
    """
    issue_number: int  # The tech_lead review GitHub issue number
    title: str  # Issue title (for display)
    flavor: TechLeadSessionFlavor  # Which tech_lead variant this queue entry launches as
    failure: DiscoveredFailure | None = None  # Triggering failure (FAILURE_INVESTIGATION only)
    # Problem-storm context preserved for an unscheduled HEALTH_REVIEW. The
    # per-tick discovery buffer is cleared before the anchor launches, so the
    # pending owner must carry the exact cohort into the launch-time board
    # snapshot. Interval/batch reviews keep this empty.
    problem_cohort: tuple[DiscoveredFailure, ...] = ()
    # Retryable launch failures consumed so far (owner-tracked by
    # PendingSessionQueues.retain_tech_lead_for_retry; bounded — see
    # TECH_LEAD_LAUNCH_RETRY_LIMIT). For failure investigations this queue item
    # is the ONLY durable record of the investigation, so transient prep
    # failures retain it instead of dropping it.
    retryable_launch_failures: int = 0

    def launch_scope(self) -> TechLeadLaunchScope:
        """The typed grant this queued item hands the launch boundary (#6780).

        The queue item is the producer that knows both the variant and, for a
        storm, the exact cohort the review owns. Handing that grant down means
        the launch authority is built from the OWNED cohort instead of being
        inferred from the board snapshot, whose failure list also contains
        unrelated pending investigations.
        """
        return TechLeadLaunchScope(
            flavor=self.flavor,
            problem_issue_numbers=tuple(
                sorted({problem.issue_number for problem in self.problem_cohort})
            ),
        )

    def __post_init__(self) -> None:
        if self.flavor is TechLeadSessionFlavor.FAILURE_INVESTIGATION and self.failure is None:
            raise ValueError(
                f"PendingTechLeadReview for issue #{self.issue_number} is a failure "
                "investigation but carries no DiscoveredFailure context; the "
                "launch-time board snapshot would be missing its own triggering "
                "failure (the discovered_failures buffer is cleared after planning)."
            )
        if (
            self.flavor is not TechLeadSessionFlavor.FAILURE_INVESTIGATION
            and self.failure is not None
        ):
            raise ValueError(
                f"PendingTechLeadReview for issue #{self.issue_number} is a "
                f"{self.flavor.value} but carries failure context; batch and "
                "health reviews are threshold-/interval-created and have no "
                "triggering failure."
            )
        if self.problem_cohort and self.flavor is not TechLeadSessionFlavor.HEALTH_REVIEW:
            raise ValueError(
                f"PendingTechLeadReview for issue #{self.issue_number} carries a "
                "problem cohort but is not a health review"
            )


@dataclass
class PendingValidationRetry:
    """A session that needs to be re-launched with validation retry prompt.

    When validation fails but retries are remaining, the orchestrator queues
    a retry. The next tick will re-launch the session as a coding session with
    error context.

    ``source_task`` is the task kind of the session that produced the retry. It
    is required so every queue/recovery call site must declare provenance: a
    validation retry always relaunches as coding work, so a review-only source
    (PR review / retrospective review) is rejected at construction. Review-only
    sessions make no commits, and relaunching one as coding work opens a PR on an
    empty branch (see issue #6426). This is the owner-boundary guard that
    complements the recovery scanner skipping review-only run directories.
    """
    issue_number: int
    issue_title: str
    agent_label: str
    worktree_path: str
    branch_name: str
    original_prompt: str | None
    validation_error: str
    validation_error_file: str | None
    retry_count: int  # Current retry count (will be incremented on re-launch)
    source_task: TaskKind
    validation_cmd: str | None = None  # For building retry prompt

    def __post_init__(self) -> None:
        if self.source_task.is_review_only:
            raise ValueError(
                "PendingValidationRetry cannot be created for review-only task "
                f"{self.source_task.value} (issue #{self.issue_number}): review-only "
                "sessions make no commits and must never enter the coder retry pipeline."
            )


# Backwards compatibility alias
PendingCTOReview = PendingTechLeadReview


@dataclass
class DependencyProblem:
    """A dependency problem for an issue (for web UI display)."""
    issue_number: int
    issue_title: str
    blocked_by: list[tuple[int, str, str]]  # [(dep_number, dep_title, state)]
    summary: str  # Human-readable summary


@dataclass
class OrchestratorState:
    """Persisted state of the orchestrator."""
    active_sessions: list[Session] = field(default_factory=list)
    completed_today: list[int] = field(default_factory=list)  # issue numbers (to migrate: set[IssueKey])
    failed_this_cycle: set[int] = field(default_factory=set)  # issues that failed since last refresh (prevent immediate retry)
    paused: bool = False
    priority_queue: list[int] = field(default_factory=list)  # manual priority overrides (to migrate: list[IssueKey])
    # Expedite lane bookkeeping (#6870), owned by RetryHistoryState. Both are
    # in-memory (like priority_queue itself): GitHub labels stay the crash-safe
    # source of truth, so a restart between file/approve and pickup simply drops
    # the intent and the issue is worked at normal priority (graceful, never
    # silently-wrong). ``tech_lead_expedited`` records which priority_queue
    # entries the tech lead placed, so the cap counts only tech-lead-expedited
    # issues (not operator/retry ones). ``tech_lead_expedite_pending`` holds
    # gated (propose-authority) create_issue follow-ups awaiting the
    # proposed-tech-lead gate removal, promoted to the front once un-gated.
    tech_lead_expedited: list[int] = field(default_factory=list)
    tech_lead_expedite_pending: list[int] = field(default_factory=list)
    # #6873: ledger of priority_queue entries the blocked->front policy owns.
    # Analogous to tech_lead_expedited (an unbounded restore lane rather than a
    # capped one), it lets the owner release these on successful launch and drop
    # them on re-block WITHOUT touching operator-owned priorities (the two are
    # disjoint by construction). In-memory like priority_queue itself.
    blocked_front_prioritized: list[int] = field(default_factory=list)
    session_history: list[SessionHistoryEntry] = field(default_factory=list)  # This session's history
    issues_started_count: int = 0  # Total issues started this session (for max_issues_to_start)
    pending_reviews: list[PendingReview] = field(default_factory=list)  # PRs waiting for code review
    pending_retrospective_reviews: list[PendingRetrospectiveReview] = field(default_factory=list)  # Existing implementations waiting for review
    pending_reworks: list[PendingRework] = field(default_factory=list)  # PRs needing rework after review
    pending_tech_lead_reviews: list["PendingTechLeadReview"] = field(default_factory=list)  # Tech Lead batch reviews waiting
    pending_cleanups: list[PendingCleanup] = field(default_factory=list)  # Sessions awaiting cleanup after review
    pending_validation_retries: list["PendingValidationRetry"] = field(default_factory=list)  # Sessions needing validation retry
    startup_status: str = "pending"  # "pending", "running", "complete"
    startup_message: str = ""  # Current startup task description
    cached_scope_issues: list["IssueProtocol"] = field(default_factory=list)  # Cached full in-scope issue snapshot for dashboard/runtime recovery
    cached_queue_issues: list["IssueProtocol"] = field(default_factory=list)  # Cached runnable queue for instant pagination
    queue_last_refresh_at: float = 0.0  # Unix timestamp of last queue refresh
    queue_last_network_sync_at: float = 0.0  # Unix timestamp of last network sync attempt
    queue_last_full_scan_at: float = 0.0  # Unix timestamp of last full GitHub scan
    queue_refresh_count: int = 0  # Number of queue refresh cycles completed
    queue_last_refresh_mode: str = "none"  # none|full|incremental
    queue_delta_watermark: str | None = None  # Last committed watermark for incremental delta sync
    issue_refresh_timestamps: dict[int, float] = field(default_factory=dict)  # issue_number -> unix timestamp of last confirmed refresh
    ui_visible_issue_numbers: list[int] = field(default_factory=list)  # Issue numbers currently visible in Flow UI
    ui_visible_updated_at: float = 0.0  # Unix timestamp when UI visibility hint was last updated
    dependency_problems: dict[int, "DependencyProblem"] = field(default_factory=dict)  # Issues blocked by dependencies (to migrate: dict[IssueKey, ...])
    # #6873: issue numbers the scheduler deemed blocked (blocking label OR
    # dependency gate) at the last dependency scan. When an issue leaves this
    # set AND is available again, it jumps to the front of the work queue — it
    # was already important enough to be in flight, so restoring it is prompt.
    # In-memory like ``priority_queue`` (GitHub labels stay the crash-safe
    # truth); a restart simply re-establishes the baseline on the next scan.
    previously_blocked_issue_numbers: set[int] = field(default_factory=set)
    dependency_gate_snapshot: DependencyGateSnapshot = field(default_factory=DependencyGateSnapshot)  # Producer-evaluated stack gate reports + successor edges for the UI (#6597)
    # Discovered facts pending Planner decision
    discovered_reviews: list[DiscoveredReview] = field(default_factory=list)  # Reviews from completions/scans
    discovered_retrospective_reviews: list[DiscoveredRetrospectiveReview] = field(default_factory=list)  # Existing implementation reviews from labels/UI
    discovered_awaiting_merge_reconciliations: list[DiscoveredAwaitingMergeReconciliation] = field(default_factory=list)  # Awaiting-merge history transitions from scans
    discovered_awaiting_merge_drifts: list[DiscoveredAwaitingMergeDrift] = field(default_factory=list)  # Open issues whose pr-pending label drifted from PR state
    discovered_reworks: list[DiscoveredRework] = field(default_factory=list)  # Reworks from scans
    discovered_escalations: list[DiscoveredEscalation] = field(default_factory=list)  # Escalations from scans
    discovered_awaiting_merge_escalations: list[DiscoveredAwaitingMergeEscalation] = field(default_factory=list)  # Post-publish stuck-or-blocked escalations
    discovered_merge_queue_enqueues: list[DiscoveredMergeQueueEnqueue] = field(default_factory=list)  # Approved PRs eligible for the merge queue
    discovered_failures: list["DiscoveredFailure"] = field(default_factory=list)  # Failures for tech_lead
    # Immediate cleanups - sessions that need cleanup now (not deferred until review)
    immediate_cleanups: list["ImmediateCleanup"] = field(default_factory=list)
    # Stale in-progress tracking: issue_number -> consecutive ticks with stale in-progress
    stale_issue_ticks: dict[int, int] = field(default_factory=dict)
    # Queue refresh/freshness tracking for dashboard UX and lazy refresh behavior
    queue_last_refresh_at: float = 0.0  # Epoch seconds of last queue refresh completion
    queue_refresh_in_progress: bool = False  # True while refresh is actively fetching from GitHub
    queue_refresh_requested: bool = False  # True when a manual refresh has been requested
    awaiting_merge_drift_scan_timestamps: dict[int, float] = field(default_factory=dict)  # issue_number -> last PR-list drift scan
    awaiting_merge_rollup_scan_timestamps: dict[int, float] = field(default_factory=dict)  # pr_number -> last status-rollup scan
    # Per-issue first time we observed `WAIT_FOR_CHECKS` (mergeable_state in
    # {unstable, blocked} with the status-check rollup not yet conclusive).
    # Used to bound how long the orchestrator is willing to wait for required
    # checks before escalating the issue to needs_human. Cleared whenever the
    # PR leaves the WAIT_FOR_CHECKS state.
    awaiting_merge_checks_pending_since: dict[int, float] = field(default_factory=dict)
    # Repo-wide backoff state for status-check-rollup reads. Bounds repeated
    # `status_check_rollup` permission failures so a token that cannot read
    # check status does not re-trigger the same GraphQL probe (and the same
    # warning) on every tick. See StatusRollupGate.
    status_rollup_capability: StatusRollupCapability = field(
        default_factory=StatusRollupCapability
    )
    # Candidate queue removals waiting for a targeted confirmation refresh.
    queue_pending_shrink_missing_issue_numbers: list[int] = field(default_factory=list)
    queue_pending_shrink_confirm_at: float = 0.0
    queue_pending_shrink_prior_count: int = 0  # Queue size before the pending shrink
    queue_pending_shrink_candidate_count: int = 0  # Queue size proposed by the pending shrink
    issue_last_refreshed_at: dict[int, float] = field(default_factory=dict)  # issue_number -> epoch seconds
    # Main-loop heartbeat — populated by run_tick. These let the view model
    # distinguish "refresh is old because GitHub hasn't been polled" from
    # "refresh is old because the main loop is stuck". A monotonically
    # increasing last_tick_completed_at is the authoritative signal that
    # the orchestrator is alive; a never-completed last_tick_started_at
    # alongside a stale completion time points to a phase that is blocking.
    last_tick_started_at: float = 0.0  # Epoch seconds; 0 if no tick has started
    last_tick_completed_at: float = 0.0  # Epoch seconds; 0 if no tick has completed
    current_tick_phase: str = ""  # Non-empty only while a tick is mid-flight
    # Periodic health review (ADR-0031 §4): epoch seconds when the last
    # health-review anchor issue was created; 0 if never. Written by the
    # health_review_trigger owner on successful anchor creation, hydrated at
    # startup from the queue-cache meta store so restarts do not double-fire.
    last_health_review_at: float = 0.0
    # Fingerprint of the reviewable board (blocked issues, active sessions +
    # their hung flags, pending-queue depths, cycle failures) as of the last
    # health review. The periodic trigger fires only when the interval has
    # elapsed AND this differs from the current board's fingerprint, so an idle
    # orchestrator does not re-walk an unchanged board (ADR-0031 §4). "" means
    # never reviewed / a fresh cache — which makes the next due review fire.
    last_reviewed_board_fingerprint: str = ""
    # Tech-lead attention sweep (#6823): epoch seconds of the last stuck-issue
    # sweep (0 = never), and the durable per-issue recovery-attempt counter that
    # bounds re-injection so an unrecoverable issue escalates instead of looping
    # forever. Both are hydrated at startup from the queue-cache meta store.
    last_stuck_sweep_at: float = 0.0
    recovery_attempts: dict[int, int] = field(default_factory=dict)
    # DURABLE set of issues whose recovery budget is exhausted and whose
    # needs-human escalation has NOT yet been acknowledged (the label observed
    # present) — persisted like ``recovery_attempts`` so an escalation survives a
    # crash or an apply failure and is retried until it lands (#6824 R1).
    pending_stuck_sweep_escalations: set[int] = field(default_factory=set)
    # Tick-scoped buffer seeded from the durable set each sweep: every unacked
    # escalation gets an idempotent, retry-safe needs-human label (the
    # authoritative, label-only escalation, #6824 R1).
    stuck_sweep_escalations: list[int] = field(default_factory=list)
    def retrospective_review_in_flight_issue_numbers(self) -> set[int]:
        """Issues already queued, discovered, or actively under retrospective review."""

        return (
            self.pending_or_active_retrospective_review_issue_numbers()
            | {review.issue_number for review in self.discovered_retrospective_reviews}
        )

    def pending_or_active_retrospective_review_issue_numbers(self) -> set[int]:
        """Issues already queued or actively under retrospective review."""

        return (
            {review.issue_number for review in self.pending_retrospective_reviews}
            | active_retrospective_review_issue_numbers(self.active_sessions)
        )

    def has_in_flight_retrospective_review(self, issue_number: int) -> bool:
        """Return true if a retrospective review is already in flight."""

        return issue_number in self.retrospective_review_in_flight_issue_numbers()

    def has_pending_or_active_retrospective_review(self, issue_number: int) -> bool:
        """Return true if a retrospective review is queued or running."""

        return issue_number in self.pending_or_active_retrospective_review_issue_numbers()

    def queue_pending_rework(self, rework: PendingRework) -> bool:
        """Queue coder rework if the issue is not already waiting for rework."""

        issue_number = rework.resolve_issue_number()
        if issue_number is not None and any(
            existing.resolve_issue_number() == issue_number
            for existing in self.pending_reworks
        ):
            return False
        self.pending_reworks.extend([rework])
        return True

    def record_discovered_failure(self, failure: DiscoveredFailure) -> None:
        """Record a session-failure fact for the Planner (owner boundary).

        ``discovered_failures`` is a per-tick fact buffer; producers record
        through this owner method rather than mutating the collection.
        """

        self.discovered_failures.extend([failure])

    def drop_active_session(self, terminal_id: str) -> bool:
        """Reconcile a terminated session out of ``active_sessions`` (owner method).

        Returns True when a record was dropped. Centralizes the collection
        mutation here in the state owner so callers (e.g. a timeout terminate)
        never reassign the shared ``active_sessions`` list directly (#6824 R7).
        """
        before = len(self.active_sessions)
        # In-place reconcile (mirrors the review-exchange lifecycle owner) so the
        # shared list object is never rebound out from under other holders.
        self.active_sessions[:] = [
            session
            for session in self.active_sessions
            if session.terminal_id != terminal_id
        ]
        return len(self.active_sessions) != before


@dataclass
class CommentHeadings:
    """Configurable headings for worker comments on issues.

    These headings structure the comments workers post, allowing
    correlation with tech_lead investigation comments and other tooling.
    """
    implementation: str = "## Implementation"
    problems: str = "## Problems Encountered"
    pr_link: str = "## Pull Request"
    blocked: str = "## Blocked"
    needs_human: str = "## Needs Human Input"

    def format_completion_comment(
        self,
        implementation: str,
        problems: str | None,
        pr_url: str,
    ) -> str:
        """Format a completion comment with all sections."""
        lines = [
            self.implementation,
            implementation,
            "",
            self.problems,
            problems or "None",
            "",
            self.pr_link,
            pr_url,
        ]
        return "\n".join(lines)

    def format_blocked_comment(self, reason: str) -> str:
        """Format a blocked comment."""
        return f"{self.blocked}\n{reason}"

    def format_needs_human_comment(self, question: str) -> str:
        """Format a needs-human comment."""
        return f"{self.needs_human}\n{question}"
