"""Entrypoint for running the orchestrator as a subprocess.

This module is invoked by the supervisor to start an orchestrator instance:

    python -m issue_orchestrator.entrypoints.run_orchestrator \
        --repo-root /path/to/repo \
        --port 8080

It handles:
- Acquiring the repository lock
- Building the orchestrator
- Running startup
- Starting the web dashboard
- Releasing the lock on exit
"""

import argparse
import asyncio
import atexit
import logging
import os
import signal
import sys
from pathlib import Path
from typing import Any


logger = logging.getLogger(__name__)
_EXPECTED_IDENTITY_ENV = "ISSUE_ORCHESTRATOR_EXPECTED_IDENTITY"


async def run_orchestrator(config_path: Path | None = None) -> None:
    """Run the legacy in-process entrypoint under the repository owner gate."""
    from ..control.orchestrator_support import handle_signal
    from ..infra.config import Config
    from ..infra.repo_lock import held_repo_lock
    from .bootstrap import build_orchestrator
    from .bootstrap_liveness import held_repo_validated_work_liveness

    config = Config.load(config_path) if config_path else Config.find_and_load()
    with held_repo_lock(config.repo_root):
        orchestrator = build_orchestrator(
            config,
            validated_work_liveness=held_repo_validated_work_liveness(config),
        )
        signal.signal(signal.SIGINT, lambda s, f: handle_signal(orchestrator, s, f))
        signal.signal(signal.SIGTERM, lambda s, f: handle_signal(orchestrator, s, f))
        await orchestrator.startup()
        await orchestrator.run_loop()


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Run the issue orchestrator for a repository"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        required=True,
        help="Repository root path",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8080,
        help="HTTP port for web dashboard (default: 8080)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        help="Path to config file (optional, will search if not provided)",
    )
    parser.add_argument(
        "--mode",
        default="default",
        help="Directory-backed configuration mode (default: default)",
    )
    parser.add_argument(
        "--log-level",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        default="INFO",
        help="Log level (default: INFO)",
    )
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Don't auto-open browser (used when started via control center)",
    )
    parser.add_argument(
        "--instance-id",
        type=str,
        default=None,
        help="Instance ID for multi-instance deployments (auto-generated by CC)",
    )
    parser.add_argument(
        "--start-paused",
        action="store_true",
        help="Start with planning/session launch paused while keeping the dashboard available",
    )
    parser.add_argument(
        "--dev-no-auth",
        action="store_true",
        help=(
            "DEVELOPMENT ONLY: disable Web Dashboard authentication. "
            "Any local process can mutate state. Also triggered by "
            "ISSUE_ORCHESTRATOR_DEV_NO_AUTH=1. Never use on a shared "
            "host or in production."
        ),
    )
    args = parser.parse_args()
    if os.environ.get("ISSUE_ORCHESTRATOR_DEV_NO_AUTH") == "1":
        args.dev_no_auth = True
    return args


def _build_repo_status_resolver():
    from ..execution.git_working_copy import GitWorkingCopy

    git = GitWorkingCopy()

    def _resolve_repo_status(root: Path) -> tuple[str | None, list[str]]:
        branch: str | None = None
        try:
            branch = git.get_current_branch(root)
        except Exception:
            branch = None
        dirty_lines = git.get_status_porcelain_lines(root)
        return branch, dirty_lines

    return _resolve_repo_status


def _assert_expected_identity(repo_root: Path) -> None:
    from ..infra.repo_identity import (
        build_repo_identity_with_status,
        deserialize_repo_identity,
        diff_repo_identity,
    )

    expected_identity_raw = os.environ.get(_EXPECTED_IDENTITY_ENV, "").strip()
    if not expected_identity_raw:
        return
    expected_identity = deserialize_repo_identity(expected_identity_raw)
    observed_identity = build_repo_identity_with_status(
        repo_root,
        status_resolver=_build_repo_status_resolver(),
    )
    mismatches = diff_repo_identity(expected_identity, observed_identity)
    if mismatches:
        raise RuntimeError(
            "Engine identity mismatch at startup: "
            f"{mismatches}. expected={expected_identity.to_dict()} observed={observed_identity.to_dict()}"
        )


def _load_config_for_instance(
    repo_root: Path,
    config_path: Path | None,
    instance_id: str | None,
    mode: str = "default",
):
    from ..infra.config import Config
    from ..infra.config_identity import (
        EXPECTED_CONFIG_FINGERPRINT_ENV,
        assert_expected_config_fingerprint,
    )
    from ..infra.config_paths import require_engine_launch_config_path

    if config_path:
        config_path = require_engine_launch_config_path(config_path)
        config = Config.load(config_path)
    else:
        config = Config.find_and_load(repo_root, mode=mode)
    if config.configuration_mode != mode:
        raise ValueError(
            "Selected mode does not match config path: "
            f"mode={mode!r} path_mode={config.configuration_mode!r}"
        )
    assert_expected_config_fingerprint(
        config.config_fingerprint,
        os.environ.get(EXPECTED_CONFIG_FINGERPRINT_ENV),
    )
    config.repo_root = repo_root
    if not instance_id:
        return config
    original_base = config.worktree_base
    config.worktree_base = original_base / instance_id
    logger.info("Worktree base set to instance-specific path: %s", config.worktree_base)
    if config.claims.enabled and not config.claims.claimant_id:
        config.claims = config.claims.__class__(
            enabled=config.claims.enabled,
            claimant_id=instance_id,
            lease_seconds=config.claims.lease_seconds,
            renew_before_expiry_seconds=config.claims.renew_before_expiry_seconds,
        )
        logger.info("Claimant ID set to instance ID: %s", instance_id)
    return config


def _install_shutdown_signal_handlers(
    orchestrator: Any,
    trigger_server_shutdown: Any,
) -> None:
    """Attach graceful shutdown to the signal consumer, recording the *real* sender.

    Signals are blocked process-wide and the consumer is started at the entry
    point (``block_shutdown_signals`` + ``begin_shutdown_watch`` in ``main``);
    now that the loop exists, this attaches the graceful callback so a signal
    runs ``orchestrator.request_shutdown()`` on the loop instead of forcing the
    startup-window exit. The consumer logs *who* sent the signal — its pid, uid,
    and resolved command line, via POSIX ``sigwaitinfo`` — replacing the old
    handler that could only log ``os.getppid()`` (the parent), which is not the
    sender and repeatedly misled diagnosis of external kills. On platforms that
    can't report the sender, an honest asyncio fallback is used. See
    ``infra.shutdown_signals``.
    """
    from ..infra.shutdown_signals import install_attributed_shutdown

    def _on_shutdown() -> None:
        orchestrator.request_shutdown()
        trigger_server_shutdown()

    install_attributed_shutdown(
        loop=asyncio.get_running_loop(),
        on_shutdown=_on_shutdown,
    )


async def run(
    repo_root: Path,
    port: int,
    config_path: Path | None,
    no_browser: bool = False,
    instance_id: str | None = None,
    start_paused: bool = False,
    dev_no_auth: bool = False,
    mode: str = "default",
) -> None:
    """Run the orchestrator with web dashboard.

    Args:
        repo_root: Repository root path
        port: HTTP port for web dashboard
        config_path: Optional path to config file
        no_browser: If True, don't auto-open browser
        instance_id: Optional instance ID for multi-instance deployments
        dev_no_auth: If True, disable dashboard auth (loopback only).
    """
    from ..entrypoints._auth_middleware import install_access_log_redaction
    from ..entrypoints.bootstrap import build_orchestrator
    from ..entrypoints.bootstrap_liveness import held_repo_validated_work_liveness
    from ..entrypoints.web import run_with_web_dashboard
    from ..infra.repo_lock import (
        acquire_lock,
        release_lock,
        touch_lock,
    )
    from .engine_startup import EngineStartup

    _assert_expected_identity(repo_root)

    config = _load_config_for_instance(repo_root, config_path, instance_id, mode)

    # Acquire the repository lock (instance-specific if multi-instance)
    instance_str = f" instance={instance_id}" if instance_id else ""
    logger.info("Acquiring lock for %s%s", repo_root, instance_str)
    lock_info = acquire_lock(
        repo_root,
        port,
        instance_id,
        configuration_mode=config.configuration_mode,
        config_name=config.config_name,
        config_fingerprint=config.config_fingerprint,
    )
    logger.info("Lock acquired: pid=%d, port=%s", lock_info.pid, lock_info.http_port)

    # Register cleanup on exit
    def cleanup():
        logger.info("Releasing lock for %s%s", repo_root, instance_str)
        release_lock(repo_root, instance_id=instance_id)

    atexit.register(cleanup)

    async def _heartbeat_loop() -> None:
        while True:
            touch_lock(repo_root, instance_id=instance_id)
            await asyncio.sleep(5.0)

    # Build the orchestrator before startup publishes anything, so auth
    # and the bound port land on the same agent-callback endpoint the
    # sessions it launches will read (#6924).
    logger.info("Building orchestrator...")
    orchestrator = build_orchestrator(
        config,
        validated_work_liveness=held_repo_validated_work_liveness(
            config, instance_id=instance_id
        ),
    )
    engine_startup = EngineStartup(
        callback_endpoint=orchestrator.deps.agent_callback_endpoint
    )
    # Auth is configured AFTER config is loaded so operator-set
    # ``ui.browser_session.*`` values take effect (#6041 re-review P2),
    # and BEFORE uvicorn binds so the first request already sees the
    # gate.
    engine_startup.configure_auth(dev_no_auth=dev_no_auth, config=config)
    install_access_log_redaction()
    _record_bound_port = engine_startup.server_started_hook(
        repo_root=repo_root, requested_port=port, instance_id=instance_id
    )
    if start_paused:
        orchestrator.set_start_paused()
        logger.info("Initial paused state applied before run loop")

    # Import here to avoid circular import at module level
    from .web import trigger_server_shutdown

    _install_shutdown_signal_handlers(orchestrator, trigger_server_shutdown)

    # Run with web dashboard
    logger.info("Starting orchestrator on port %d", port)
    heartbeat_task = asyncio.create_task(_heartbeat_loop(), name="repo-lock-heartbeat")
    try:
        await run_with_web_dashboard(
            orchestrator,
            port,
            open_browser=not no_browser,
            on_server_started=_record_bound_port,
        )
    finally:
        heartbeat_task.cancel()
        try:
            await heartbeat_task
        except asyncio.CancelledError:
            pass


def main() -> int:
    """Main entry point."""
    args = parse_args()

    # Configure logging
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Block SIGTERM/SIGINT process-wide BEFORE any thread is created, so the
    # dedicated sigwaitinfo consumer can read the *sender* of a shutdown signal.
    # Doing this here — the earliest point — ensures threads spawned during
    # orchestrator build inherit the block and can't take the signal first.
    # Then start the consumer IMMEDIATELY: blocking without a running consumer
    # would leave a signal delivered during config load / build_orchestrator()
    # pending, so a slow or hung startup couldn't be stopped with SIGTERM
    # (only SIGKILL). begin_shutdown_watch closes that window — a startup signal
    # is attributed and forces exit; run() later attaches graceful shutdown.
    # See infra.shutdown_signals.
    from ..infra.shutdown_signals import begin_shutdown_watch, block_shutdown_signals

    if block_shutdown_signals():
        begin_shutdown_watch()
        logger.debug(
            "Shutdown signals blocked; early sender-attributed watcher started"
        )

    # Change to repo root
    os.chdir(args.repo_root)

    try:
        asyncio.run(
            run(
                args.repo_root,
                args.port,
                args.config,
                args.no_browser,
                args.instance_id,
                args.start_paused,
                args.dev_no_auth,
                args.mode,
            )
        )
        return 0
    except Exception as e:
        logger.exception("Orchestrator failed: %s", e)
        return 1


if __name__ == "__main__":
    sys.exit(main())
