"""Entrypoint for running the orchestrator as a subprocess.

This module is invoked by the supervisor to start an orchestrator instance:

    python -m issue_orchestrator.entrypoints.run_orchestrator \
        --repo-root /path/to/repo \
        --port 8080

It handles:
- Acquiring the repository lock
- Building the orchestrator
- Running startup
- Starting the web dashboard
- Releasing the lock on exit
"""

import argparse
import asyncio
import atexit
import logging
import os
import sys
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)
_EXPECTED_IDENTITY_ENV = "ISSUE_ORCHESTRATOR_EXPECTED_IDENTITY"


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Run the issue orchestrator for a repository"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        required=True,
        help="Repository root path",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8080,
        help="HTTP port for web dashboard (default: 8080)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        help="Path to config file (optional, will search if not provided)",
    )
    parser.add_argument(
        "--log-level",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        default="INFO",
        help="Log level (default: INFO)",
    )
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Don't auto-open browser (used when started via control center)",
    )
    parser.add_argument(
        "--instance-id",
        type=str,
        default=None,
        help="Instance ID for multi-instance deployments (auto-generated by CC)",
    )
    parser.add_argument(
        "--start-paused",
        action="store_true",
        help="Start with planning/session launch paused while keeping the dashboard available",
    )
    parser.add_argument(
        "--dev-no-auth",
        action="store_true",
        help=(
            "DEVELOPMENT ONLY: disable Web Dashboard authentication. "
            "Any local process can mutate state. Also triggered by "
            "ISSUE_ORCHESTRATOR_DEV_NO_AUTH=1. Never use on a shared "
            "host or in production."
        ),
    )
    args = parser.parse_args()
    if os.environ.get("ISSUE_ORCHESTRATOR_DEV_NO_AUTH") == "1":
        args.dev_no_auth = True
    return args


def _build_repo_status_resolver():
    from ..execution.git_working_copy import GitWorkingCopy

    git = GitWorkingCopy()

    def _resolve_repo_status(root: Path) -> tuple[str | None, list[str]]:
        branch: str | None = None
        try:
            branch = git.get_current_branch(root)
        except Exception:
            branch = None
        dirty_lines = git.get_status_porcelain_lines(root)
        return branch, dirty_lines

    return _resolve_repo_status


def _assert_expected_identity(repo_root: Path) -> None:
    from ..infra.repo_identity import (
        build_repo_identity_with_status,
        deserialize_repo_identity,
        diff_repo_identity,
    )

    expected_identity_raw = os.environ.get(_EXPECTED_IDENTITY_ENV, "").strip()
    if not expected_identity_raw:
        return
    expected_identity = deserialize_repo_identity(expected_identity_raw)
    observed_identity = build_repo_identity_with_status(
        repo_root,
        status_resolver=_build_repo_status_resolver(),
    )
    mismatches = diff_repo_identity(expected_identity, observed_identity)
    if mismatches:
        raise RuntimeError(
            "Engine identity mismatch at startup: "
            f"{mismatches}. expected={expected_identity.to_dict()} observed={observed_identity.to_dict()}"
        )


def _load_config_for_instance(repo_root: Path, config_path: Path | None, instance_id: str | None):
    from ..infra.config import Config

    if config_path:
        config = Config.load(config_path)
    else:
        config = Config.find_and_load(repo_root)
    config.repo_root = repo_root
    if not instance_id:
        return config
    original_base = config.worktree_base
    config.worktree_base = original_base / instance_id
    logger.info("Worktree base set to instance-specific path: %s", config.worktree_base)
    if config.claims.enabled and not config.claims.claimant_id:
        config.claims = config.claims.__class__(
            enabled=config.claims.enabled,
            claimant_id=instance_id,
            lease_seconds=config.claims.lease_seconds,
            renew_before_expiry_seconds=config.claims.renew_before_expiry_seconds,
        )
        logger.info("Claimant ID set to instance ID: %s", instance_id)
    return config


def _configure_dashboard_auth(dev_no_auth: bool, config: Any) -> None:
    """Activate (or explicitly disable) dashboard auth before binding.

    Security #5987 F3 — PR 8. The same admin token is shared with the
    Control API so a single login covers both surfaces. ``config`` is
    the loaded ``Config`` instance; its ``browser_session_ttl_seconds``
    / ``sse_token_ttl_seconds`` / ``browser_session_max`` settings are
    threaded into ``browser_session.initialize`` so operator hardening
    under ``ui.browser_session.*`` applies to the dashboard too (#6041
    re-review P2). Without this, the dashboard silently fell back to
    the built-in defaults while the Control API honored the config —
    the same rule enforced differently by path.
    """
    from ..entrypoints.web import configure_dashboard_admin_token
    from ..infra import browser_session
    from ..infra.api_token import resolve_api_token

    session_ttl = getattr(config, "browser_session_ttl_seconds", None)
    sse_ttl = getattr(config, "sse_token_ttl_seconds", None)
    max_sessions = getattr(config, "browser_session_max", None)

    if dev_no_auth:
        logger.error(
            "⚠  Web Dashboard running with --dev-no-auth: authentication "
            "is DISABLED. Any local process can mutate state. DO NOT use "
            "on a shared host or in production."
        )
        print(
            "\n\033[1;31m"
            "⚠  AUTH DISABLED (--dev-no-auth). Any local process can "
            "mutate dashboard state. Dev only."
            "\033[0m\n",
            flush=True,
        )
        configure_dashboard_admin_token(None)
        os.environ.pop("ISSUE_ORCHESTRATOR_API_TOKEN", None)
        browser_session.initialize(
            session_ttl_seconds=session_ttl,
            sse_token_ttl_seconds=sse_ttl,
            max_sessions=max_sessions,
        )
        return
    admin_token = resolve_api_token()
    configure_dashboard_admin_token(admin_token)
    # Derive the HMAC secret from the admin token so a session cookie
    # minted by the Control Center on port 19080 validates here too —
    # one login covers both processes.
    browser_session.initialize(
        admin_token=admin_token,
        session_ttl_seconds=session_ttl,
        sse_token_ttl_seconds=sse_ttl,
        max_sessions=max_sessions,
    )
    os.environ.setdefault("ISSUE_ORCHESTRATOR_API_TOKEN", admin_token)


def _install_shutdown_signal_handlers(
    orchestrator: Any,
    trigger_server_shutdown: Any,
) -> None:
    """Attach graceful shutdown to the signal consumer, recording the *real* sender.

    Signals are blocked process-wide and the consumer is started at the entry
    point (``block_shutdown_signals`` + ``begin_shutdown_watch`` in ``main``);
    now that the loop exists, this attaches the graceful callback so a signal
    runs ``orchestrator.request_shutdown()`` on the loop instead of forcing the
    startup-window exit. The consumer logs *who* sent the signal — its pid, uid,
    and resolved command line, via POSIX ``sigwaitinfo`` — replacing the old
    handler that could only log ``os.getppid()`` (the parent), which is not the
    sender and repeatedly misled diagnosis of external kills. On platforms that
    can't report the sender, an honest asyncio fallback is used. See
    ``infra.shutdown_signals``.
    """
    from ..infra.shutdown_signals import install_attributed_shutdown

    def _on_shutdown() -> None:
        orchestrator.request_shutdown()
        trigger_server_shutdown()

    install_attributed_shutdown(
        loop=asyncio.get_running_loop(),
        on_shutdown=_on_shutdown,
    )


async def run(
    repo_root: Path,
    port: int,
    config_path: Path | None,
    no_browser: bool = False,
    instance_id: str | None = None,
    start_paused: bool = False,
    dev_no_auth: bool = False,
) -> None:
    """Run the orchestrator with web dashboard.

    Args:
        repo_root: Repository root path
        port: HTTP port for web dashboard
        config_path: Optional path to config file
        no_browser: If True, don't auto-open browser
        instance_id: Optional instance ID for multi-instance deployments
        dev_no_auth: If True, disable dashboard auth (loopback only).
    """
    from ..entrypoints._auth_middleware import install_access_log_redaction
    from ..entrypoints.bootstrap import build_orchestrator
    from ..entrypoints.web import run_with_web_dashboard
    from ..infra.repo_lock import acquire_lock, release_lock, set_lock_http_port, touch_lock

    _assert_expected_identity(repo_root)

    # Acquire the repository lock (instance-specific if multi-instance)
    instance_str = f" instance={instance_id}" if instance_id else ""
    logger.info("Acquiring lock for %s%s", repo_root, instance_str)
    lock_info = acquire_lock(repo_root, port, instance_id)
    logger.info("Lock acquired: pid=%d, port=%s", lock_info.pid, lock_info.http_port)

    # Register cleanup on exit
    def cleanup():
        logger.info("Releasing lock for %s%s", repo_root, instance_str)
        release_lock(repo_root, instance_id=instance_id)

    atexit.register(cleanup)

    async def _heartbeat_loop() -> None:
        while True:
            touch_lock(repo_root, instance_id=instance_id)
            await asyncio.sleep(5.0)

    def _record_bound_port(actual_port: int) -> None:
        if actual_port != port:
            set_lock_http_port(repo_root, actual_port, instance_id=instance_id)
            logger.info("Updated lock with actual bound port %d", actual_port)

    config = _load_config_for_instance(repo_root, config_path, instance_id)

    # Configure dashboard auth AFTER config is loaded so operator-set
    # ``ui.browser_session.*`` values take effect on this surface
    # (#6041 re-review P2). Run before uvicorn binds so the first
    # request already sees the gate.
    _configure_dashboard_auth(dev_no_auth, config)
    install_access_log_redaction()

    # Build orchestrator
    logger.info("Building orchestrator...")
    orchestrator = build_orchestrator(config)
    if start_paused:
        orchestrator.set_start_paused()
        logger.info("Initial paused state applied before run loop")

    # Import here to avoid circular import at module level
    from .web import trigger_server_shutdown

    _install_shutdown_signal_handlers(orchestrator, trigger_server_shutdown)

    # Run with web dashboard
    logger.info("Starting orchestrator on port %d", port)
    heartbeat_task = asyncio.create_task(_heartbeat_loop(), name="repo-lock-heartbeat")
    try:
        await run_with_web_dashboard(
            orchestrator,
            port,
            open_browser=not no_browser,
            on_server_started=_record_bound_port,
        )
    finally:
        heartbeat_task.cancel()
        try:
            await heartbeat_task
        except asyncio.CancelledError:
            pass


def main() -> int:
    """Main entry point."""
    args = parse_args()

    # Configure logging
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Block SIGTERM/SIGINT process-wide BEFORE any thread is created, so the
    # dedicated sigwaitinfo consumer can read the *sender* of a shutdown signal.
    # Doing this here — the earliest point — ensures threads spawned during
    # orchestrator build inherit the block and can't take the signal first.
    # Then start the consumer IMMEDIATELY: blocking without a running consumer
    # would leave a signal delivered during config load / build_orchestrator()
    # pending, so a slow or hung startup couldn't be stopped with SIGTERM
    # (only SIGKILL). begin_shutdown_watch closes that window — a startup signal
    # is attributed and forces exit; run() later attaches graceful shutdown.
    # See infra.shutdown_signals.
    from ..infra.shutdown_signals import begin_shutdown_watch, block_shutdown_signals
    if block_shutdown_signals():
        begin_shutdown_watch()
        logger.debug("Shutdown signals blocked; early sender-attributed watcher started")

    # Change to repo root
    os.chdir(args.repo_root)

    try:
        asyncio.run(run(
            args.repo_root,
            args.port,
            args.config,
            args.no_browser,
            args.instance_id,
            args.start_paused,
            args.dev_no_auth,
        ))
        return 0
    except Exception as e:
        logger.exception("Orchestrator failed: %s", e)
        return 1


if __name__ == "__main__":
    sys.exit(main())
