"""Data models for issue-orchestrator."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Optional

# Marker used in PR bodies to identify orchestrator-generated PRs
ORCHESTRATOR_PR_MARKER = "Generated by issue-orchestrator"


class SessionStatus(Enum):
    """Status of a Claude session."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    BLOCKED = "blocked"
    NEEDS_HUMAN = "needs_human"
    FAILED = "failed"
    TIMED_OUT = "timed_out"


class IssueStatus(Enum):
    """Status of an issue in the queue."""
    AVAILABLE = "available"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    NEEDS_HUMAN = "needs_human"
    COMPLETED = "completed"


@dataclass
class Issue:
    """A GitHub issue."""
    number: int
    title: str
    labels: list[str]
    state: str = "open"  # "open" or "closed"
    milestone: Optional[str] = None
    body: Optional[str] = None
    milestone_number: Optional[int] = None
    milestone_due_on: Optional[str] = None  # ISO date string

    @property
    def agent_type(self) -> Optional[str]:
        """Extract agent type from labels (e.g., 'agent:web')."""
        for label in self.labels:
            if label.startswith("agent:"):
                return label
        return None

    @property
    def priority(self) -> int:
        """Extract priority (lower = higher priority)."""
        if "priority:high" in self.labels:
            return 1
        elif "priority:medium" in self.labels:
            return 2
        elif "priority:low" in self.labels:
            return 3
        return 4

    @property
    def is_blocked(self) -> bool:
        """Check if issue has the 'blocked' label.

        Blocked is a MODIFIER label that coexists with in-progress.
        An issue can be both in-progress AND blocked - this means:
        - We maintain ownership/claim on the issue
        - Work is paused waiting for a blocker to be resolved
        - When blocked is removed, work resumes immediately

        Blocked does NOT release the in-progress claim.
        """
        return "blocked" in self.labels

    @property
    def is_in_progress(self) -> bool:
        """Check if issue has the 'in-progress' label.

        In-progress is an OWNERSHIP label indicating we are actively working
        on or have claimed this issue. The label persists until:
        - Work is completed and PR is created (COMPLETED status)
        - Work fails unrecoverably (FAILED status)
        - Work times out (TIMED_OUT status)

        The label is NOT removed for:
        - BLOCKED status - we keep the claim while waiting for blocker
        - NEEDS_HUMAN status - we keep the claim while waiting for input

        This ensures we can immediately resume work when blockers are resolved.
        """
        return "in-progress" in self.labels

    @property
    def needs_human(self) -> bool:
        """Check if issue has the 'needs-human' label.

        Needs-human is a MODIFIER label that coexists with in-progress.
        An issue can be both in-progress AND needs-human - this means:
        - We maintain ownership/claim on the issue
        - Work is paused waiting for human input/decision
        - When needs-human is removed (human provided input), work resumes

        Needs-human does NOT release the in-progress claim.
        """
        return "needs-human" in self.labels


@dataclass
class AgentConfig:
    """Configuration for an agent type."""
    prompt_path: Path
    worktree_base: Path
    model: str = "sonnet"
    timeout_minutes: int = 45
    repo_root: Optional[Path] = None  # Per-agent repo root override
    # Permission mode for Claude CLI: default, acceptEdits, bypassPermissions, plan, dontAsk
    permission_mode: str = "default"
    # Skip code review for this agent (e.g., domain-expert agents that don't produce code)
    skip_review: bool = False
    # Command template - {initial_prompt} is passed as positional arg to claude
    command: str = "claude --permission-mode {permission_mode} --model {model} --append-system-prompt 'Read {prompt} for your instructions.' '{initial_prompt}'"
    initial_prompt: str = "Work on issue #{issue_number}: {issue_title}. Follow the instructions in {prompt}. When done, exit with /exit."

    def get_command(
        self,
        issue_number: int,
        issue_title: str,
        worktree: Path,
        pr_number: Optional[int] = None,
        existing_work: Optional[str] = None,
    ) -> str:
        """Render the command template with actual values, including initial prompt.

        Args:
            issue_number: The GitHub issue number
            issue_title: The issue title
            worktree: Path to the worktree
            pr_number: Optional PR number (for review agents). If a prompt template
                       uses {pr_number} but this is not provided, a KeyError is raised.
            existing_work: Optional context about existing commits in the worktree.
                          If provided, prepended to prompt so agent knows to complete vs restart.
        """
        # Build format kwargs - pr_number only included if provided (fail-fast if used but missing)
        format_kwargs = {
            "issue_number": issue_number,
            "issue_title": issue_title,
            "prompt": self.prompt_path,
            "worktree": worktree,
            "model": self.model,
            "permission_mode": self.permission_mode,
        }
        if pr_number is not None:
            format_kwargs["pr_number"] = pr_number

        # First render the initial prompt
        rendered_prompt = self.initial_prompt.format(**format_kwargs)

        # Prepend existing work context if provided
        if existing_work:
            rendered_prompt = f"IMPORTANT: {existing_work}\n\n{rendered_prompt}"

        # Escape single quotes in the prompt for shell safety
        escaped_prompt = rendered_prompt.replace("'", "'\\''")

        # Then render the full command with the prompt included
        format_kwargs["initial_prompt"] = escaped_prompt
        return self.command.format(**format_kwargs)


@dataclass
class Session:
    """A running Claude session working on an issue."""
    issue: Issue
    agent_config: AgentConfig
    tmux_session_name: str
    worktree_path: Path
    branch_name: str
    started_at: datetime = field(default_factory=datetime.now)
    status: SessionStatus = SessionStatus.RUNNING
    exit_sent: bool = False  # Track if we've already sent /exit

    @property
    def runtime_minutes(self) -> int:
        """How long this session has been running."""
        delta = datetime.now() - self.started_at
        return int(delta.total_seconds() / 60)

    @property
    def is_timed_out(self) -> bool:
        """Check if session exceeded timeout."""
        return self.runtime_minutes > self.agent_config.timeout_minutes


@dataclass
class SessionHistoryEntry:
    """Record of a completed session."""
    issue_number: int
    title: str
    agent_type: str
    status: str  # "completed", "failed", "blocked", "needs_human", "timed_out"
    runtime_minutes: int
    pr_url: Optional[str] = None  # Set if PR was created
    status_reason: Optional[str] = None  # Human-readable explanation of status


@dataclass
class PendingReview:
    """A PR queued for code review."""
    issue_number: int
    pr_number: int
    pr_url: str
    branch_name: str


@dataclass
class PendingRework:
    """A PR that needs rework after review requested changes."""
    issue_number: int
    pr_number: int
    pr_url: str
    branch_name: str
    rework_cycle: int = 1  # Which rework iteration this is (1, 2, etc.)


@dataclass
class OrchestratorState:
    """Persisted state of the orchestrator."""
    active_sessions: list[Session] = field(default_factory=list)
    completed_today: list[int] = field(default_factory=list)  # issue numbers
    paused: bool = False
    priority_queue: list[int] = field(default_factory=list)  # manual priority overrides
    session_history: list[SessionHistoryEntry] = field(default_factory=list)  # This session's history
    issues_started_count: int = 0  # Total issues started this session (for max_issues_to_start)
    pending_reviews: list[PendingReview] = field(default_factory=list)  # PRs waiting for code review
    pending_reworks: list[PendingRework] = field(default_factory=list)  # PRs needing rework after review
    startup_status: str = "pending"  # "pending", "running", "complete"
    startup_message: str = ""  # Current startup task description
    cached_queue_issues: list["Issue"] = field(default_factory=list)  # Cached queue for instant pagination


@dataclass
class CommentHeadings:
    """Configurable headings for worker comments on issues.

    These headings structure the comments workers post, allowing
    correlation with CTO investigation comments and other tooling.
    """
    implementation: str = "## Implementation"
    problems: str = "## Problems Encountered"
    pr_link: str = "## Pull Request"
    blocked: str = "## Blocked"
    needs_human: str = "## Needs Human Input"

    def format_completion_comment(
        self,
        implementation: str,
        problems: str | None,
        pr_url: str,
    ) -> str:
        """Format a completion comment with all sections."""
        lines = [
            self.implementation,
            implementation,
            "",
            self.problems,
            problems or "None",
            "",
            self.pr_link,
            pr_url,
        ]
        return "\n".join(lines)

    def format_blocked_comment(self, reason: str) -> str:
        """Format a blocked comment."""
        return f"{self.blocked}\n{reason}"

    def format_needs_human_comment(self, question: str) -> str:
        """Format a needs-human comment."""
        return f"{self.needs_human}\n{question}"
