"""Guardrail checks for doctor."""

import os
from pathlib import Path
from typing import Optional

from ..types import Check
from ...config import Config
from ....ports.command_runner import CommandRunner


def _check_guardrails_in_worktree(
    repo_root: Path,
    runner: CommandRunner,
    worktree_base: str = "../",
) -> list[Check]:
    from ....adapters.worktree._worktree import create_worktree

    checks: list[Check] = []
    worktree_path: Optional[Path] = None
    branch_name: Optional[str] = None

    try:
        worktree_path, branch_name, _, _, _, _, _ = create_worktree(
            repo_root=repo_root,
            issue_number=0,
            issue_title="doctor-guardrail-test",
            worktree_base=Path(worktree_base),
        )

        checks.append(Check(
            name="Test Worktree",
            status="ok",
            detail=f"Created at {worktree_path}",
        ))
        checks.append(Check(
            name="Git/GH Guardrails",
            status="ok",
            detail="Worktree checks executed",
        ))

        wrapper_dir = Path(__file__).resolve().parents[3] / "scripts"
        env = os.environ.copy()
        env["PATH"] = f"{wrapper_dir}:{env.get('PATH', '')}"
        env.pop("ORCHESTRATOR_GH_AUTH", None)

        def test_blocked(cmd: list[str], name: str, detail_ok: str, detail_fail: str) -> Check:
            result = runner.run(
                cmd,
                cwd=worktree_path,
                env=env,
                timeout_seconds=5,
            )
            if result.timed_out:
                return Check(name=name, status="warning", detail="Check timed out")
            if "BLOCKED" in result.stderr:
                return Check(name=name, status="ok", detail=detail_ok)
            debug_info = f"rc={result.returncode}, stderr={result.stderr[:200] if result.stderr else 'empty'}"
            return Check(name=name, status="error", detail=f"{detail_fail} [{debug_info}]")

        checks.append(test_blocked(
            ["git", "push"],
            "Git Push Guard",
            "git push correctly blocked",
            "git push was NOT blocked - guardrail failed",
        ))

        checks.append(test_blocked(
            ["gh", "pr", "create", "--title", "[DOCTOR-CHECK] DO NOT MERGE", "--body",
             "Auto-generated by doctor guardrail check - if you see this PR, the guardrail failed"],
            "GH PR Create Guard",
            "gh pr create correctly blocked",
            "gh pr create was NOT blocked - guardrail failed",
        ))

        checks.append(test_blocked(
            ["gh", "pr", "review", "1", "--approve"],
            "GH PR Review Guard",
            "gh pr review correctly blocked",
            "gh pr review was NOT blocked - guardrail failed",
        ))

        checks.append(test_blocked(
            ["gh", "api", "/user"],
            "GH API Guard",
            "gh api correctly blocked",
            "gh api was NOT blocked - guardrail failed",
        ))

        checks.append(test_blocked(
            ["gh", "issue", "create", "--title", "[DOCTOR-CHECK] DO NOT CREATE", "--body",
             "Auto-generated by doctor guardrail check - if you see this issue, the guardrail failed"],
            "GH Issue Create Guard",
            "gh issue create correctly blocked",
            "gh issue create was NOT blocked - guardrail failed",
        ))

        result = runner.run(
            ["agent-done", "--help"],
            cwd=worktree_path,
            env=env,
            timeout_seconds=5,
        )
        if result.returncode == 0:
            checks.append(Check(
                name="agent-done Available",
                status="ok",
                detail="agent-done command found",
            ))
        elif "not found" in result.stderr.lower() or "no such file" in result.stderr.lower():
            checks.append(Check(
                name="agent-done Available",
                status="error",
                detail="agent-done command not found in PATH",
            ))
        else:
            checks.append(Check(
                name="agent-done Available",
                status="error",
                detail=f"agent-done command not working: {result.stderr[:100]}",
            ))

        from ....control.isolation import build_isolation_prefix

        isolation_script = build_isolation_prefix(
            worktree=worktree_path,
            isolation_mode="standard",
            scrub_env=True,
            isolate_home=False,
        )

        try:
            real_gh = None
            for gh_path in ["/opt/homebrew/bin/gh", "/usr/local/bin/gh", "/usr/bin/gh"]:
                if os.path.isfile(gh_path) and os.access(gh_path, os.X_OK):
                    real_gh = gh_path
                    break

            if real_gh is None:
                checks.append(Check(
                    name="GH Auth Bypass Test",
                    status="warning",
                    detail="Could not find real gh binary to test",
                ))
            else:
                bypass_script = f"{isolation_script} && {real_gh} auth status 2>&1"
                result = runner.run(
                    f"bash -c '{bypass_script}'",
                    cwd=worktree_path,
                    env=os.environ.copy(),
                    timeout_seconds=10,
                    shell=True,
                )
                output = result.stdout + result.stderr
                if "Logged in" in output or "Active account" in output:
                    checks.append(Check(
                        name="GH Auth Bypass Test",
                        status="error",
                        detail=f"BYPASS: {real_gh} auth succeeded!",
                    ))
                else:
                    checks.append(Check(
                        name="GH Auth Bypass Test",
                        status="ok",
                        detail="Real gh cannot authenticate after scrubbing",
                    ))
        except Exception as e:
            checks.append(Check(
                name="GH Auth Bypass Test",
                status="warning",
                detail=f"Error: {e}",
            ))

        try:
            real_git = None
            for git_path in ["/opt/homebrew/bin/git", "/usr/local/bin/git", "/usr/bin/git"]:
                if os.path.isfile(git_path) and os.access(git_path, os.X_OK):
                    real_git = git_path
                    break

            if real_git is None:
                checks.append(Check(
                    name="Git Push Bypass Test",
                    status="warning",
                    detail="Could not find real git binary to test",
                ))
            else:
                bypass_script = f"{isolation_script} && {real_git} push --dry-run 2>&1 || true"
                result = runner.run(
                    f"bash -c '{bypass_script}'",
                    cwd=worktree_path,
                    env=os.environ.copy(),
                    timeout_seconds=10,
                    shell=True,
                )
                output = result.stdout + result.stderr
                if "Everything up-to-date" in output or "->" in output.lower():
                    checks.append(Check(
                        name="Git Push Bypass Test",
                        status="error",
                        detail=f"BYPASS: {real_git} push succeeded!",
                    ))
                elif any(x in output.lower() for x in ["authentication", "permission denied", "fatal:", "could not read"]):
                    checks.append(Check(
                        name="Git Push Bypass Test",
                        status="ok",
                        detail="Real git push blocked (no credentials)",
                    ))
                else:
                    checks.append(Check(
                        name="Git Push Bypass Test",
                        status="ok",
                        detail="Real git push failed (expected)",
                    ))
        except Exception as e:
            checks.append(Check(
                name="Git Push Bypass Test",
                status="warning",
                detail=f"Error: {e}",
            ))

    except Exception as e:
        checks.append(Check(
            name="Test Worktree",
            status="error",
            detail=f"Failed to create: {e}",
        ))
    finally:
        if worktree_path and worktree_path.exists():
            try:
                runner.run(
                    ["git", "worktree", "remove", "--force", str(worktree_path)],
                    cwd=repo_root,
                )
                if branch_name:
                    runner.run(
                        ["git", "branch", "-D", branch_name],
                        cwd=repo_root,
                    )
            except Exception:
                pass

    return checks


def check_guardrails(config: Config, runner: CommandRunner | None) -> list[Check]:
    checks: list[Check] = []
    if not config.repo:
        return checks
    if runner is None:
        return [Check(
            name="Git/GH Guardrails",
            status="info",
            detail="Skipped (no CommandRunner provided)",
        )]

    repo_root = Path.cwd()
    worktree_base = str(config.worktree_base) if config.worktree_base else "../"
    return _check_guardrails_in_worktree(repo_root, runner, worktree_base)
