"""Guardrail checks for doctor."""

import os
import sys
from pathlib import Path
from typing import Optional

from ..types import Check
from ...config import Config
from ....ports.command_runner import CommandRunner


def check_guardrails_in_worktree_impl(
    worktree_path: Path,
    runner: CommandRunner,
) -> list[Check]:
    """Run guardrail checks in an existing worktree.

    Args:
        worktree_path: Path to the test worktree
        runner: CommandRunner for executing test commands

    Returns list of Check results for each guardrail tested.
    """
    checks: list[Check] = []

    # Build the PATH as agents see it (wrapper dir prepended)
    wrapper_dir = Path(__file__).resolve().parents[3] / "scripts"
    active_python_bin = Path(sys.executable).parent
    env = os.environ.copy()
    path_entries = [str(wrapper_dir), str(active_python_bin)]
    resolved_python_bin = Path(sys.executable).resolve().parent
    if resolved_python_bin != active_python_bin:
        path_entries.append(str(resolved_python_bin))
    env["PATH"] = ":".join(path_entries + [env.get("PATH", "")])
    env.pop("ORCHESTRATOR_GH_AUTH", None)  # Ensure no auth token

    # Run git command guards (blocked by wrapper scripts)
    checks.extend(_check_git_guards(worktree_path, runner, env))

    # Run gh CLI guards (blocked by wrappers or gh_guard)
    checks.extend(_check_gh_guards(worktree_path, runner, env))

    # Check completion command availability
    checks.extend(_check_completion_commands_available(worktree_path, runner, env))

    # Run bypass tests
    checks.extend(_check_bypass_tests(worktree_path, runner))

    return checks


def _check_git_guards(
    worktree_path: Path,
    runner: CommandRunner,
    env: dict,
) -> list[Check]:
    """Check that git commands are blocked by wrapper scripts.

    Wrapper scripts output "BLOCKED" when they catch dangerous commands.
    """

    def is_blocked(stderr: str) -> bool:
        return "BLOCKED" in stderr

    def test_blocked(cmd: list[str], name: str, detail_ok: str, detail_fail: str) -> Check:
        result = runner.run(
            cmd,
            cwd=worktree_path,
            env=env,
            timeout_seconds=5,
        )
        if result.timed_out:
            return Check(name=name, status="warning", detail="Check timed out")
        if is_blocked(result.stderr):
            return Check(name=name, status="ok", detail=detail_ok)
        debug_info = f"rc={result.returncode}, stderr={result.stderr[:200] if result.stderr else 'empty'}"
        return Check(name=name, status="error", detail=f"{detail_fail} [{debug_info}]")

    return [
        test_blocked(
            ["git", "push"],
            "Git Push Guard",
            "git push correctly blocked",
            "git push was NOT blocked - guardrail failed",
        ),
    ]


def _check_gh_guards(
    worktree_path: Path,
    runner: CommandRunner,
    env: dict,
) -> list[Check]:
    """Check that gh CLI commands are blocked.

    GH commands can be blocked by two mechanisms:
    1. Wrapper scripts (output "BLOCKED")
    2. Python-level gh_guard when running in orchestrator process

    Both are valid blocking mechanisms.
    """
    # gh_guard's specific error message (see execution/gh_guard.py)
    GH_GUARD_MESSAGE = "Direct gh invocation is forbidden"

    def is_blocked(stderr: str) -> bool:
        # Wrappers say "BLOCKED", gh_guard has specific message
        # Don't just check for "forbidden" - that could match GitHub 403 responses
        return "BLOCKED" in stderr or GH_GUARD_MESSAGE in stderr

    def test_blocked(cmd: list[str], name: str, detail_ok: str, detail_fail: str) -> Check:
        result = runner.run(
            cmd,
            cwd=worktree_path,
            env=env,
            timeout_seconds=5,
        )
        if result.timed_out:
            return Check(name=name, status="warning", detail="Check timed out")
        if is_blocked(result.stderr):
            return Check(name=name, status="ok", detail=detail_ok)
        debug_info = f"rc={result.returncode}, stderr={result.stderr[:200] if result.stderr else 'empty'}"
        return Check(name=name, status="error", detail=f"{detail_fail} [{debug_info}]")

    return [
        test_blocked(
            ["gh", "pr", "create", "--title", "[DOCTOR-CHECK] DO NOT MERGE", "--body",
             "Auto-generated by doctor guardrail check - if you see this PR, the guardrail failed"],
            "GH PR Create Guard",
            "gh pr create correctly blocked",
            "gh pr create was NOT blocked - guardrail failed",
        ),
        test_blocked(
            ["gh", "pr", "review", "1", "--approve"],
            "GH PR Review Guard",
            "gh pr review correctly blocked",
            "gh pr review was NOT blocked - guardrail failed",
        ),
        test_blocked(
            ["gh", "api", "/user"],
            "GH API Guard",
            "gh api correctly blocked",
            "gh api was NOT blocked - guardrail failed",
        ),
        test_blocked(
            ["gh", "issue", "create", "--title", "[DOCTOR-CHECK] DO NOT CREATE", "--body",
             "Auto-generated by doctor guardrail check - if you see this issue, the guardrail failed"],
            "GH Issue Create Guard",
            "gh issue create correctly blocked",
            "gh issue create was NOT blocked - guardrail failed",
        ),
    ]


def _check_completion_commands_available(
    worktree_path: Path,
    runner: CommandRunner,
    env: dict,
) -> list[Check]:
    """Check that coding-done and reviewer-done commands are available."""
    checks: list[Check] = []
    for cmd_name in ("coding-done", "reviewer-done"):
        result = runner.run(
            [cmd_name, "--help"],
            cwd=worktree_path,
            env=env,
            timeout_seconds=5,
        )
        if result.returncode == 0:
            checks.append(Check(
                name=f"{cmd_name} Available",
                status="ok",
                detail=f"{cmd_name} command found",
            ))
        elif "not found" in result.stderr.lower() or "no such file" in result.stderr.lower():
            checks.append(Check(
                name=f"{cmd_name} Available",
                status="error",
                detail=f"{cmd_name} command not found in PATH",
            ))
        else:
            checks.append(Check(
                name=f"{cmd_name} Available",
                status="error",
                detail=f"{cmd_name} command not working: {result.stderr[:100]}",
            ))
    return checks


def _check_bypass_tests(
    worktree_path: Path,
    runner: CommandRunner,
) -> list[Check]:
    """Test that real binaries cannot bypass guardrails after env scrubbing."""
    checks: list[Check] = []

    from ....control.isolation import build_isolation_prefix

    isolation_script = build_isolation_prefix(
        worktree=worktree_path,
        isolation_mode="standard",
        scrub_env=True,
        isolate_home=False,
    )

    # Test gh auth bypass
    checks.append(_check_gh_auth_bypass(worktree_path, runner, isolation_script))

    # Test git push bypass
    checks.append(_check_git_push_bypass(worktree_path, runner, isolation_script))

    return checks


def _find_binary(candidates: list[str]) -> Optional[str]:
    """Find first executable binary from candidates."""
    for path in candidates:
        if os.path.isfile(path) and os.access(path, os.X_OK):
            return path
    return None


def _check_gh_auth_bypass(
    worktree_path: Path,
    runner: CommandRunner,
    isolation_script: str,
) -> Check:
    """Test that real gh binary cannot authenticate after env scrubbing."""
    try:
        real_gh = _find_binary(["/opt/homebrew/bin/gh", "/usr/local/bin/gh", "/usr/bin/gh"])

        if real_gh is None:
            return Check(
                name="GH Auth Bypass Test",
                status="warning",
                detail="Could not find real gh binary to test",
            )

        bypass_script = f"{isolation_script} && {real_gh} auth status 2>&1"
        result = runner.run(
            f"bash -c '{bypass_script}'",
            cwd=worktree_path,
            env=os.environ.copy(),
            timeout_seconds=10,
            shell=True,
        )
        output = result.stdout + result.stderr
        if "Logged in" in output or "Active account" in output:
            return Check(
                name="GH Auth Bypass Test",
                status="error",
                detail=f"BYPASS: {real_gh} auth succeeded!",
            )
        return Check(
            name="GH Auth Bypass Test",
            status="ok",
            detail="Real gh cannot authenticate after scrubbing",
        )
    except Exception as e:
        return Check(
            name="GH Auth Bypass Test",
            status="warning",
            detail=f"Error: {e}",
        )


def _check_git_push_bypass(
    worktree_path: Path,
    runner: CommandRunner,
    isolation_script: str,
) -> Check:
    """Test that real git binary cannot push after env scrubbing."""
    try:
        real_git = _find_binary(["/opt/homebrew/bin/git", "/usr/local/bin/git", "/usr/bin/git"])

        if real_git is None:
            return Check(
                name="Git Push Bypass Test",
                status="warning",
                detail="Could not find real git binary to test",
            )

        bypass_script = f"{isolation_script} && {real_git} push --dry-run 2>&1 || true"
        result = runner.run(
            f"bash -c '{bypass_script}'",
            cwd=worktree_path,
            env=os.environ.copy(),
            timeout_seconds=10,
            shell=True,
        )
        output = result.stdout + result.stderr

        # Success indicators (push worked - bad!)
        if "Everything up-to-date" in output or "->" in output.lower():
            return Check(
                name="Git Push Bypass Test",
                status="error",
                detail=f"BYPASS: {real_git} push succeeded!",
            )

        # Failure indicators (good - credentials blocked)
        if any(x in output.lower() for x in ["authentication", "permission denied", "fatal:", "could not read"]):
            return Check(
                name="Git Push Bypass Test",
                status="ok",
                detail="Real git push blocked (no credentials)",
            )

        # No upstream might be ok too
        return Check(
            name="Git Push Bypass Test",
            status="ok",
            detail="Real git push failed (expected)",
        )
    except Exception as e:
        return Check(
            name="Git Push Bypass Test",
            status="warning",
            detail=f"Error: {e}",
        )


def check_guardrails(config: Config, runner: CommandRunner | None) -> list[Check]:
    """Run guardrails check from config."""
    checks: list[Check] = []
    if not config.repo:
        return checks
    if runner is None:
        return [Check(
            name="Git/GH Guardrails",
            status="info",
            detail="Skipped (no CommandRunner provided)",
        )]

    repo_root = config.repo_root
    worktree_base = str(config.worktree_base) if config.worktree_base else "../"
    return _check_guardrails_in_worktree(
        repo_root,
        runner,
        worktree_base,
        base_branch=config.worktree_base_branch_override,
    )


def _check_guardrails_in_worktree(
    repo_root: Path,
    runner: CommandRunner,
    worktree_base: str = "../",
    base_branch: str | None = None,
) -> list[Check]:
    """Create a test worktree and verify guardrails work."""
    from ....adapters.worktree._worktree import create_worktree

    checks: list[Check] = []
    worktree_path: Optional[Path] = None
    branch_name: Optional[str] = None

    try:
        worktree_path, branch_name, _, _, _, _, _ = create_worktree(
            repo_root=repo_root,
            issue_number=0,
            issue_title="doctor-guardrail-test",
            worktree_base=Path(worktree_base),
            base_branch=base_branch,
        )

        checks.append(Check(
            name="Test Worktree",
            status="ok",
            detail=f"Created at {worktree_path}",
        ))

        # Delegate to implementation
        checks.extend(check_guardrails_in_worktree_impl(worktree_path, runner))

    except Exception as e:
        checks.append(Check(
            name="Test Worktree",
            status="error",
            detail=f"Failed to create: {e}",
        ))
    finally:
        if worktree_path and worktree_path.exists():
            try:
                runner.run(
                    ["git", "worktree", "remove", "--force", str(worktree_path)],
                    cwd=repo_root,
                )
                if branch_name:
                    runner.run(
                        ["git", "branch", "-D", branch_name],
                        cwd=repo_root,
                    )
            except Exception:
                pass

    return checks
