# pyright: reportUnsupportedDunderAll=false
# Lazy __getattr__ exports are runtime-resolved; pyright cannot see them in __all__.
"""Port interfaces for the issue orchestrator hexagonal architecture."""

from importlib import import_module
from typing import Any

_EXPORTS = {
    "Issue": (".issue", "Issue"),
    "IssueTracker": (".issue_tracker", "IssueTracker"),
    "IssueRepository": (".issue_tracker", "IssueRepository"),
    "FreshIssueReader": (".fresh_issue_reader", "FreshIssueReader"),
    "LabelSet": (".label_set", "LabelSet"),
    "LabelManager": (".label_set", "LabelManager"),
    "PRInfo": (".pull_request_tracker", "PRInfo"),
    "PullRequestTracker": (".pull_request_tracker", "PullRequestTracker"),
    "PRRepository": (".pull_request_tracker", "PRRepository"),
    "ReviewState": (".pull_request_tracker", "ReviewState"),
    "SessionStore": (".session_store", "SessionStore"),
    "WorkingCopy": (".working_copy", "WorkingCopy"),
    "CommitInfo": (".working_copy", "CommitInfo"),
    "BranchStatus": (".working_copy", "BranchStatus"),
    "PushResult": (".working_copy", "PushResult"),
    "RebaseResult": (".working_copy", "RebaseResult"),
    "EventSink": (".event_sink", "EventSink"),
    "TraceEvent": (".event_sink", "TraceEvent"),
    "NullEventSink": (".event_sink", "NullEventSink"),
    "InMemoryEventSink": (".event_sink", "InMemoryEventSink"),
    "make_trace_event": (".event_sink", "make_trace_event"),
    "make_run_scoped_event": (".event_sink", "make_run_scoped_event"),
    "SessionRunner": (".session_runner", "SessionRunner"),
    "NullSessionRunner": (".session_runner", "NullSessionRunner"),
    "RepositoryHost": (".repository_host", "RepositoryHost"),
    "RepositoryHostError": (".repository_host", "RepositoryHostError"),
    "IssueResolver": (".issue_resolver", "IssueResolver"),
    "WorktreeManager": (".worktree_manager", "WorktreeManager"),
    "WorktreeInfo": (".worktree_manager", "WorktreeInfo"),
    "WorktreeReuseOptions": (".worktree_manager", "WorktreeReuseOptions"),
    "CommandRunner": (".command_runner", "CommandRunner"),
    "CommandResult": (".command_runner", "CommandResult"),
    "NullCommandRunner": (".command_runner", "NullCommandRunner"),
    "Git": (".git", "Git"),
    "GitResult": (".git", "GitResult"),
    "GitError": (".git", "GitError"),
    "TerminalObserver": (".terminal_observer", "TerminalObserver"),
    "NullTerminalObserver": (".terminal_observer", "NullTerminalObserver"),
    "SessionOutput": (".session_output", "SessionOutput"),
    "SessionRun": (".session_output", "SessionRun"),
    "ValidationRecord": (".session_output", "ValidationRecord"),
    "ValidationState": (".session_output", "ValidationState"),
    "ValidationEvidenceRecorder": (".run_evidence", "ValidationEvidenceRecorder"),
    "NullValidationEvidenceRecorder": (
        ".run_evidence", "NullValidationEvidenceRecorder",
    ),
    "ManifestDownloader": (".manifest_downloader", "ManifestDownloader"),
    "NullManifestDownloader": (".manifest_downloader", "NullManifestDownloader"),
    "GoalPilotStore": (".goal_pilot_store", "GoalPilotStore"),
    "AttemptStore": (".attempt_store", "AttemptStore"),
    "ProviderCircuitState": (".provider_resilience", "ProviderCircuitState"),
    "ProviderCircuitStore": (".provider_resilience", "ProviderCircuitStore"),
    "InMemoryProviderCircuitStore": (".provider_resilience", "InMemoryProviderCircuitStore"),
    "LabelStore": (".label_store", "LabelStore"),
    "QueueCacheStore": (".queue_cache_store", "QueueCacheStore"),
    "TimelineStore": (".timeline_store", "TimelineStore"),
    "TimelineRecord": (".timeline_store", "TimelineRecord"),
    "NullTimelineStore": (".timeline_store", "NullTimelineStore"),
    "TimelineReader": (".timeline_reader", "TimelineReader"),
    "NullTimelineReader": (".timeline_reader", "NullTimelineReader"),
    "TimelineWriter": (".timeline_writer", "TimelineWriter"),
    "NullTimelineWriter": (".timeline_writer", "NullTimelineWriter"),
    "BackgroundJobRunner": (".background_job", "BackgroundJobRunner"),
    "CompletedJob": (".background_job", "CompletedJob"),
    "NullBackgroundJobRunner": (".background_job", "NullBackgroundJobRunner"),
    "PersistentExchangePairRegistry": (
        ".persistent_exchange_pair_registry", "PersistentExchangePairRegistry",
    ),
}

__all__ = (
    "Issue",
    "IssueTracker",
    "IssueRepository",
    "FreshIssueReader",
    "LabelSet",
    "LabelManager",
    "PRInfo",
    "PullRequestTracker",
    "PRRepository",
    "ReviewState",
    "SessionStore",
    "WorkingCopy",
    "CommitInfo",
    "BranchStatus",
    "PushResult",
    "RebaseResult",
    "EventSink",
    "TraceEvent",
    "NullEventSink",
    "InMemoryEventSink",
    "make_trace_event",
    "make_run_scoped_event",
    "SessionRunner",
    "NullSessionRunner",
    "RepositoryHost",
    "RepositoryHostError",
    "IssueResolver",
    "WorktreeManager",
    "WorktreeInfo",
    "WorktreeReuseOptions",
    "CommandRunner",
    "CommandResult",
    "NullCommandRunner",
    "Git",
    "GitResult",
    "GitError",
    "TerminalObserver",
    "NullTerminalObserver",
    "SessionOutput",
    "SessionRun",
    "ValidationRecord",
    "ValidationState",
    "ValidationEvidenceRecorder",
    "NullValidationEvidenceRecorder",
    "ManifestDownloader",
    "NullManifestDownloader",
    "GoalPilotStore",
    "AttemptStore",
    "ProviderCircuitState",
    "ProviderCircuitStore",
    "InMemoryProviderCircuitStore",
    "LabelStore",
    "QueueCacheStore",
    "TimelineStore",
    "TimelineRecord",
    "NullTimelineStore",
    "TimelineReader",
    "NullTimelineReader",
    "TimelineWriter",
    "NullTimelineWriter",
    "BackgroundJobRunner",
    "CompletedJob",
    "NullBackgroundJobRunner",
    "PersistentExchangePairRegistry",
)


def __getattr__(name: str) -> Any:
    try:
        module_name, attr_name = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc

    value = getattr(import_module(module_name, __name__), attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted([*globals(), *__all__])
