"""Port protocol for label persistence."""

from __future__ import annotations

from typing import Protocol


class LabelStore(Protocol):
    """Tracks which labels the orchestrator has applied to issues."""

    def add_label(self, issue_number: int, label: str) -> None: ...
    def remove_label(self, issue_number: int, label: str) -> None: ...
    def save_labels(self, issue_number: int, labels: set[str]) -> None: ...
    def load_labels(self, issue_number: int) -> set[str]: ...
    def load_all(self) -> dict[int, set[str]]: ...
    def remove_issue(self, issue_number: int) -> None: ...
    def clear(self) -> None: ...
