"""Port protocol for queue cache persistence."""

from __future__ import annotations

from typing import TYPE_CHECKING, Mapping, Protocol, Sequence

from ..domain.issue_work_classification import IssueWorkClassification

if TYPE_CHECKING:
    from .issue import Issue


class QueueCacheStore(Protocol):
    """Persists the in-scope issue snapshot across restarts."""

    def load_work_classifications(self, repo: str) -> dict[int, IssueWorkClassification]: ...
    def record_work_classifications(
        self, repo: str, classifications: Mapping[int, IssueWorkClassification],
    ) -> None: ...
    def load_issues(self, repo: str) -> Sequence["Issue"]: ...
    def load_watermark(self) -> str | None: ...
    def load_last_health_review_at(self) -> float: ...
    def save_last_health_review_at(self, value: float) -> None: ...
    def load_last_reviewed_board_fingerprint(self) -> str: ...
    def save_last_reviewed_board_fingerprint(self, value: str) -> None: ...
    def load_last_stuck_sweep_at(self) -> float: ...
    def save_last_stuck_sweep_at(self, value: float) -> None: ...
    def load_recovery_attempts(self) -> dict[int, int]: ...
    def save_recovery_attempts(self, value: dict[int, int]) -> None: ...
    def load_pending_escalations(self) -> set[int]: ...
    def save_pending_escalations(self, value: set[int]) -> None: ...
    def save_snapshot(
        self,
        issues: Sequence["Issue"],
        watermark: str | None,
        repo: str = "",
    ) -> None: ...
    def clear(self) -> None: ...
