"""Required admission-only lifecycle capability; grants no publication authority."""

from typing import Protocol
from ..domain.validated_work_commands import AutomaticCaptureCommand, ValidatedWorkDispositionBatch
from ..domain.validated_work_store import AdmissionOutcome, EvidenceAdmission, EvidenceLookup, EvidenceRow


class ValidatedWorkAdmissionStore(Protocol):
    def retained_evidence(self, issue_number: int) -> tuple[EvidenceRow, ...]: ...
    def admit(self, admission: EvidenceAdmission) -> AdmissionOutcome: ...
    def for_issue(self, issue_number: int) -> ValidatedWorkDispositionBatch: ...
    def has_unresolved_work(self, issue_number: int) -> bool: ...
    def evidence_for_id(self, evidence_id: str) -> EvidenceLookup | None: ...


class ValidatedWorkPreservation(Protocol):
    def dispose_at_termination(self, command: AutomaticCaptureCommand) -> ValidatedWorkDispositionBatch: ...
    def has_unresolved_work(self, issue_number: int) -> bool: ...
    def for_issue(self, issue_number: int) -> ValidatedWorkDispositionBatch: ...
